from pathlib import Path
import re

VERSION='20260922-unified-chat1'

p=Path('index.html')
s=p.read_text(encoding='utf-8')
s=re.sub(r'<form class="sv-search" id="universalSearch"[\s\S]*?</form>\s*', '', s, count=1)
s=s.replace('AI does not invent live prices, availability, verification, jobs, Wi‑Fi access or company replies. Use provider/source links for live confirmation.', 'One conversation: type, speak, take a photo or attach an image/text file. SEEKVERA replies in your language and never invents live prices, availability or verification.')
new_chat='''<div class="sv-chat-card sv-unified-chat" id="aiChat" aria-label="SEEKVERA AI Chat">
<div class="sv-chat-head"><div><b>✨ SEEKVERA AI</b><small>Chat · Voice · Camera · Attach</small></div><span>● Online</span><button id="aiChatSpeaker" class="sv-speaker" type="button" aria-label="Voice reply on or off">🔊</button></div>
<div class="sv-chat-messages" id="aiMessages" aria-live="polite"><div class="ai-msg bot">Hi. Message me in your language. You can type, speak, take a photo or attach an image/text file.</div></div>
<form class="sv-chat-form sv-unified-compose" id="aiChatForm">
<button class="attach" id="aiChatAttach" type="button" aria-label="Attach image or text file">📎</button>
<input id="aiChatInput" autocomplete="off" maxlength="1800" placeholder="Message SEEKVERA AI…" aria-label="Message SEEKVERA AI">
<button class="camera" id="aiChatCamera" type="button" aria-label="Take a photo">📷</button>
<button class="mic" id="aiChatMic" type="button" aria-label="Speak to SEEKVERA AI">🎤</button>
<button class="send" type="submit" aria-label="Send">➤</button>
<input id="aiChatFile" type="file" accept="image/jpeg,image/png,image/webp,text/plain,.txt" hidden>
<input id="aiChatCameraFile" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" hidden>
</form><div class="sv-attachment-state" id="aiAttachmentState" hidden></div><div class="sv-ai-actions" id="aiActions"></div></div>'''
s,n=re.subn(r'<div class="sv-chat-card" id="aiChat"[\s\S]*?<div class="sv-ai-panel" id="aiResult"', new_chat+'\n<div class="sv-ai-panel" id="aiResult"', s, count=1)
if n!=1:
    raise SystemExit('homepage AI chat block not found')
s=s.replace('20260922-premium-voice2',VERSION)
p.write_text(s,encoding='utf-8')

p=Path('superapp.js')
s=p.read_text(encoding='utf-8')
s=s.replace("if(pending){pending.textContent=d.response;pending.classList.remove('thinking')}if(ans)ans.textContent=d.response;if(actions)actions.innerHTML=actionLinks(d.category||cat,q)","if(pending){pending.textContent=d.response;pending.classList.remove('thinking')}if(ans)ans.textContent=d.response;if(actions)actions.innerHTML=actionLinks(d.category||cat,q);window.dispatchEvent(new CustomEvent('seekvera:ai-response',{detail:{text:d.response,language:d.language||lang()}}))")
old="function bindAIChat(){const f=$('#aiChatForm'),i=$('#aiChatInput');if(f&&i)f.addEventListener('submit',e=>{e.preventDefault();const q=i.value.trim();if(!q)return;i.value='';askAI(q)});$('#aiChatMic')?.addEventListener('click',()=>{const fab=$('#svVoiceFab');if(fab)fab.click();else $('#heroVoice')?.click()})}"
new="""async function handleChatAttachment(file){if(!file)return;const state=$('#aiAttachmentState');if(state){state.hidden=false;state.textContent='Checking '+file.name+'…'}try{if(file.type==='text/plain'||/\\.txt$/i.test(file.name)){if(file.size>256*1024)throw Error('Text file is too large. Use a TXT file up to 256 KB.');const text=clean(await file.text(),3500);if(!text)throw Error('The text file is empty.');if(state){state.textContent='📎 '+file.name;setTimeout(()=>state.hidden=true,3500)}await askAI('Attached text file '+file.name+':\\n'+text);return}if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024)throw Error('Use JPG, PNG, WebP up to 5 MB, or TXT up to 256 KB.');const data=await fileToDataURL(file);chatAdd('user','📷 '+file.name);const pending=chatAdd('bot','Checking the image with Safety Gate and AI Vision…','thinking');const r=await fetch(api('/api/visual-search'),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({image:data,country:selectedCountryName(),language:lang()})});const d=await r.json().catch(()=>({}));let msg='';if(!r.ok||d.allowed===false||d.blocked)msg=d.reason?'Image not accepted: '+d.reason:'This image cannot be processed.';else if(d.reviewRequired)msg='This image needs review before visual search can continue.';else msg=[d.summary,d.guidance,d.suggestedQuery&&('Suggested search: '+d.suggestedQuery)].filter(Boolean).join('\\n')||'Image checked. Visual search is ready.';if(pending){pending.textContent=msg;pending.classList.remove('thinking')}if(state){state.textContent='📷 '+file.name;setTimeout(()=>state.hidden=true,3500)}}catch(e){chatAdd('bot',e?.message||'Attachment could not be processed.');if(state){state.textContent=e?.message||'Attachment could not be processed.'}}}
function bindAIChat(){const f=$('#aiChatForm'),i=$('#aiChatInput');if(f&&i)f.addEventListener('submit',e=>{e.preventDefault();const q=i.value.trim();if(!q)return;i.value='';askAI(q)});$('#aiChatMic')?.addEventListener('click',()=>window.dispatchEvent(new CustomEvent('seekvera:voice',{detail:{targetId:'aiChatInput'}})));const file=$('#aiChatFile'),cam=$('#aiChatCameraFile');$('#aiChatAttach')?.addEventListener('click',()=>file?.click());$('#aiChatCamera')?.addEventListener('click',()=>cam?.click());file?.addEventListener('change',()=>{const x=file.files?.[0];if(x)handleChatAttachment(x);file.value=''});cam?.addEventListener('change',()=>{const x=cam.files?.[0];if(x)handleChatAttachment(x);cam.value=''})}"""
if old not in s:
    raise SystemExit('bindAIChat block not found')
s=s.replace(old,new)
p.write_text(s,encoding='utf-8')

Path('voice-ai.js').write_text(r'''(()=>{
'use strict';
if(window.__seekveraVoiceAI)return;window.__seekveraVoiceAI=true;
const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;
const LANGS={en:'en-US',ar:'ar-SA',fr:'fr-FR',zh:'zh-CN',es:'es-ES',hi:'hi-IN',pt:'pt-BR',de:'de-DE',ja:'ja-JP',ko:'ko-KR',id:'id-ID',tr:'tr-TR',ru:'ru-RU',ur:'ur-PK',bn:'bn-BD',vi:'vi-VN',it:'it-IT',sw:'sw-KE',th:'th-TH',fa:'fa-IR',pl:'pl-PL',nl:'nl-NL',ms:'ms-MY',fil:'fil-PH',ha:'ha-NG',yo:'yo-NG',ig:'ig-NG',am:'am-ET'};
const FEMALE_HINTS=/aria|jenny|zira|samantha|victoria|karen|moira|tessa|ava|allison|susan|hazel|fiona|serena|veena|heera|lekha|monica|amelie|audrey|julie|celine|hortense|laila|layla|salma|hoda|farah|mariam|maryam|amira|zahra|female|woman/i;
const MALE_HINTS=/david|mark|george|daniel|fred|ralph|bruce|hammad|hamed|majed|maged|male|man/i;
const QUALITY_HINTS=/neural|natural|enhanced|premium|online|google|microsoft|siri/i;
let recognition=null,lastAnswer='',lastLocale='',muted=localStorage.getItem('seekvera_voice_muted')==='1',activeButton=null;
function locale(){const e=document.getElementById('lang');let code=(e?.value||localStorage.getItem('seekvera_lang')||navigator.language||'en').toLowerCase();const label=e?.options?.[e.selectedIndex]?.textContent||'';if(code==='auto'||/auto/i.test(label))return navigator.language||'en-US';code=code.split('_')[0];return LANGS[code]||navigator.language||'en-US'}
function localeForText(t,requested){t=String(t||'');const r=String(requested||'').toLowerCase();if(r&&r!=='auto'&&LANGS[r])return LANGS[r];if(/[\u0600-\u06ff]/.test(t))return 'ar-SA';if(/[\u4e00-\u9fff]/.test(t))return 'zh-CN';if(/[\u3040-\u30ff]/.test(t))return 'ja-JP';if(/[\uac00-\ud7af]/.test(t))return 'ko-KR';if(/[\u0900-\u097f]/.test(t))return 'hi-IN';if(/[\u0980-\u09ff]/.test(t))return 'bn-BD';if(/[\u0400-\u04ff]/.test(t))return 'ru-RU';return locale()}
function pickVoice(l){const vs=speechSynthesis?.getVoices?.()||[];if(!vs.length)return null;const w=String(l||'').toLowerCase(),b=w.split('-')[0];let c=vs.filter(v=>String(v.lang||'').toLowerCase().startsWith(b));if(!c.length)c=vs;const sc=v=>{const n=(v.name||'')+' '+(v.voiceURI||''),vl=String(v.lang||'').toLowerCase();let x=0;if(vl===w)x+=120;else if(vl.startsWith(b))x+=75;if(QUALITY_HINTS.test(n))x+=40;if(FEMALE_HINTS.test(n))x+=48;if(MALE_HINTS.test(n))x-=60;if(v.default)x+=8;return x};return [...c].sort((a,b)=>sc(b)-sc(a))[0]||null}
function stopSpeech(){try{speechSynthesis.cancel()}catch(_){}}
function cleanSpeech(t){return String(t||'').replace(/```[\s\S]*?```/g,' ').replace(/https?:\/\/\S+/g,' ').replace(/[*_#>`~|]/g,' ').replace(/\s+/g,' ').trim()}
function speak(text,l){lastAnswer=String(text||'');lastLocale=localeForText(lastAnswer,l);if(muted||!lastAnswer||!('speechSynthesis'in window))return;stopSpeech();const u=new SpeechSynthesisUtterance(cleanSpeech(lastAnswer));u.lang=lastLocale;const v=pickVoice(lastLocale);if(v)u.voice=v;u.rate=1.02;u.pitch=1.07;u.volume=1;speechSynthesis.speak(u)}
function setMic(on){if(!activeButton)return;activeButton.classList.toggle('listening',on);activeButton.textContent=on?'■':'🎤'}
function start(targetId,button){stopSpeech();if(recognition){try{recognition.stop()}catch(_){ }return}activeButton=button||document.getElementById('aiChatMic')||document.querySelector('.sv-global-compose .mic');if(!SpeechRecognition){const i=document.getElementById(targetId||'aiChatInput');if(i)i.placeholder='Voice recognition is unavailable here — please type your message.';return}const r=new SpeechRecognition();recognition=r;r.lang=locale();r.interimResults=true;r.continuous=false;r.maxAlternatives=1;let final='';r.onstart=()=>setMic(true);r.onresult=e=>{let interim='';for(let x=e.resultIndex;x<e.results.length;x++){const t=e.results[x][0].transcript;if(e.results[x].isFinal)final+=(final?' ':'')+t;else interim+=t}const i=document.getElementById(targetId||'aiChatInput');if(i)i.value=(final||interim).trim()};r.onerror=()=>{};r.onend=()=>{setMic(false);recognition=null;const i=document.getElementById(targetId||'aiChatInput');if(i&&i.value.trim())i.form?.requestSubmit?.()};try{r.start()}catch(_){recognition=null;setMic(false)}}
function toggleMute(btn){muted=!muted;localStorage.setItem('seekvera_voice_muted',muted?'1':'0');document.querySelectorAll('#aiChatSpeaker,.sv-global-speaker').forEach(b=>b.textContent=muted?'🔇':'🔊');if(muted)stopSpeech();else if(lastAnswer)speak(lastAnswer,lastLocale);if(btn)btn.textContent=muted?'🔇':'🔊'}
window.addEventListener('seekvera:voice',e=>start(e.detail?.targetId,e.detail?.button));
window.addEventListener('seekvera:ai-response',e=>speak(e.detail?.text,e.detail?.language));
document.addEventListener('click',e=>{const mic=e.target.closest('#aiChatMic,.sv-global-compose .mic');if(mic){e.preventDefault();const input=mic.closest('form')?.querySelector('input[type="text"],input:not([type])');start(input?.id,mic)}const sp=e.target.closest('#aiChatSpeaker,.sv-global-speaker');if(sp){e.preventDefault();toggleMute(sp)}});
document.addEventListener('DOMContentLoaded',()=>document.querySelectorAll('#aiChatSpeaker,.sv-global-speaker').forEach(b=>b.textContent=muted?'🔇':'🔊'),{once:true});
})();
''',encoding='utf-8')

Path('global-ui.js').write_text(r'''/* SEEKVERA Worldwide Premium UI — unified AI composer */
(()=>{'use strict';
const W=location.hostname.endsWith('workers.dev')?'':'https://seekvera-main.seekvera-global.workers.dev';const api=p=>`${W}${p}`;const $=s=>document.querySelector(s);const lang=()=>localStorage.getItem('seekvera_lang')||document.documentElement.lang||navigator.language||'auto';
function addMsg(box,role,text,thinking=false){const d=document.createElement('div');d.className=`sv-global-msg ${role}${thinking?' thinking':''}`;d.textContent=String(text||'');box.appendChild(d);box.scrollTop=box.scrollHeight;return d}
function country(){const e=$('#country');return e?.options?.[e.selectedIndex]?.textContent||'Worldwide'}
async function ask(box,input){const q=String(input.value||'').trim();if(!q)return;input.value='';addMsg(box,'user',q);const p=addMsg(box,'bot','SEEKVERA AI is thinking…',true);try{const r=await fetch(api('/api/ai'),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:q,country:country(),language:lang(),scope:'worldwide',fast:true})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.response)throw Error(d.error||'AI unavailable');p.textContent=d.response;p.classList.remove('thinking');window.dispatchEvent(new CustomEvent('seekvera:ai-response',{detail:{text:d.response,language:d.language||lang()}}))}catch(e){p.textContent='SEEKVERA AI is temporarily unavailable. Please try again.';p.classList.remove('thinking')}}
function dataURL(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
async function attach(box,input,file){if(!file)return;try{if(file.type==='text/plain'||/\.txt$/i.test(file.name)){if(file.size>256*1024)throw Error('Use TXT up to 256 KB.');input.value=('Attached text file '+file.name+':\n'+(await file.text()).slice(0,3500));input.form?.requestSubmit?.();return}if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024)throw Error('Use JPG, PNG, WebP up to 5 MB, or TXT up to 256 KB.');addMsg(box,'user','📷 '+file.name);const p=addMsg(box,'bot','Checking image with Safety Gate and AI Vision…',true);const r=await fetch(api('/api/visual-search'),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({image:await dataURL(file),country:country(),language:lang()})});const d=await r.json().catch(()=>({}));p.textContent=!r.ok||d.allowed===false?(d.reason||'Image could not be processed.'):d.reviewRequired?'Image needs review before visual search can continue.':[d.summary,d.guidance,d.suggestedQuery&&('Suggested search: '+d.suggestedQuery)].filter(Boolean).join('\n')||'Visual search ready.';p.classList.remove('thinking')}catch(e){addMsg(box,'bot',e?.message||'Attachment could not be processed.')}}
function buildSideChat(dock){const chat=document.createElement('aside');chat.className='sv-global-chat';chat.id='svGlobalChat';chat.innerHTML=`<div class="sv-global-chat-head"><b>✨ SEEKVERA AI</b><small>● Online</small><button class="sv-global-speaker" type="button" aria-label="Voice reply">🔊</button><button class="close" type="button" aria-label="Close">×</button></div><div class="sv-global-chat-body"><div class="sv-global-messages" id="svGlobalMessages"><div class="sv-global-msg bot">Message me in your language — type, speak, take a photo or attach a file.</div></div><form class="sv-global-compose" id="svGlobalForm"><button class="attach" type="button" aria-label="Attach">📎</button><input id="svGlobalInput" type="text" maxlength="1800" autocomplete="off" placeholder="Message SEEKVERA AI…"><button class="camera" type="button" aria-label="Camera">📷</button><button class="mic" type="button" aria-label="Voice">🎤</button><button class="send" type="submit" aria-label="Send">➤</button><input class="file" type="file" accept="image/jpeg,image/png,image/webp,text/plain,.txt" hidden><input class="camfile" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" hidden></form></div>`;document.body.appendChild(chat);const f=$('#svGlobalForm'),i=$('#svGlobalInput'),m=$('#svGlobalMessages'),file=f.querySelector('.file'),cam=f.querySelector('.camfile');f.addEventListener('submit',e=>{e.preventDefault();ask(m,i)});f.querySelector('.attach').addEventListener('click',()=>file.click());f.querySelector('.camera').addEventListener('click',()=>cam.click());file.addEventListener('change',()=>{const x=file.files?.[0];if(x)attach(m,i,x);file.value=''});cam.addEventListener('change',()=>{const x=cam.files?.[0];if(x)attach(m,i,x);cam.value=''});f.querySelector('.mic').addEventListener('click',e=>window.dispatchEvent(new CustomEvent('seekvera:voice',{detail:{targetId:'svGlobalInput',button:e.currentTarget}})));chat.querySelector('.close').addEventListener('click',()=>{chat.classList.remove('open');document.body.classList.remove('sv-chat-open')});dock.querySelector('.sv-ai-open').addEventListener('click',()=>{const open=!chat.classList.contains('open');chat.classList.toggle('open',open);$('#svGlobalSafety')?.classList.remove('open');document.body.classList.toggle('sv-chat-open',open);if(open)setTimeout(()=>i.focus(),80)});return chat}
function compactRequestOnHome(){if(!document.body.classList.contains('sv-home-global'))return;const section=$('#request'),form=$('#requestForm');if(!section||!form||section.dataset.compact==='1')return;section.dataset.compact='1';section.classList.add('sv-request-compact');form.hidden=true;const head=section.querySelector('.sv-section-head');if(!head)return;const btn=document.createElement('button');btn.type='button';btn.className='sv-pill-btn sv-request-toggle';btn.textContent='Open Request Form';btn.addEventListener('click',()=>{const open=form.hidden;form.hidden=!open;section.classList.toggle('open',open);btn.textContent=open?'Close Request Form':'Open Request Form'});head.appendChild(btn)}
function init(){document.documentElement.classList.add('sv-global-ui');document.body.classList.add('sv-global-ready');const home=location.pathname==='/'||/\/index\.html$/.test(location.pathname);if(home)document.body.classList.add('sv-home-global');const inline=$('#aiChat');if(inline)inline.classList.add('sv-inline-ai-visible');const dock=document.createElement('nav');dock.className='sv-global-dock';dock.setAttribute('aria-label','SEEKVERA quick tools');dock.innerHTML=`<a href="index.html" aria-label="Home">⌂<span class="sv-global-tip">Home</span></a><a href="hub.html" aria-label="All categories">▦<span class="sv-global-tip">Categories</span></a><button class="sv-ai-open" type="button" aria-label="AI chat">✨<span class="sv-global-tip">AI Chat</span></button><a href="post-ad.html" aria-label="Post ad">＋<span class="sv-global-tip">Post Ad</span></a><button class="sv-safety-open" type="button" aria-label="Safety">🛡️<span class="sv-global-tip">Safety</span></button>`;document.body.appendChild(dock);let chat=null;if(home){dock.querySelector('.sv-ai-open').addEventListener('click',()=>{inline?.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>$('#aiChatInput')?.focus(),350)})}else chat=buildSideChat(dock);const safety=document.createElement('aside');safety.className='sv-global-safety';safety.id='svGlobalSafety';safety.innerHTML=`<span class="ok">🛡️ Central Safety Gate active</span><h3>SEEKVERA Safety</h3><p>Listings, requests and uploaded images use centralized text and AI Vision checks before approval or publication.</p><p>Unsafe content is blocked and uncertain content is held for review.</p>`;document.body.appendChild(safety);dock.querySelector('.sv-safety-open').addEventListener('click',()=>{safety.classList.toggle('open');chat?.classList.remove('open');document.body.classList.remove('sv-chat-open')});compactRequestOnHome();document.querySelectorAll('a[href]').forEach(a=>{const h=a.getAttribute('href')||'';if(/^javascript:/i.test(h))a.removeAttribute('href')})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,0),{once:true});else setTimeout(init,0);
})();
''',encoding='utf-8')

p=Path('global-ui.css')
css=p.read_text(encoding='utf-8')
marker='/* Unified premium AI conversation — one compact WhatsApp-style composer */'
if marker not in css:
    css+='''\n/* Unified premium AI conversation — one compact WhatsApp-style composer */
body.sv-home-global .sv-search{display:none!important}
body.sv-home-global .sv-search-note{margin:8px 0 6px!important;color:#bdcada!important;line-height:1.35}
.sv-unified-chat{margin-top:8px!important;border-radius:22px!important;border:1px solid rgba(255,255,255,.14)!important;box-shadow:0 16px 40px rgba(0,0,0,.18)!important}
.sv-unified-chat .sv-chat-head{padding:10px 12px!important;background:linear-gradient(135deg,#0c2139,#173b60)!important}.sv-unified-chat .sv-chat-head>div{min-width:0;display:flex;align-items:center;gap:8px}.sv-unified-chat .sv-chat-head small{font-size:.68rem;color:#9cb0c7;white-space:nowrap}.sv-speaker,.sv-global-speaker{border:0;background:rgba(255,255,255,.12);color:#fff;border-radius:10px;width:34px;height:34px;display:grid;place-items:center;cursor:pointer}.sv-chat-messages{min-height:72px!important;max-height:210px!important;padding:10px 11px!important}.sv-chat-messages .ai-msg{font-size:.88rem!important;padding:9px 11px!important}.sv-unified-compose{display:grid!important;grid-template-columns:40px minmax(0,1fr) 40px 40px 44px!important;gap:6px!important;padding:8px!important;align-items:center}.sv-unified-compose input#aiChatInput{height:42px!important;border-radius:21px!important;padding:0 14px!important;background:#f7f9fb!important}.sv-unified-compose button{width:40px!important;height:40px!important;padding:0!important;border-radius:50%!important;display:grid!important;place-items:center!important}.sv-unified-compose .attach,.sv-unified-compose .camera,.sv-unified-compose .mic{background:#eef3f8!important;color:#17304f!important}.sv-unified-compose .send{background:var(--svg-green)!important;color:#fff!important;font-size:1.05rem}.sv-unified-compose .mic.listening,.sv-global-compose .mic.listening{background:#d92d20!important;color:#fff!important}.sv-attachment-state{margin:0 10px 8px;padding:6px 9px;border-radius:10px;background:#eef7f3;color:#087a50;font-size:.74rem;font-weight:750}
.sv-global-compose{grid-template-columns:40px minmax(0,1fr) 40px 40px 44px!important;gap:6px!important;padding:8px!important}.sv-global-compose>button{width:40px;height:40px;padding:0!important;border-radius:50%!important;display:grid!important;place-items:center!important}.sv-global-compose input#svGlobalInput{height:42px;border-radius:21px!important;padding:0 13px!important}.sv-global-compose .attach,.sv-global-compose .camera,.sv-global-compose .mic{background:#eef3f8}.sv-global-compose .send{background:var(--svg-green)!important;color:#fff!important}.sv-global-chat-head{height:52px!important}.sv-global-chat-head .close{border:0;background:rgba(255,255,255,.12);color:#fff;border-radius:9px;width:34px;height:34px}.sv-global-dock{gap:6px!important}
@media(max-width:600px){body.sv-home-global .sv-hero{padding:13px 10px 12px!important;border-radius:20px!important}body.sv-home-global .sv-kicker{font-size:.61rem!important;padding:5px 8px!important}body.sv-home-global .sv-hero h1{font-size:1.55rem!important;line-height:1.04!important;margin:8px 0 6px!important;letter-spacing:-.025em!important}body.sv-home-global .sv-lead{font-size:.8rem!important;line-height:1.35!important;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}body.sv-home-global .sv-scope{margin:8px 0 6px!important}body.sv-home-global .sv-scope button{padding:6px 9px!important;font-size:.72rem!important}.sv-unified-chat{margin-top:6px!important}.sv-unified-chat .sv-chat-head{padding:8px 10px!important}.sv-unified-chat .sv-chat-head small{display:none}.sv-chat-messages{min-height:58px!important;max-height:155px!important;padding:8px!important}.sv-chat-messages .ai-msg{font-size:.82rem!important}.sv-unified-compose{grid-template-columns:38px minmax(0,1fr) 38px 38px 40px!important;gap:4px!important;padding:6px!important}.sv-unified-compose button{width:38px!important;height:38px!important}.sv-unified-compose input#aiChatInput{height:40px!important;font-size:.86rem!important;padding:0 11px!important}.sv-global-dock{bottom:7px!important;padding:5px!important}.sv-global-dock a,.sv-global-dock button{width:43px!important;height:42px!important}.sv-global-chat{bottom:58px!important;height:min(64vh,560px)!important}.sv-global-compose{grid-template-columns:38px minmax(0,1fr) 38px 38px 40px!important;gap:4px!important}.sv-global-compose>button{width:38px;height:38px}.sv-global-compose input#svGlobalInput{height:40px;font-size:.86rem}}
'''
p.write_text(css,encoding='utf-8')

for hp in Path('.').glob('*.html'):
    t=hp.read_text(encoding='utf-8')
    t=t.replace('20260922-premium-voice2',VERSION)
    hp.write_text(t,encoding='utf-8')

ap=Path('.github/workflows/premium-worldwide-live-a-z-final.yml')
if ap.exists():
    t=ap.read_text(encoding='utf-8').replace("VERSION='20260922-premium-voice2'",f"VERSION='{VERSION}'")
    ap.write_text(t,encoding='utf-8')
