(()=>{
'use strict';
const SB='https://nrdpyydfrpmqedtzmbyw.supabase.co',KEY='sb_publishable_tqqPQxqdNowIsSlJz4bW5w_kHOC905o';
const $=s=>document.querySelector(s);let access=sessionStorage.getItem('sv_da_access')||'';
function headers(){return{apikey:KEY,Authorization:`Bearer ${access||KEY}`,'content-type':'application/json'}}
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function parseHash(){const p=new URLSearchParams(location.hash.slice(1));const t=p.get('access_token');if(t){access=t;sessionStorage.setItem('sv_da_access',t);history.replaceState(null,'',location.pathname+location.search);return true}return false}
async function authUser(){if(!access)return null;const r=await fetch(`${SB}/auth/v1/user`,{headers:{apikey:KEY,Authorization:`Bearer ${access}`}});if(!r.ok){sessionStorage.removeItem('sv_da_access');access='';return null}return r.json()}
async function sendMagic(){const email=$('#ownerEmail').value.trim();if(!email){$('#authStatus').textContent='Enter the owner business email.';return}$('#authStatus').textContent='Sending secure sign-in link…';const r=await fetch(`${SB}/auth/v1/otp`,{method:'POST',headers:{apikey:KEY,'content-type':'application/json'},body:JSON.stringify({email,options:{emailRedirectTo:location.origin+location.pathname}})});$('#authStatus').textContent=r.ok?'Sign-in link sent. Open it on this device, then return here.':'Could not send the sign-in link. Check Supabase Auth email configuration.'}
async function upsertSettings(){if(!access){$('#settingsStatus').textContent='Sign in first.';return}const mode=$('#mode').value;const payload={mode,zero_cost:true,voice_mode:'off',paid_actions:'ask_first',auto_recharge:false,contract_signing:'owner_approval',payments:'owner_approval',bank_changes:'owner_verification',high_scam_risk:'auto_pause'};const r=await fetch(`${SB}/rest/v1/deal_agent_settings?on_conflict=owner_id`,{method:'POST',headers:{...headers(),Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify(payload)});$('#settingsStatus').textContent=r.ok?'Owner settings saved securely.':'Could not save settings.';if(r.ok)setAgentState(mode)}
function setAgentState(mode){const e=$('#agentState');e.textContent=mode==='off'?'OFF':'ON';e.className='state '+(mode==='off'?'off':'on')}
async function loadSettings(){if(!access)return;const r=await fetch(`${SB}/rest/v1/deal_agent_settings?select=*&limit=1`,{headers:headers()});if(r.ok){const rows=await r.json();if(rows[0]){$('#mode').value=rows[0].mode||'off';setAgentState($('#mode').value);$('#settingsStatus').textContent='Server settings loaded.'}}}
async function createMission(){if(!access){$('#missionStatus').textContent='Sign in first.';return}const sector=$('#sector').value.trim(),country=$('#missionCountry').value.trim(),goal=$('#goal').value.trim();if(!sector||!country||!goal){$('#missionStatus').textContent='Sector, country and goal are required.';return}const payload={sector,country,city:$('#missionCity').value.trim(),goal,target_count:Math.max(1,Math.min(500,Number($('#targetCount').value)||20)),product_service:$('#product').value.trim(),target_terms:$('#commission').value.trim(),language:$('#missionLanguage').value,mission_type:$('#missionMode').value,status:'draft'};const r=await fetch(`${SB}/rest/v1/deal_missions`,{method:'POST',headers:{...headers(),Prefer:'return=representation'},body:JSON.stringify(payload)});if(!r.ok){const t=await r.text();$('#missionStatus').textContent='Could not save mission.';console.warn(t);return}$('#missionStatus').textContent='Mission saved as draft. No outreach has been sent.';loadMissions()}
async function loadMissions(){if(!access)return;const r=await fetch(`${SB}/rest/v1/deal_missions?select=id,sector,country,city,goal,target_count,status,created_at&order=created_at.desc&limit=10`,{headers:headers()});if(!r.ok)return;const rows=await r.json();$('#missionList').innerHTML=rows.length?rows.map(m=>`<div class="mission"><b>${esc(m.sector)} · ${esc(m.country)}${m.city?' · '+esc(m.city):''}</b><small>${esc(m.status)} · target ${Number(m.target_count)||0}</small><div>${esc(m.goal)}</div></div>`).join(''):'<div class="sv-status">No missions yet.</div>'}
async function count(table,filter=''){if(!access)return null;const r=await fetch(`${SB}/rest/v1/${table}?select=id${filter?'&'+filter:''}`,{method:'HEAD',headers:{...headers(),Prefer:'count=exact'}});const range=r.headers.get('content-range')||'';const m=range.match(/\/(\d+)$/);return m?Number(m[1]):0}
async function loadMetrics(){if(!access)return;const vals=await Promise.all([count('deal_leads'),count('deal_leads','status=eq.contacted'),count('deal_leads','status=eq.hot_lead'),count('deal_leads','risk=eq.high'),count('deal_approvals','status=eq.pending'),count('deal_money_notices','status=eq.pending'),count('deal_leads','status=eq.won')]);['mLeads','mContacted','mHot','mRisk','mApprovals','mMoney','mWon'].forEach((id,i)=>$('#'+id).textContent=vals[i]??'—');$('#metricsStatus').textContent='Live counts from your private Deal Agent database.'}
async function init(){parseHash();$('#magicBtn').onclick=sendMagic;$('#logoutBtn').onclick=()=>{sessionStorage.removeItem('sv_da_access');access='';location.reload()};$('#saveSettings').onclick=upsertSettings;$('#createMission').onclick=createMission;const u=await authUser();if(u){$('#authStatus').textContent=`Signed in securely as ${u.email||'owner'}.`;await Promise.all([loadSettings(),loadMissions(),loadMetrics()])}else $('#authStatus').textContent='Not signed in.'}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
