/* SEEKVERA Games — 50 free self-contained mini games */
(()=>{'use strict';
const GAMES=[
{id:'neon-highway',name:'Neon Highway',cat:'Racing',icon:'🏎️',mode:'lane',theme:'city',speed:6,diff:1,desc:'Switch lanes and avoid neon traffic.'},
{id:'desert-drift',name:'Desert Drift',cat:'Racing',icon:'🚙',mode:'lane',theme:'desert',speed:6.4,diff:2,desc:'Race across a fast desert highway.'},
{id:'city-turbo',name:'City Turbo',cat:'Racing',icon:'🚗',mode:'lane',theme:'city',speed:7,diff:2,desc:'Fast city traffic with tighter gaps.'},
{id:'jungle-rally',name:'Jungle Rally',cat:'Racing',icon:'🛻',mode:'lane',theme:'forest',speed:6.2,diff:2,desc:'Dodge jungle obstacles on a wild rally road.'},
{id:'night-rider',name:'Night Rider',cat:'Racing',icon:'🏍️',mode:'lane',theme:'night',speed:7.5,diff:3,desc:'High-speed night racing.'},
{id:'ice-road',name:'Ice Road',cat:'Racing',icon:'🚘',mode:'lane',theme:'ice',speed:6.8,diff:3,desc:'Stay sharp on a slippery frozen route.'},
{id:'superbike-rush',name:'Superbike Rush',cat:'Racing',icon:'🏍️',mode:'lane',theme:'sunset',speed:8,diff:4,desc:'A quick superbike lane challenge.'},
{id:'monster-track',name:'Monster Track',cat:'Racing',icon:'🚜',mode:'lane',theme:'canyon',speed:6.6,diff:4,desc:'Heavy obstacles and a rough canyon track.'},
{id:'sky-racer',name:'Sky Racer',cat:'Flying',icon:'✈️',mode:'flight',theme:'sky',speed:5.5,diff:1,desc:'Fly through open sky gates.'},
{id:'jet-canyon',name:'Jet Canyon',cat:'Flying',icon:'🛩️',mode:'flight',theme:'canyon',speed:6.2,diff:2,desc:'Keep your jet clear of canyon towers.'},
{id:'space-wings',name:'Space Wings',cat:'Flying',icon:'🚀',mode:'flight',theme:'space',speed:6.4,diff:3,desc:'Pilot through a field of space gates.'},
{id:'ocean-patrol',name:'Ocean Patrol',cat:'Flying',icon:'🚁',mode:'flight',theme:'ocean',speed:5.8,diff:2,desc:'Low-altitude patrol above the ocean.'},
{id:'cloud-dash',name:'Cloud Dash',cat:'Flying',icon:'🛫',mode:'flight',theme:'cloud',speed:7,diff:4,desc:'Fast flight through narrow cloud lanes.'},
{id:'forest-runner',name:'Forest Runner',cat:'Adventure',icon:'🌲',mode:'runner',theme:'forest',speed:6,diff:1,desc:'Jump logs and keep running through the forest.'},
{id:'temple-escape',name:'Temple Escape',cat:'Adventure',icon:'🗿',mode:'runner',theme:'temple',speed:6.4,diff:2,desc:'Escape temple traps without slowing down.'},
{id:'lava-run',name:'Lava Run',cat:'Adventure',icon:'🌋',mode:'runner',theme:'lava',speed:6.8,diff:3,desc:'Jump fiery rocks and survive the lava trail.'},
{id:'rooftop-rush',name:'Rooftop Rush',cat:'Adventure',icon:'🏙️',mode:'runner',theme:'city',speed:7.2,diff:3,desc:'Leap rooftop obstacles in a city sprint.'},
{id:'dino-trail',name:'Dino Trail',cat:'Adventure',icon:'🦖',mode:'runner',theme:'jungle',speed:6.5,diff:2,desc:'Run a prehistoric jungle trail.'},
{id:'snow-sprint',name:'Snow Sprint',cat:'Adventure',icon:'❄️',mode:'runner',theme:'ice',speed:6.7,diff:3,desc:'Sprint through snow and icy barriers.'},
{id:'safari-dash',name:'Safari Dash',cat:'Adventure',icon:'🦒',mode:'runner',theme:'savanna',speed:7,diff:4,desc:'A fast safari obstacle run.'},
{id:'space-blaster',name:'Space Blaster',cat:'Action',icon:'🌌',mode:'target',theme:'space',speed:1,diff:2,desc:'Tap moving space targets before they vanish.'},
{id:'ninja-targets',name:'Ninja Targets',cat:'Action',icon:'🥷',mode:'target',theme:'night',speed:1,diff:3,desc:'React quickly to ninja targets.'},
{id:'alien-strike',name:'Alien Strike',cat:'Action',icon:'👾',mode:'target',theme:'space',speed:1,diff:4,desc:'Hit alien targets under time pressure.'},
{id:'robot-arena',name:'Robot Arena',cat:'Action',icon:'🤖',mode:'target',theme:'metal',speed:1,diff:3,desc:'Fast robot target challenge.'},
{id:'pirate-cannon',name:'Pirate Cannon',cat:'Action',icon:'🏴‍☠️',mode:'target',theme:'ocean',speed:1,diff:2,desc:'Tap pirate targets and build a combo.'},
{id:'galaxy-dodge',name:'Galaxy Dodge',cat:'Action',icon:'☄️',mode:'collect',theme:'space',speed:7,diff:4,desc:'Collect energy while dodging meteors.'},
{id:'meteor-rush',name:'Meteor Rush',cat:'Action',icon:'💫',mode:'collect',theme:'space',speed:7.5,diff:4,desc:'Survive a dense meteor field.'},
{id:'laser-lanes',name:'Laser Lanes',cat:'Action',icon:'⚡',mode:'lane',theme:'space',speed:8,diff:5,desc:'Extreme lane switching through laser traffic.'},
{id:'shadow-run',name:'Shadow Run',cat:'Action',icon:'🌑',mode:'runner',theme:'night',speed:8,diff:5,desc:'A dark high-speed runner challenge.'},
{id:'reactor-dash',name:'Reactor Dash',cat:'Action',icon:'🔋',mode:'collect',theme:'metal',speed:7.3,diff:5,desc:'Collect reactor cells and avoid hazards.'},
{id:'star-catch',name:'Star Catch',cat:'Arcade',icon:'⭐',mode:'collect',theme:'sky',speed:5.5,diff:1,desc:'Catch stars and avoid dark hazards.'},
{id:'jungle-gems',name:'Jungle Gems',cat:'Arcade',icon:'💎',mode:'collect',theme:'forest',speed:5.8,diff:2,desc:'Collect jungle gems before they disappear.'},
{id:'ocean-pearls',name:'Ocean Pearls',cat:'Arcade',icon:'🦪',mode:'collect',theme:'ocean',speed:5.8,diff:2,desc:'Catch pearls and avoid sea hazards.'},
{id:'firefly-forest',name:'Firefly Forest',cat:'Arcade',icon:'✨',mode:'collect',theme:'forest',speed:6.2,diff:3,desc:'Collect glowing fireflies in the forest.'},
{id:'moon-crystals',name:'Moon Crystals',cat:'Arcade',icon:'🌙',mode:'collect',theme:'space',speed:6.6,diff:3,desc:'Gather moon crystals under falling debris.'},
{id:'treasure-cave',name:'Treasure Cave',cat:'Arcade',icon:'🪙',mode:'collect',theme:'cave',speed:6.8,diff:4,desc:'Grab treasure while avoiding cave rocks.'},
{id:'neon-snake',name:'Neon Snake',cat:'Puzzle',icon:'🐍',mode:'snake',theme:'night',speed:1,diff:2,desc:'Turn, collect energy and avoid your trail.'},
{id:'jungle-snake',name:'Jungle Snake',cat:'Puzzle',icon:'🐍',mode:'snake',theme:'forest',speed:1,diff:3,desc:'A jungle version of the classic snake challenge.'},
{id:'ocean-snake',name:'Ocean Snake',cat:'Puzzle',icon:'🐉',mode:'snake',theme:'ocean',speed:1,diff:3,desc:'Guide the sea snake to glowing food.'},
{id:'logic-dodge',name:'Logic Dodge',cat:'Puzzle',icon:'🧠',mode:'lane',theme:'clean',speed:5.5,diff:2,desc:'Read the lane pattern and choose safely.'},
{id:'pattern-rush',name:'Pattern Rush',cat:'Puzzle',icon:'🔷',mode:'target',theme:'clean',speed:1,diff:3,desc:'Tap matching targets quickly.'},
{id:'color-reaction',name:'Color Reaction',cat:'Puzzle',icon:'🎨',mode:'target',theme:'rainbow',speed:1,diff:2,desc:'Train reaction speed with bright targets.'},
{id:'balance-ball',name:'Balance Ball',cat:'Puzzle',icon:'⚪',mode:'pong',theme:'clean',speed:1,diff:3,desc:'Keep the ball alive with your paddle.'},
{id:'space-pong',name:'Space Pong',cat:'Puzzle',icon:'🪐',mode:'pong',theme:'space',speed:1,diff:4,desc:'A faster space paddle challenge.'},
{id:'balloon-pop',name:'Balloon Pop',cat:'Kids',icon:'🎈',mode:'target',theme:'rainbow',speed:1,diff:1,desc:'Pop colorful balloons.'},
{id:'fruit-splash',name:'Fruit Splash',cat:'Kids',icon:'🍉',mode:'target',theme:'garden',speed:1,diff:1,desc:'Tap fruits and build a happy score.'},
{id:'candy-catch',name:'Candy Catch',cat:'Kids',icon:'🍬',mode:'collect',theme:'candy',speed:4.7,diff:1,desc:'Catch candy and avoid gray blocks.'},
{id:'pixel-snake',name:'Pixel Snake',cat:'Kids',icon:'🟩',mode:'snake',theme:'rainbow',speed:1,diff:1,desc:'Easy colorful snake for younger players.'},
{id:'goal-keeper',name:'Goal Keeper',cat:'Sports',icon:'🥅',mode:'target',theme:'stadium',speed:1,diff:3,desc:'React to shots and protect the goal.'},
{id:'bounce-master',name:'Bounce Master',cat:'Sports',icon:'🏓',mode:'pong',theme:'stadium',speed:1,diff:3,desc:'Keep the ball bouncing as long as possible.'}
];
const $=s=>document.querySelector(s),canvas=$('#gameCanvas'),ctx=canvas.getContext('2d'),grid=$('#gameGrid'),filters=$('#filters');
const title=$('#gameTitle'),sub=$('#gameSub'),desc=$('#gameDescription'),scoreEl=$('#score'),overlay=$('#gameOverlay'),overlayTitle=$('#overlayTitle'),overlayText=$('#overlayText');
let game=GAMES[0],running=false,last=0,score=0,lives=3,t=0,spawn=0,objects=[],player={},keys={left:false,right:false,action:false},snake=null,pong=null,target=null;
const THEMES={city:['#081827','#18486b','#78d5ff'],desert:['#321b0f','#a75c24','#ffd08a'],forest:['#08261b','#17633e','#72e3a9'],night:['#050915','#172447','#8e9bff'],ice:['#0b2940','#4d9ec4','#d9f7ff'],sunset:['#37152c','#b54b55','#ffbe73'],canyon:['#2a160f','#85492f','#e5a16d'],sky:['#0c3a65','#4ea8e8','#dff4ff'],space:['#030713','#111d48','#a58bff'],ocean:['#032439','#087a9a','#8be8ff'],cloud:['#1b4666','#78bce6','#eefaff'],temple:['#251b11','#705a2d','#e6c77c'],lava:['#240706','#8d1f0e','#ff7a28'],jungle:['#052719','#1d7042','#91df78'],savanna:['#3d270d','#ae7a2b','#f5d47a'],metal:['#111820','#445464','#b9d0df'],cave:['#151016','#4b3c4d','#c69665'],clean:['#102133','#eef3f8','#4bb7ff'],rainbow:['#352058','#ff6b9b','#75e1ff'],garden:['#16421f','#66b84b','#ffda6f'],candy:['#46234c','#ff7fa6','#8be7ff'],stadium:['#082716','#178348','#e8f5ff']};
function bg(theme){const c=THEMES[theme]||THEMES.city,g=ctx.createLinearGradient(0,0,0,canvas.height);g.addColorStop(0,c[0]);g.addColorStop(.6,c[1]);g.addColorStop(1,c[2]);ctx.fillStyle=g;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.globalAlpha=.12;for(let i=0;i<18;i++){ctx.fillStyle='#fff';ctx.fillRect((i*137+t*15)%canvas.width,(i*73)%canvas.height,2,2)}ctx.globalAlpha=1}
function reset(){score=0;lives=3;t=0;spawn=0;objects=[];target=null;player={x:canvas.width/2,y:canvas.height*.78,w:46,h:62,vx:0,vy:0,lane:1,onGround:true};snake={dir:0,body:[{x:8,y:7},{x:7,y:7},{x:6,y:7}],food:{x:14,y:7},tick:0};pong={x:canvas.width/2,y:canvas.height/2,vx:5,vy:-5,paddle:canvas.width/2};scoreEl.textContent='0'}
function select(g){game=g;title.textContent=g.name;sub.textContent=`${g.cat} · Touch controls`;desc.textContent=g.desc;overlayTitle.textContent=g.name;overlayText.textContent='Tap Play Now, then use ◀, ACTION and ▶ or touch the game area.';overlay.hidden=false;running=false;reset();draw()}
function start(){reset();running=true;overlay.hidden=true;last=performance.now();requestAnimationFrame(loop)}
function end(){running=false;overlay.hidden=false;overlayTitle.textContent='Game Over';overlayText.textContent=`${game.name} · Score ${Math.floor(score)} · Tap Play Now to try again.`}
function hit(a,b){return a.x-a.w/2<b.x+b.w/2&&a.x+a.w/2>b.x-b.w/2&&a.y-a.h/2<b.y+b.h/2&&a.y+a.h/2>b.y-b.h/2}
function spawnObject(kind='bad'){const lane=Math.floor(Math.random()*3),w=40+Math.random()*22;objects.push({kind,lane,x:canvas.width*(.32+lane*.18),y:-50,w,h:w*.8,vy:game.speed+Math.random()*2,phase:Math.random()*6.2})}
function road(){ctx.fillStyle='rgba(5,12,18,.72)';ctx.beginPath();ctx.moveTo(canvas.width*.42,canvas.height*.18);ctx.lineTo(canvas.width*.12,canvas.height);ctx.lineTo(canvas.width*.88,canvas.height);ctx.lineTo(canvas.width*.58,canvas.height*.18);ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(255,255,255,.5)';ctx.lineWidth=4;for(let i=1;i<3;i++){ctx.beginPath();ctx.moveTo(canvas.width*(.42+i*.053),canvas.height*.18);ctx.lineTo(canvas.width*(.12+i*.253),canvas.height);ctx.stroke()}for(let y=(t*120)%90;y<canvas.height;y+=90){ctx.globalAlpha=.65;ctx.fillStyle='#fff';ctx.fillRect(canvas.width/2-4,y,8,28)}ctx.globalAlpha=1}
function drawPlayer(icon='◆'){ctx.save();ctx.translate(player.x,player.y);ctx.shadowColor='rgba(0,0,0,.35)';ctx.shadowBlur=15;ctx.fillStyle='#fff';ctx.beginPath();ctx.roundRect(-player.w/2,-player.h/2,player.w,player.h,12);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#0c3454';ctx.font='28px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(icon,0,0);ctx.restore()}
function lane(dt){road();const lanes=[canvas.width*.32,canvas.width*.50,canvas.width*.68];if(keys.left){player.lane=Math.max(0,player.lane-1);keys.left=false}if(keys.right){player.lane=Math.min(2,player.lane+1);keys.right=false}player.x+=(lanes[player.lane]-player.x)*Math.min(1,dt*10);spawn-=dt;if(spawn<=0){spawnObject('bad');spawn=Math.max(.35,1.0-game.diff*.1)}for(const o of objects){o.y+=o.vy*dt*60;ctx.fillStyle='rgba(255,80,90,.95)';ctx.beginPath();ctx.roundRect(o.x-o.w/2,o.y-o.h/2,o.w,o.h,10);ctx.fill();if(hit(player,o)&&!o.hit){o.hit=true;lives--;o.y=canvas.height+100}if(o.y>canvas.height+80&&!o.hit)score+=2}objects=objects.filter(o=>o.y<canvas.height+120);drawPlayer(game.icon);score+=dt*5;if(lives<=0)end()}
function runner(dt){const ground=canvas.height*.82;ctx.fillStyle='rgba(20,20,20,.45)';ctx.fillRect(0,ground,canvas.width,canvas.height-ground);if(keys.action&&player.onGround){player.vy=-14;player.onGround=false;keys.action=false}player.vy+=31*dt;player.y+=player.vy*dt*60;if(player.y>ground-player.h/2){player.y=ground-player.h/2;player.vy=0;player.onGround=true}player.x=canvas.width*.2;spawn-=dt;if(spawn<=0){objects.push({x:canvas.width+40,y:ground-25,w:40+Math.random()*25,h:50,kind:'bad'});spawn=.8+Math.random()*.6-game.diff*.06}for(const o of objects){o.x-=game.speed*dt*60;ctx.fillStyle='#ff765e';ctx.fillRect(o.x-o.w/2,o.y-o.h/2,o.w,o.h);if(hit(player,o)&&!o.hit){o.hit=true;lives--;o.x=-100}if(o.x<-80&&!o.hit)score+=3}objects=objects.filter(o=>o.x>-120);drawPlayer('🏃');score+=dt*4;if(lives<=0)end()}
function flight(dt){player.x=canvas.width*.24;if(keys.action){player.vy-=25*dt;keys.action=false}if(keys.left)player.vy-=18*dt;if(keys.right)player.vy+=18*dt;player.vy+=10*dt;player.vy=Math.max(-6,Math.min(6,player.vy));player.y+=player.vy*dt*60;player.y=Math.max(35,Math.min(canvas.height-35,player.y));spawn-=dt;if(spawn<=0){const gapY=90+Math.random()*(canvas.height-180),gap=155-game.diff*10;objects.push({x:canvas.width+30,gapY,gap,w:55,kind:'gate'});spawn=1.25-game.diff*.08}for(const o of objects){o.x-=game.speed*dt*60;ctx.fillStyle='rgba(255,255,255,.45)';ctx.fillRect(o.x-22,0,44,o.gapY-o.gap/2);ctx.fillRect(o.x-22,o.gapY+o.gap/2,44,canvas.height);if(Math.abs(player.x-o.x)<38&&(player.y<o.gapY-o.gap/2||player.y>o.gapY+o.gap/2)&&!o.hit){o.hit=true;lives--}if(o.x<player.x&&!o.scored){o.scored=true;score+=8}}objects=objects.filter(o=>o.x>-80);drawPlayer(game.icon);score+=dt*2;if(lives<=0)end()}
function collect(dt){if(keys.left)player.x-=300*dt;if(keys.right)player.x+=300*dt;player.x=Math.max(30,Math.min(canvas.width-30,player.x));player.y=canvas.height*.84;spawn-=dt;if(spawn<=0){const good=Math.random()>.34;objects.push({x:40+Math.random()*(canvas.width-80),y:-25,w:38,h:38,kind:good?'good':'bad',vy:game.speed+Math.random()*2});spawn=.32+.4*Math.random()}for(const o of objects){o.y+=o.vy*dt*60;ctx.font='32px system-ui';ctx.textAlign='center';ctx.fillText(o.kind==='good'?'✨':'💥',o.x,o.y);if(hit(player,o)&&!o.hit){o.hit=true;if(o.kind==='good')score+=10;else lives--;o.y=canvas.height+80}}objects=objects.filter(o=>o.y<canvas.height+100);drawPlayer('🛡️');if(lives<=0)end()}
function newTarget(){target={x:70+Math.random()*(canvas.width-140),y:70+Math.random()*(canvas.height-140),r:24+Math.random()*18,life:1.5-game.diff*.12}}
function targetMode(dt){if(!target)newTarget();target.life-=dt;ctx.strokeStyle='rgba(255,255,255,.35)';ctx.lineWidth=3;ctx.beginPath();ctx.arc(target.x,target.y,target.r+8,0,Math.PI*2);ctx.stroke();ctx.fillStyle='#fff';ctx.beginPath();ctx.arc(target.x,target.y,target.r,0,Math.PI*2);ctx.fill();ctx.fillStyle='#ef4c67';ctx.beginPath();ctx.arc(target.x,target.y,target.r*.48,0,Math.PI*2);ctx.fill();if(target.life<=0){lives--;newTarget()}if(keys.action){score+=3;newTarget();keys.action=false}if(lives<=0)end()}
function snakeMode(dt){const cell=32,cols=Math.floor(canvas.width/cell),rows=Math.floor(canvas.height/cell);snake.tick+=dt*(6+game.diff);if(keys.left){snake.dir=(snake.dir+3)%4;keys.left=false}if(keys.right){snake.dir=(snake.dir+1)%4;keys.right=false}if(keys.action){snake.dir=(snake.dir+1)%4;keys.action=false}if(snake.tick>=1){snake.tick=0;const h={...snake.body[0]},dirs=[[1,0],[0,1],[-1,0],[0,-1]],d=dirs[snake.dir];h.x=(h.x+d[0]+cols)%cols;h.y=(h.y+d[1]+rows)%rows;if(snake.body.some(p=>p.x===h.x&&p.y===h.y)){lives--;snake.body=snake.body.slice(0,3);if(lives<=0)return end()}snake.body.unshift(h);if(h.x===snake.food.x&&h.y===snake.food.y){score+=10;snake.food={x:Math.floor(Math.random()*cols),y:Math.floor(Math.random()*rows)}}else snake.body.pop()}ctx.fillStyle='rgba(0,0,0,.18)';for(let x=0;x<cols;x++)for(let y=0;y<rows;y++)if((x+y)%2===0)ctx.fillRect(x*cell,y*cell,cell,cell);ctx.fillStyle='#fff';snake.body.forEach((p,i)=>{ctx.globalAlpha=i?Math.max(.35,1-i*.04):1;ctx.fillRect(p.x*cell+3,p.y*cell+3,cell-6,cell-6)});ctx.globalAlpha=1;ctx.fillStyle='#ffde59';ctx.beginPath();ctx.arc(snake.food.x*cell+cell/2,snake.food.y*cell+cell/2,cell*.3,0,Math.PI*2);ctx.fill()}
function pongMode(dt){if(keys.left)pong.paddle-=360*dt;if(keys.right)pong.paddle+=360*dt;pong.paddle=Math.max(80,Math.min(canvas.width-80,pong.paddle));pong.x+=pong.vx*dt*60;pong.y+=pong.vy*dt*60;if(pong.x<16||pong.x>canvas.width-16)pong.vx*=-1;if(pong.y<16)pong.vy=Math.abs(pong.vy);const py=canvas.height-42;if(pong.y>py-15&&pong.y<py+15&&Math.abs(pong.x-pong.paddle)<85){pong.vy=-Math.abs(pong.vy)*1.02;score+=4}if(pong.y>canvas.height+20){lives--;pong.x=canvas.width/2;pong.y=canvas.height/2;pong.vy=-5;if(lives<=0)return end()}ctx.fillStyle='#fff';ctx.fillRect(pong.paddle-80,py,160,16);ctx.beginPath();ctx.arc(pong.x,pong.y,14,0,Math.PI*2);ctx.fill();score+=dt}
function draw(){bg(game.theme);ctx.fillStyle='rgba(255,255,255,.9)';ctx.font='bold 18px system-ui';ctx.textAlign='left';ctx.fillText(`❤ ${lives}`,18,30);if(!running){if(game.mode==='lane')road();drawPlayer(game.icon)}}
function update(dt){bg(game.theme);ctx.fillStyle='rgba(255,255,255,.9)';ctx.font='bold 18px system-ui';ctx.textAlign='left';ctx.fillText(`❤ ${lives}`,18,30);if(game.mode==='lane')lane(dt);else if(game.mode==='runner')runner(dt);else if(game.mode==='flight')flight(dt);else if(game.mode==='collect')collect(dt);else if(game.mode==='target')targetMode(dt);else if(game.mode==='snake')snakeMode(dt);else pongMode(dt);scoreEl.textContent=Math.floor(score)}
function loop(now){if(!running)return;const dt=Math.min(.033,(now-last)/1000||.016);last=now;t+=dt;update(dt);if(running)requestAnimationFrame(loop)}
function action(type,on){keys[type]=on;if(type==='left'&&on&&game.mode==='lane'){keys.left=true}else if(type==='right'&&on&&game.mode==='lane'){keys.right=true}}
for(const [id,key] of[['leftBtn','left'],['rightBtn','right'],['actionBtn','action']]){const b=$('#'+id);for(const ev of['pointerdown','touchstart'])b.addEventListener(ev,e=>{e.preventDefault();action(key,true)},{passive:false});for(const ev of['pointerup','pointercancel','touchend'])b.addEventListener(ev,e=>{e.preventDefault();action(key,false)},{passive:false})}
addEventListener('keydown',e=>{if(['ArrowLeft','a','A'].includes(e.key))keys.left=true;if(['ArrowRight','d','D'].includes(e.key))keys.right=true;if([' ','ArrowUp','w','W'].includes(e.key)){keys.action=true;e.preventDefault()}});addEventListener('keyup',e=>{if(['ArrowLeft','a','A'].includes(e.key))keys.left=false;if(['ArrowRight','d','D'].includes(e.key))keys.right=false;if([' ','ArrowUp','w','W'].includes(e.key))keys.action=false});
canvas.addEventListener('pointerdown',e=>{const r=canvas.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*canvas.width,y=(e.clientY-r.top)/r.height*canvas.height;if(game.mode==='target'&&target&&Math.hypot(x-target.x,y-target.y)<=target.r+14){score+=10;newTarget();return}if(game.mode==='collect')player.x=x;else if(game.mode==='flight'){player.y=y;player.vy=-2}else if(game.mode==='lane'){if(x<canvas.width/2)keys.left=true;else keys.right=true}else keys.action=true});canvas.addEventListener('pointerup',()=>{keys.left=keys.right=keys.action=false});
$('#startGame').onclick=start;document.addEventListener('visibilitychange',()=>{if(document.hidden&&running){running=false;overlay.hidden=false;overlayTitle.textContent='Paused';overlayText.textContent='Tap Play Now to continue from a new round.'}});
const cats=['All',...new Set(GAMES.map(g=>g.cat))];function renderFilters(){filters.innerHTML='';cats.forEach((c,i)=>{const b=document.createElement('button');b.type='button';b.textContent=c;b.className=i===0?'active':'';b.onclick=()=>{[...filters.children].forEach(x=>x.classList.remove('active'));b.classList.add('active');renderGames(c)};filters.appendChild(b)})}
function renderGames(cat='All'){grid.innerHTML='';GAMES.filter(g=>cat==='All'||g.cat===cat).forEach(g=>{const a=document.createElement('article');a.className='game';a.tabIndex=0;a.innerHTML=`<span class="icon">${g.icon}</span><b>${g.name}</b><small>${g.cat} · ${g.desc}</small><span class="free">FREE · PLAY NOW</span>`;const go=()=>{select(g);scrollTo({top:document.querySelector('.stage').offsetTop-70,behavior:'smooth'})};a.onclick=go;a.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();go()}};grid.appendChild(a)})}
renderFilters();renderGames();select(GAMES[0]);
})();