/* SEEKVERA Worldwide Premium UI — unified AI composer + localized controls */
(()=>{'use strict';
const HOST=location.hostname;const W=(HOST==='seekveraglobal.com'||HOST==='www.seekveraglobal.com'||HOST.endsWith('workers.dev'))?'':'https://seekvera-main.seekvera-global.workers.dev';const api=p=>`${W}${p}`;const $=s=>document.querySelector(s);const lang=()=>localStorage.getItem('seekvera_lang')||document.documentElement.lang||navigator.language||'auto';
const LOCALE_UI={
en:['Country / Region','Worldwide · All countries','Language','Auto · Device language','Currency'],ar:['الدولة / المنطقة','العالم · كل الدول','اللغة','تلقائي · لغة الجهاز','العملة'],fr:['Pays / région','Monde · Tous les pays','Langue','Auto · Langue de l’appareil','Devise'],zh:['国家 / 地区','全球 · 所有国家','语言','自动 · 设备语言','货币'],es:['País / región','Mundial · Todos los países','Idioma','Automático · Idioma del dispositivo','Moneda'],hi:['देश / क्षेत्र','विश्वभर · सभी देश','भाषा','स्वचालित · डिवाइस भाषा','मुद्रा'],pt:['País / região','Mundo · Todos os países','Idioma','Automático · Idioma do dispositivo','Moeda'],de:['Land / Region','Weltweit · Alle Länder','Sprache','Automatisch · Gerätesprache','Währung'],ja:['国 / 地域','世界 · すべての国','言語','自動 · 端末の言語','通貨'],ko:['국가 / 지역','전 세계 · 모든 국가','언어','자동 · 기기 언어','통화'],id:['Negara / Wilayah','Seluruh dunia · Semua negara','Bahasa','Otomatis · Bahasa perangkat','Mata uang'],tr:['Ülke / Bölge','Dünya çapında · Tüm ülkeler','Dil','Otomatik · Cihaz dili','Para birimi'],ru:['Страна / регион','Весь мир · Все страны','Язык','Авто · Язык устройства','Валюта'],ur:['ملک / علاقہ','دنیا بھر · تمام ممالک','زبان','خودکار · ڈیوائس کی زبان','کرنسی'],bn:['দেশ / অঞ্চল','বিশ্বব্যাপী · সব দেশ','ভাষা','স্বয়ংক্রিয় · ডিভাইসের ভাষা','মুদ্রা'],vi:['Quốc gia / Khu vực','Toàn cầu · Tất cả quốc gia','Ngôn ngữ','Tự động · Ngôn ngữ thiết bị','Tiền tệ'],it:['Paese / Regione','Tutto il mondo · Tutti i paesi','Lingua','Auto · Lingua del dispositivo','Valuta'],sw:['Nchi / Eneo','Duniani · Nchi zote','Lugha','Otomatiki · Lugha ya kifaa','Sarafu'],th:['ประเทศ / ภูมิภาค','ทั่วโลก · ทุกประเทศ','ภาษา','อัตโนมัติ · ภาษาของอุปกรณ์','สกุลเงิน'],fa:['کشور / منطقه','سراسر جهان · همه کشورها','زبان','خودکار · زبان دستگاه','ارز'],pl:['Kraj / region','Cały świat · Wszystkie kraje','Język','Auto · Język urządzenia','Waluta'],nl:['Land / regio','Wereldwijd · Alle landen','Taal','Automatisch · Apparaattaal','Valuta'],ms:['Negara / Wilayah','Semua negara','Bahasa','Auto · Bahasa peranti','Mata wang'],fil:['Bansa / Rehiyon','Buong mundo · Lahat ng bansa','Wika','Auto · Wika ng device','Pera'],ha:['Ƙasa / Yanki','Duniya · Duk ƙasashe','Harshe','Atomatik · Harshen na’ura','Kuɗi'],yo:['Orílẹ̀-èdè / Agbègbè','Kárí ayé · Gbogbo orílẹ̀-èdè','Èdè','Laifọwọyi · Èdè ẹrọ','Owó'],ig:['Mba / Mpaghara','Ụwa niile · Mba niile','Asụsụ','Akpaka · Asụsụ ngwaọrụ','Ego'],am:['አገር / ክልል','ዓለም አቀፍ · ሁሉም አገሮች','ቋንቋ','ራስ-ሰር · የመሣሪያ ቋንቋ','ገንዘብ']};
function langCode(){let c=$('#lang')?.value||localStorage.getItem('seekvera_lang')||navigator.language||'en';if(c==='auto')c=navigator.language||'en';return String(c).toLowerCase().split(/[-_]/)[0]}
function labels(){return LOCALE_UI[langCode()]||LOCALE_UI.en}
const plain=v=>typeof v==='string'&&!/^\[object Object\]$/i.test(v.trim())?v.trim():'';
const tx=s=>window.SEEKVERA_I18N?.t?.(s)||s;
function ensureControlStyles(){if($('#svControlFieldStyles'))return;const st=document.createElement('style');st.id='svControlFieldStyles';st.textContent='.sv-control-field{display:grid;gap:2px;min-width:132px;align-content:end}.sv-control-field small{font-size:10px;line-height:1.1;opacity:.72;padding-inline:8px;white-space:nowrap;font-weight:700;letter-spacing:.02em}.sv-control-field .sv-select{width:100%;min-width:0;text-overflow:ellipsis}@media(max-width:760px){.sv-controls{align-items:end}.sv-control-field{min-width:0;flex:1 1 116px}.sv-control-field small{font-size:9px;padding-inline:6px}}';document.head.appendChild(st)}
function wrapControl(el,kind){if(!el)return null;let w=el.closest('.sv-control-field');if(!w){w=document.createElement('label');w.className='sv-control-field';w.dataset.kind=kind;const cap=document.createElement('small');cap.className='sv-control-caption';el.parentNode.insertBefore(w,el);w.appendChild(cap);w.appendChild(el)}return w}
function localizeControls(){ensureControlStyles();const [countryLabel,worldwide,languageLabel,autoLabel,currencyLabel]=labels();const c=$('#country'),l=$('#lang'),cur=$('#currency');const cw=wrapControl(c,'country'),lw=wrapControl(l,'language'),uw=wrapControl(cur,'currency');if(cw)cw.querySelector('small').textContent='🌍 '+countryLabel;if(lw)lw.querySelector('small').textContent='🗣 '+languageLabel;if(uw)uw.querySelector('small').textContent='💱 '+currencyLabel;if(l){const a=[...l.options].find(o=>o.value==='auto');if(a)a.textContent='✨ '+autoLabel;l.setAttribute('aria-label',languageLabel);l.title=languageLabel}if(c){const selected=c.value;let dn;try{dn=new Intl.DisplayNames([langCode()],{type:'region'})}catch(_){};[...c.options].forEach(o=>{if(o.value==='WW')o.textContent='🌍 '+worldwide;else if(/^[A-Z]{2}$/.test(o.value)){try{o.textContent=dn?.of(o.value)||o.textContent}catch(_){}}});c.value=selected;c.setAttribute('aria-label',countryLabel);c.title=countryLabel}if(cur){cur.setAttribute('aria-label',currencyLabel);cur.title=currencyLabel}}
function bindLocaleControls(){localizeControls();$('#lang')?.addEventListener('change',()=>{setTimeout(localizeControls,0);setTimeout(localizeControls,120)});$('#country')?.addEventListener('change',()=>setTimeout(localizeControls,0))}
const AI_LANGUAGE_NAME={en:'English',ar:'Arabic',fr:'French',zh:'Chinese',es:'Spanish',hi:'Hindi',pt:'Portuguese',de:'German',ja:'Japanese',ko:'Korean',id:'Indonesian',tr:'Turkish',ru:'Russian',ur:'Urdu',bn:'Bengali',vi:'Vietnamese',it:'Italian',sw:'Swahili',th:'Thai',fa:'Persian',pl:'Polish',nl:'Dutch',ms:'Malay',fil:'Filipino',ha:'Hausa',yo:'Yoruba',ig:'Igbo',am:'Amharic'};
const AI_INTRO={
en:'I’m the SEEKVERA AI assistant. I can help you search, compare, translate and find travel, hotels, jobs, shopping, suppliers, deals, games, media and services inside SEEKVERA. Type or speak in your language.',
ar:'أنا مساعد SEEKVERA بالذكاء الاصطناعي. أساعدك في البحث والمقارنة والترجمة والعثور على السفر والفنادق والوظائف والتسوق والموردين والصفقات والألعاب والميديا والخدمات داخل SEEKVERA. اكتب أو احكِ بلغتك.',
fr:'Je suis l’assistant IA de SEEKVERA. Je peux vous aider à rechercher, comparer, traduire et trouver voyages, hôtels, emplois, achats, fournisseurs, offres, jeux, médias et services dans SEEKVERA. Écrivez ou parlez dans votre langue.',
es:'Soy el asistente de IA de SEEKVERA. Puedo ayudarte a buscar, comparar, traducir y encontrar viajes, hoteles, empleo, compras, proveedores, ofertas, juegos, medios y servicios dentro de SEEKVERA. Escribe o habla en tu idioma.',
pt:'Sou o assistente de IA da SEEKVERA. Posso ajudar a pesquisar, comparar, traduzir e encontrar viagens, hotéis, empregos, compras, fornecedores, ofertas, jogos, mídia e serviços dentro da SEEKVERA. Escreva ou fale no seu idioma.',
de:'Ich bin der SEEKVERA-KI-Assistent. Ich helfe beim Suchen, Vergleichen, Übersetzen und beim Finden von Reisen, Hotels, Jobs, Shopping, Lieferanten, Angeboten, Spielen, Medien und Diensten in SEEKVERA. Schreiben oder sprechen Sie in Ihrer Sprache.',
zh:'我是 SEEKVERA AI 助手。我可以帮你搜索、比较、翻译，并在 SEEKVERA 内寻找旅行、酒店、工作、购物、供应商、优惠、游戏、媒体和服务。你可以用自己的语言打字或说话。',
hi:'मैं SEEKVERA AI सहायक हूँ। मैं SEEKVERA के अंदर खोज, तुलना, अनुवाद और यात्रा, होटल, नौकरी, खरीदारी, सप्लायर, डील, गेम, मीडिया और सेवाएँ ढूँढने में मदद कर सकता हूँ। अपनी भाषा में लिखें या बोलें।',
tr:'Ben SEEKVERA AI asistanıyım. SEEKVERA içinde arama, karşılaştırma, çeviri; seyahat, otel, iş, alışveriş, tedarikçi, fırsat, oyun, medya ve hizmet bulma konusunda yardımcı olabilirim. Kendi dilinizde yazın veya konuşun.',
ru:'Я ИИ-помощник SEEKVERA. Я помогу искать, сравнивать, переводить и находить путешествия, отели, работу, покупки, поставщиков, предложения, игры, медиа и услуги внутри SEEKVERA. Пишите или говорите на своем языке.',
ja:"私はSEEKVERAのAIアシスタントです。検索、比較、翻訳、SEEKVERA内のサービス探しをお手伝いします。あなたの言語で入力または話してください。",
ko:"저는 SEEKVERA AI 도우미입니다. 검색, 비교, 번역과 SEEKVERA 안의 서비스 찾기를 도와드립니다. 원하는 언어로 입력하거나 말하세요.",
id:"Saya asisten AI SEEKVERA. Saya membantu mencari, membandingkan, menerjemahkan, dan menemukan layanan di SEEKVERA. Ketik atau bicara dalam bahasa Anda.",
ur:"میں SEEKVERA کا AI اسسٹنٹ ہوں۔ میں تلاش، موازنہ، ترجمہ اور SEEKVERA کے اندر خدمات تلاش کرنے میں مدد کر سکتا ہوں۔ اپنی زبان میں لکھیں یا بولیں۔",
bn:"আমি SEEKVERA AI সহকারী। আমি খোঁজা, তুলনা, অনুবাদ এবং SEEKVERA-এর ভেতরে সেবা খুঁজে পেতে সাহায্য করতে পারি। আপনার ভাষায় লিখুন বা বলুন।",
vi:"Tôi là trợ lý AI của SEEKVERA. Tôi có thể giúp tìm kiếm, so sánh, dịch và tìm dịch vụ trong SEEKVERA. Hãy nhập hoặc nói bằng ngôn ngữ của bạn.",
it:"Sono l’assistente AI di SEEKVERA. Posso aiutarti a cercare, confrontare, tradurre e trovare servizi in SEEKVERA. Scrivi o parla nella tua lingua.",
sw:"Mimi ni msaidizi wa AI wa SEEKVERA. Ninaweza kusaidia kutafuta, kulinganisha, kutafsiri na kupata huduma ndani ya SEEKVERA. Andika au zungumza kwa lugha yako.",
th:"ฉันคือผู้ช่วย AI ของ SEEKVERA ฉันช่วยค้นหา เปรียบเทียบ แปล และค้นหาบริการใน SEEKVERA ได้ พิมพ์หรือพูดด้วยภาษาของคุณ",
fa:"من دستیار هوش مصنوعی SEEKVERA هستم. می‌توانم در جستجو، مقایسه، ترجمه و پیدا کردن خدمات در SEEKVERA کمک کنم. به زبان خودتان بنویسید یا صحبت کنید.",
pl:"Jestem asystentem AI SEEKVERA. Mogę pomóc wyszukiwać, porównywać, tłumaczyć i znaleźć usługi w SEEKVERA. Pisz lub mów w swoim języku.",
nl:"Ik ben de AI-assistent van SEEKVERA. Ik kan helpen zoeken, vergelijken, vertalen en diensten binnen SEEKVERA vinden. Typ of spreek in uw taal.",
ms:"Saya pembantu AI SEEKVERA. Saya boleh membantu mencari, membandingkan, menterjemah dan mencari perkhidmatan dalam SEEKVERA. Taip atau bercakap dalam bahasa anda.",
fil:"Ako ang SEEKVERA AI assistant. Matutulungan kitang maghanap, maghambing, magsalin at mahanap ang mga serbisyo sa SEEKVERA. Mag-type o magsalita sa iyong wika.",
ha:"Ni ne mataimakin AI na SEEKVERA. Zan taimaka maka wajen nema, kwatantawa, fassara da gano sabis a cikin SEEKVERA. Rubuta ko yi magana da harshenka.",
yo:"Èmi ni olùrànlọ́wọ́ AI SEEKVERA. Mo lè ràn ọ́ lọ́wọ́ láti wá, fiwé, túmọ̀ àti rí iṣẹ́ nínú SEEKVERA. Kọ tàbí sọ̀rọ̀ ní èdè rẹ.",
ig:"Abụ m onye enyemaka AI SEEKVERA. Enwere m ike inyere gị aka ịchọ, tụnyere, tụgharịa asụsụ ma chọta ọrụ n’ime SEEKVERA. Dee ma ọ bụ kwuo n’asụsụ gị.",
am:"እኔ የSEEKVERA AI ረዳት ነኝ። በSEEKVERA ውስጥ ለመፈለግ፣ ለማወዳደር፣ ለመተርጎም እና አገልግሎቶችን ለማግኘት እረዳዎታለሁ። በቋንቋዎ ይጻፉ ወይም ይናገሩ።"};
function aiLanguageName(){const c=langCode();return AI_LANGUAGE_NAME[c]||c}
function assistantIntro(){return AI_INTRO[langCode()]||AI_INTRO.en}
function syncInlineAssistantIntro(){const first=document.querySelector('#aiMessages .ai-msg.bot');if(first)first.textContent=assistantIntro()}
function addMsg(box,role,text,thinking=false){const d=document.createElement('div');d.className=`sv-global-msg ${role}${thinking?' thinking':''}`;d.textContent=plain(text)||tx('SEEKVERA AI is temporarily unavailable. Please try again.');box.appendChild(d);box.scrollTop=box.scrollHeight;return d}
function country(){const e=$('#country');return e?.value==='WW'?'Worldwide':(e?.options?.[e.selectedIndex]?.textContent||'Worldwide')}
async function ask(box,input){const q=String(input.value||'').trim();if(!q)return;input.value='';addMsg(box,'user',q);const p=addMsg(box,'bot',tx('SEEKVERA AI is thinking…'),true);try{const r=await fetch(api('/api/ai'),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:q,country:country(),language:aiLanguageName(),scope:'worldwide',fast:true})});const d=await r.json().catch(()=>null),answer=plain(d?.response);if(!r.ok||!answer)throw Error(plain(d?.error)||'AI unavailable');p.textContent=answer;p.classList.remove('thinking');window.dispatchEvent(new CustomEvent('seekvera:ai-response',{detail:{text:answer,language:plain(d?.language)||lang()}}))}catch(e){p.textContent=tx('SEEKVERA AI is temporarily unavailable. Please try again.');p.classList.remove('thinking')}}
function dataURL(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
async function attach(box,input,file){if(!file)return;try{if(file.type==='text/plain'||/\.txt$/i.test(file.name)){if(file.size>256*1024)throw Error('Use TXT up to 256 KB.');input.value=('Attached text file '+file.name+':\n'+(await file.text()).slice(0,3500));input.form?.requestSubmit?.();return}if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024)throw Error('Use JPG, PNG, WebP up to 5 MB, or TXT up to 256 KB.');addMsg(box,'user','📷 '+file.name);const p=addMsg(box,'bot',tx('Checking image with Safety Gate and AI Vision…'),true);const r=await fetch(api('/api/visual-search'),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({image:await dataURL(file),country:country(),language:aiLanguageName()})});const d=await r.json().catch(()=>null);let text='';if(!r.ok||d?.allowed===false)text=plain(d?.reason)||tx('Image could not be processed.');else if(d?.reviewRequired)text=tx('Image needs review before visual search can continue.');else{text=[plain(d?.summary),plain(d?.guidance),plain(d?.suggestedQuery)&&('Suggested search: '+plain(d?.suggestedQuery))].filter(Boolean).join('\n')||tx('Visual search ready.')}p.textContent=text;p.classList.remove('thinking')}catch(e){addMsg(box,'bot',plain(e?.message)||'Attachment could not be processed.')}}
function buildSideChat(dock){const chat=document.createElement('aside');chat.className='sv-global-chat';chat.id='svGlobalChat';chat.innerHTML=`<div class="sv-global-chat-head"><b>✨ SEEKVERA AI</b><small>● Online</small><button class="sv-global-speaker" type="button" aria-label="Voice reply">🔊</button><button class="close" type="button" aria-label="Close">×</button></div><div class="sv-global-chat-body"><div class="sv-global-messages" id="svGlobalMessages"><div class="sv-global-msg bot">${assistantIntro()}</div></div><form class="sv-global-compose" id="svGlobalForm"><button class="attach" type="button" aria-label="Attach">📎</button><input id="svGlobalInput" type="text" maxlength="1800" autocomplete="off" placeholder="Message SEEKVERA AI…"><button class="camera" type="button" aria-label="Camera">📷</button><button class="mic" type="button" aria-label="Voice">🎤</button><button class="send" type="submit" aria-label="Send">➤</button><input class="file" type="file" accept="image/jpeg,image/png,image/webp,text/plain,.txt" hidden><input class="camfile" type="file" accept="image/jpeg,image/png,image/webp" capture="environment" hidden></form></div>`;document.body.appendChild(chat);const f=$('#svGlobalForm'),i=$('#svGlobalInput'),m=$('#svGlobalMessages'),file=f.querySelector('.file'),cam=f.querySelector('.camfile');f.addEventListener('submit',e=>{e.preventDefault();ask(m,i)});f.querySelector('.attach').addEventListener('click',()=>file.click());f.querySelector('.camera').addEventListener('click',()=>cam.click());file.addEventListener('change',()=>{const x=file.files?.[0];if(x)attach(m,i,x);file.value=''});cam.addEventListener('change',()=>{const x=cam.files?.[0];if(x)attach(m,i,x);cam.value=''});chat.querySelector('.close').addEventListener('click',()=>{chat.classList.remove('open');document.body.classList.remove('sv-chat-open')});dock.querySelector('.sv-ai-open').addEventListener('click',()=>{const open=!chat.classList.contains('open');chat.classList.toggle('open',open);$('#svGlobalSafety')?.classList.remove('open');document.body.classList.toggle('sv-chat-open',open);if(open)setTimeout(()=>i.focus(),80)});return chat}
function compactRequestOnHome(){if(!document.body.classList.contains('sv-home-global'))return;const section=$('#request'),form=$('#requestForm');if(!section||!form||section.dataset.compact==='1')return;section.dataset.compact='1';section.classList.add('sv-request-compact');form.hidden=true;const head=section.querySelector('.sv-section-head');if(!head)return;const btn=document.createElement('button');btn.type='button';btn.className='sv-pill-btn sv-request-toggle';btn.textContent=tx('Open Request Form');btn.addEventListener('click',()=>{const open=form.hidden;form.hidden=!open;section.classList.toggle('open',open);btn.textContent=tx(open?'Close Request Form':'Open Request Form')});head.appendChild(btn)}
function init(){document.documentElement.classList.add('sv-global-ui');document.body.classList.add('sv-global-ready');bindLocaleControls();const home=location.pathname==='/'||/\/index\.html$/.test(location.pathname);if(home)document.body.classList.add('sv-home-global');const inline=$('#aiChat');if(inline){inline.classList.add('sv-inline-ai-visible');syncInlineAssistantIntro();$('#lang')?.addEventListener('change',()=>setTimeout(syncInlineAssistantIntro,0));}const dock=document.createElement('nav');dock.className='sv-global-dock';dock.setAttribute('aria-label','SEEKVERA quick tools');dock.innerHTML=`<a href="index.html" aria-label="Home">⌂<span class="sv-global-tip">Home</span></a><a href="hub.html" aria-label="All categories">▦<span class="sv-global-tip">Categories</span></a><button class="sv-ai-open" type="button" aria-label="AI chat">✨<span class="sv-global-tip">AI Chat</span></button><a href="post-ad.html" aria-label="Post ad">＋<span class="sv-global-tip">Post Ad</span></a><button class="sv-safety-open" type="button" aria-label="Safety">🛡️<span class="sv-global-tip">Safety</span></button>`;document.body.appendChild(dock);let chat=null;if(home){dock.querySelector('.sv-ai-open').addEventListener('click',()=>{inline?.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>$('#aiChatInput')?.focus(),350)})}else chat=buildSideChat(dock);const safety=document.createElement('aside');safety.className='sv-global-safety';safety.id='svGlobalSafety';safety.innerHTML=`<span class="ok">🛡️ Central Safety Gate active</span><h3>SEEKVERA Safety</h3><p>Listings, requests and uploaded images use centralized text and AI Vision checks before approval or publication.</p><p>Unsafe content is blocked and uncertain content is held for review.</p>`;document.body.appendChild(safety);dock.querySelector('.sv-safety-open').addEventListener('click',()=>{safety.classList.toggle('open');chat?.classList.remove('open');document.body.classList.remove('sv-chat-open')});compactRequestOnHome();document.querySelectorAll('a[href]').forEach(a=>{const h=a.getAttribute('href')||'';if(/^javascript:/i.test(h))a.removeAttribute('href')})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,20),{once:true});else setTimeout(init,20);
})();