/* SEEKVERA Worldwide Premium UI — 2026-09-22 final */
(()=>{'use strict';
const W=location.hostname.endsWith('workers.dev')?'':'https://seekvera-main.seekvera-global.workers.dev';
const api=p=>`${W}${p}`;const $=s=>document.querySelector(s);const lang=()=>localStorage.getItem('seekvera_lang')||document.documentElement.lang||navigator.language||'en';
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function addMsg(box,role,text,thinking=false){const d=document.createElement('div');d.className=`sv-global-msg ${role}${thinking?' thinking':''}`;d.textContent=String(text||'');box.appendChild(d);box.scrollTop=box.scrollHeight;return d}
async function ask(box,input){const q=String(input.value||'').trim();if(!q)return;input.value='';addMsg(box,'user',q);const p=addMsg(box,'bot','SEEKVERA AI is thinking…',true);try{const r=await fetch(api('/api/ai'),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:q,country:'Worldwide',language:lang(),scope:'worldwide',fast:true})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.response)throw Error(d.error||'AI unavailable');p.textContent=d.response;p.classList.remove('thinking')}catch(e){p.textContent='SEEKVERA AI is temporarily unavailable. Please try again.';p.classList.remove('thinking')}}
function init(){document.documentElement.classList.add('sv-global-ui');document.body.classList.add('sv-global-ready');if(location.pathname==='/'||/\/index\.html$/.test(location.pathname))document.body.classList.add('sv-home-global');
 const dock=document.createElement('nav');dock.className='sv-global-dock';dock.setAttribute('aria-label','SEEKVERA quick tools');dock.innerHTML=`<a href="index.html" aria-label="Home">⌂<span class="sv-global-tip">Home</span></a><a href="hub.html" aria-label="All categories">▦<span class="sv-global-tip">All categories</span></a><button class="sv-ai-open" type="button" aria-label="AI chat">✨<span class="sv-global-tip">AI Chat</span></button><button class="sv-voice-open" type="button" aria-label="Voice AI">🎤<span class="sv-global-tip">Voice</span></button><button class="sv-visual-open" type="button" aria-label="Visual search">📷<span class="sv-global-tip">Visual search</span></button><button class="sv-safety-open" type="button" aria-label="Safety status">🛡️<span class="sv-global-tip">Safety</span></button>`;document.body.appendChild(dock);
 const chat=document.createElement('aside');chat.className='sv-global-chat';chat.id='svGlobalChat';chat.innerHTML=`<div class="sv-global-chat-head"><b>✨ SEEKVERA AI</b><small>● Fast worldwide</small><button type="button" aria-label="Close">×</button></div><div class="sv-global-chat-body" id="svGlobalChatBody"></div>`;document.body.appendChild(chat);
 const body=$('#svGlobalChatBody'),existing=$('#aiChat');if(existing){body.appendChild(existing)}else{body.innerHTML=`<div class="sv-global-messages" id="svGlobalMessages"><div class="sv-global-msg bot">Hi. Ask me anything, anywhere in the world.</div></div><form class="sv-global-compose" id="svGlobalForm"><input id="svGlobalInput" maxlength="1800" autocomplete="off" placeholder="Ask SEEKVERA AI…"><button class="mic" type="button" aria-label="Speak">🎤</button><button class="send" type="submit">Send</button></form>`;const f=$('#svGlobalForm'),i=$('#svGlobalInput'),m=$('#svGlobalMessages');f.addEventListener('submit',e=>{e.preventDefault();ask(m,i)});f.querySelector('.mic').addEventListener('click',()=>dock.querySelector('.sv-voice-open').click())}
 const safety=document.createElement('aside');safety.className='sv-global-safety';safety.id='svGlobalSafety';safety.innerHTML=`<span class="ok">🛡️ Central Safety Gate active</span><h3>SEEKVERA Safety</h3><p>Listings, requests and uploaded images use centralized text / AI Vision checks before approval or publication.</p><p>Unsafe content is blocked. Uncertain or suspicious content is held for review. Paid actions, money transfers and binding approvals stay owner-controlled where applicable.</p>`;document.body.appendChild(safety);
 const toggleChat=()=>{const open=!chat.classList.contains('open');chat.classList.toggle('open',open);safety.classList.remove('open');document.body.classList.toggle('sv-chat-open',open);if(open)setTimeout(()=>($('#aiChatInput')||$('#svGlobalInput'))?.focus(),80)};dock.querySelector('.sv-ai-open').addEventListener('click',toggleChat);chat.querySelector('.sv-global-chat-head button').addEventListener('click',()=>{chat.classList.remove('open');document.body.classList.remove('sv-chat-open')});
 dock.querySelector('.sv-safety-open').addEventListener('click',()=>{safety.classList.toggle('open');chat.classList.remove('open');document.body.classList.remove('sv-chat-open')});
 dock.querySelector('.sv-voice-open').addEventListener('click',()=>{const b=$('#svVoiceFab')||$('#heroVoice')||$('#aiChatMic');if(b&&b!==dock.querySelector('.sv-voice-open'))b.click();else window.dispatchEvent(new CustomEvent('seekvera:voice'))});
 dock.querySelector('.sv-visual-open').addEventListener('click',()=>{const b=$('#heroCamera')||$('#visualOpen');if(b)b.click();else location.href='index.html?visual=1'});
 if(document.body.classList.contains('sv-home-global')&&innerWidth>=1280){chat.classList.add('open');document.body.classList.add('sv-chat-open')}
 if(new URLSearchParams(location.search).get('visual')==='1')setTimeout(()=>($('#heroCamera')||$('#visualOpen'))?.click(),400);
 document.querySelectorAll('a[href]').forEach(a=>{const h=a.getAttribute('href')||'';if(/^javascript:/i.test(h))a.removeAttribute('href')});
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,0));else setTimeout(init,0);
})();
