/* SEEKVERA R32 universal locale runtime: one country -> one language/currency -> every visible UI string. */
(()=>{'use strict';
if(window.__SEEKVERA_I18N_R32)return;window.__SEEKVERA_I18N_R32=true;
const VERSION='20260925-r35-global-final';
const SRC=new WeakMap(),ATTRSRC=new WeakMap(),MEM=new Map(),PACKS=new Map(),PACKING=new Map(),RENDERED_TEXT=new WeakMap(),RENDERED_ATTR=new WeakMap();
const RTL=new Set(['ar','fa','ur','he','ps','dv']);
const ATTRS=['placeholder','aria-label','title'];
const SKIP='script,style,noscript,code,pre,svg,select,option,textarea,[data-no-translate],[data-user-content],.ai-msg.user';
const INITIAL_AI='I’m the SEEKVERA AI assistant. Tell me what you need and I’ll help you find the right section, compare options or search worldwide.';
const QUICK={ar:{
'GLOBAL AI MARKETPLACE':'سوق عالمي بالذكاء الاصطناعي','Country / Region':'الدولة / المنطقة','Language':'اللغة','Currency':'العملة','Install':'تثبيت','Post Ad':'أضف إعلاناً',
'Worldwide':'العالم كله','AI assisted':'بمساعدة الذكاء الاصطناعي','Voice + Chat':'صوت + دردشة','Find it faster. Compare it better.':'اعثر عليه أسرع. قارنه بشكل أفضل.','Hotels, homes, cars, jobs, products, suppliers, media and services — from one global marketplace.':'فنادق ومنازل وسيارات ووظائف ومنتجات وموردون وإعلام وخدمات — من سوق عالمي واحد.','Near Me':'بالقرب مني','My Country':'بلدي','Chat · Voice · Camera · Attach':'دردشة · صوت · كاميرا · إرفاق','Online':'متصل','Message SEEKVERA AI…':'راسل ذكاء SEEKVERA…','Choose a country once and SEEKVERA switches the app language, currency, AI context and country-aware sections automatically. You can still change language manually if you want.':'اختر دولة مرة واحدة، وستغيّر SEEKVERA تلقائياً لغة التطبيق والعملة وسياق الذكاء الاصطناعي والأقسام المرتبطة بالدولة. ويمكنك تغيير اللغة يدوياً متى أردت.',
'Popular categories':'الأقسام الشائعة','Clear visual routes, like a marketplace — no empty cards.':'مسارات واضحة مثل السوق — بدون بطاقات فارغة.','ALL CATEGORIES →':'كل الأقسام ←','Live marketplace':'السوق المباشر','Approved real listings only.':'إعلانات حقيقية معتمدة فقط.','OPEN MARKETPLACE →':'افتح السوق ←','Loading approved listings…':'جارٍ تحميل الإعلانات المعتمدة…','No approved live marketplace listings are available right now. SEEKVERA does not generate fake listings.':'لا توجد حالياً إعلانات سوق مباشرة معتمدة. لا تنشئ SEEKVERA إعلانات وهمية.','No approved live marketplace listings are available right now':'لا توجد حالياً إعلانات سوق مباشرة معتمدة.','SEEKVERA does not generate fake listings':'لا تنشئ SEEKVERA إعلانات وهمية.',
'Request anything':'اطلب أي شيء','Tell SEEKVERA what you need anywhere in the world.':'أخبر SEEKVERA بما تحتاج إليه في أي مكان في العالم.','Country / anywhere':'الدولة / أي مكان','City / area':'المدينة / المنطقة','Describe what you need':'اشرح ما تحتاج إليه','Send request':'إرسال الطلب','Find, compare, choose — worldwide.':'ابحث وقارن واختر — حول العالم.','Find, compare, choose — worldwide':'ابحث وقارن واختر — حول العالم','About':'حول','Privacy':'الخصوصية','Terms':'الشروط','Contact':'تواصل','Disclosure':'الإفصاح',
[INITIAL_AI]:'أنا مساعد SEEKVERA بالذكاء الاصطناعي. أخبرني بما تحتاج إليه وسأساعدك في الوصول إلى القسم المناسب ومقارنة الخيارات أو البحث حول العالم.'
}};
function api(p){const h=location.hostname;return(h==='seekveraglobal.com'||h==='www.seekveraglobal.com'||h.endsWith('workers.dev'))?p:'https://seekvera-main.seekvera-global.workers.dev'+p}
function norm(v){v=String(v||'').trim().toLowerCase().replace('_','-');if(!v||v==='auto')v=String(navigator.language||'en').toLowerCase();return v.split('-')[0]||'en'}
function lang(){return norm(document.querySelector('#lang')?.value||window.SEEKVERA_LOCALE_STATE?.language||document.documentElement.lang||'en')}
function langName(l){try{return new Intl.DisplayNames(['en'],{type:'language'}).of(l)||l}catch{return l}}
function worth(s){s=String(s||'').trim();if(!s||s.length<2||s.length>1200)return false;if(/^SEEKVERA$/i.test(s))return false;if(/^(https?:\/\/|www\.)/i.test(s)||/\b\S+@\S+\.\S+\b/.test(s))return false;if(/^[A-Z0-9]{2,5}$/.test(s))return false;if(/^[\d\s.,:+\-/%$€£₦¥₹]+$/.test(s))return false;return /[A-Za-z\u00C0-\u024F\u0400-\u052F\u0600-\u06FF\u0900-\u097F\u3040-\u30FF\u3400-\u9FFF]/.test(s)}
function skipped(n){const p=n?.parentElement;return !p||!!p.closest(SKIP)}
function capture(root=document){
 const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;while((n=w.nextNode())){if(skipped(n))continue;const s=n.nodeValue?.trim();if(worth(s)&&!SRC.has(n))SRC.set(n,s)}
 const els=root===document?[...document.querySelectorAll('[placeholder],[aria-label],[title]')]:[...(root.querySelectorAll?.('[placeholder],[aria-label],[title]')||[])];
 for(const el of els){if(el.closest?.(SKIP))continue;let m=ATTRSRC.get(el);if(!m){m={};ATTRSRC.set(el,m)}for(const a of ATTRS){const s=el.getAttribute?.(a)?.trim();if(worth(s)&&!(a in m))m[a]=s}}
}
function k(l,s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return'sv_r32_'+l+'_'+(h>>>0).toString(36)}
function get(l,s){const q=QUICK[l]?.[s];if(q)return q;const m=MEM.get(l+'\u0000'+s);if(m)return m;try{return localStorage.getItem(k(l,s))||''}catch{return''}}
function put(l,s,v){v=String(v||'').trim();if(!v||v===s)return;MEM.set(l+'\u0000'+s,v);try{localStorage.setItem(k(l,s),v)}catch{}}
/* r32-static-v5: atomic local packs + render/source separation */
async function loadPack(l){
 l=norm(l);if(l==='en')return true;if(PACKS.has(l))return true;if(PACKING.has(l))return PACKING.get(l);
 const task=(async()=>{try{const r=await fetch('/i18n-r32/'+encodeURIComponent(l)+'.json?v=20260925-r32-static-v5',{cache:'force-cache'});if(!r.ok)throw Error('pack '+r.status);const d=await r.json();const t=d?.translations;if(!t||typeof t!=='object')throw Error('invalid pack');for(const [src,v] of Object.entries(t)){const val=String(v||'').trim();if(val&&val!==src)MEM.set(l+'\u0000'+src,val)}PACKS.set(l,d);document.documentElement.dataset.seekveraPackReady=l;return true}catch(e){console.warn('SEEKVERA local language pack unavailable',l,e);return false}finally{PACKING.delete(l)}})();
 PACKING.set(l,task);return task
}
function markAttr(el,a,v){let m=RENDERED_ATTR.get(el);if(!m){m={};RENDERED_ATTR.set(el,m)}m[a]=String(v||'').trim()}

function valid(v,src){v=String(v||'').trim();return !!v&&v!==src&&!/^undefined|null$/i.test(v)&&!/^\[object Object\]$/i.test(v)}
async function cloudTranslate(l,batch){for(let attempt=0;attempt<3;attempt++)try{const ctl=new AbortController(),to=setTimeout(()=>ctl.abort(),12000);const r=await fetch(api('/api/ui-translate'),{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({language:langName(l),strings:batch}),signal:ctl.signal,cache:'no-store'});clearTimeout(to);const d=await r.json().catch(()=>null);if(r.ok&&Array.isArray(d?.translations)&&d.translations.length===batch.length){const vals=d.translations.map((v,i)=>valid(v,batch[i])?String(v).trim():'');if(vals.some(Boolean))return vals}}catch{};return null}
async function publicTranslate(l,batch){try{const prompt=['Translate these user-interface strings from English into '+langName(l)+'.','Keep SEEKVERA, URLs, numbers and currency codes unchanged.','Return ONLY a JSON array with exactly '+batch.length+' strings in the same order.',JSON.stringify(batch)].join('\n');const ctl=new AbortController(),to=setTimeout(()=>ctl.abort(),15000);const r=await fetch('https://text.pollinations.ai/'+encodeURIComponent(prompt)+'?model=openai&private=true',{headers:{accept:'text/plain'},signal:ctl.signal,cache:'no-store'});clearTimeout(to);if(!r.ok)return null;let raw=String(await r.text()).trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'');const a=raw.indexOf('['),b=raw.lastIndexOf(']');if(a>=0&&b>a)raw=raw.slice(a,b+1);const vals=JSON.parse(raw);if(!Array.isArray(vals)||vals.length!==batch.length)return null;return vals.map((v,i)=>valid(v,batch[i])?String(v).trim():'')}catch{return null}}
async function translate(l,arr){await loadPack(l);const unique=[...new Set(arr.filter(s=>worth(s)&&!get(l,s)))];if(!unique.length)return;const groups=[];for(let i=0;i<unique.length;i+=14)groups.push(unique.slice(i,i+14));for(let i=0;i<groups.length;i+=3){await Promise.all(groups.slice(i,i+3).map(async batch=>{let vals=await cloudTranslate(l,batch);if(!vals||vals.some((v,j)=>!v&&!get(l,batch[j])))vals=await publicTranslate(l,batch);if(vals)batch.forEach((s,j)=>{if(valid(vals[j],s))put(l,s,vals[j])})}))}}
function setText(n,src,l){const v=l==='en'?src:get(l,src);if(!v)return false;const raw=n.nodeValue||'',t=raw.trim(),next=t?raw.replace(t,v):v;RENDERED_TEXT.set(n,String(next).trim());if(next!==raw)n.nodeValue=next;return true}
function setAttr(el,a,src,l){const v=l==='en'?src:get(l,src);if(!v)return false;markAttr(el,a,v);if(el.getAttribute(a)!==v)el.setAttribute(a,v);return true}
let seq=0,timer=0,applying=false;
async function apply(){const my=++seq,l=lang();if(l!=='en'){await loadPack(l);if(my!==seq)return}applying=true;document.documentElement.lang=l;document.documentElement.dir=RTL.has(l)?'rtl':'ltr';capture(document);const texts=[],attrs=[],need=[];
 for(const [n,src] of entriesText()){if(!n.isConnected)continue;texts.push([n,src]);if(l!=='en'&&!get(l,src))need.push(src);setText(n,src,l)}
 for(const [el,m] of entriesAttr()){if(!el.isConnected)continue;for(const [a,src] of Object.entries(m)){attrs.push([el,a,src]);if(l!=='en'&&!get(l,src))need.push(src);setAttr(el,a,src,l)}}
 const ai=document.querySelector('#aiMessages .ai-msg.bot:first-child');if(ai&&ai.textContent?.trim()===INITIAL_AI){if(l==='en')ai.textContent=INITIAL_AI;else{const q=get(l,INITIAL_AI);ai.textContent=q||'…';if(!q)need.push(INITIAL_AI)}}
 applying=false;if(l!=='en'&&need.length)await translate(l,need);if(my!==seq)return;applying=true;for(const [n,src] of texts)if(n.isConnected)setText(n,src,l);for(const [el,a,src] of attrs)if(el.isConnected)setAttr(el,a,src,l);const ai2=document.querySelector('#aiMessages .ai-msg.bot:first-child');if(ai2&&(!ai2.closest('.user'))){const q=l==='en'?INITIAL_AI:get(l,INITIAL_AI);if(q&&(/SEEKVERA AI assistant/.test(ai2.textContent||'')||(ai2.textContent||'').trim()==='…'))ai2.textContent=q}document.documentElement.dataset.seekveraI18nReady=l;document.documentElement.dataset.seekveraI18nVersion=VERSION;applying=false}
function entriesText(){const out=[];const w=document.createTreeWalker(document,NodeFilter.SHOW_TEXT);let n;while((n=w.nextNode())){const s=SRC.get(n);if(s)out.push([n,s])}return out}
function entriesAttr(){const out=[];for(const el of document.querySelectorAll('[placeholder],[aria-label],[title]')){const m=ATTRSRC.get(el);if(m)out.push([el,m])}return out}
function schedule(ms=80){clearTimeout(timer);timer=setTimeout(()=>apply().catch(()=>{}),ms)}
function boot(){capture(document);document.addEventListener('change',e=>{if(e.target?.id==='country'||e.target?.id==='lang'||e.target?.id==='currency')schedule(20)},true);new MutationObserver(ms=>{if(applying)return;let dirty=false;for(const m of ms){if(m.type==='characterData'){const n=m.target;if(!skipped(n)){const now=String(n.nodeValue||'').trim(),rendered=RENDERED_TEXT.get(n);if(rendered!==undefined&&now===rendered)continue;RENDERED_TEXT.delete(n);if(worth(now)){SRC.set(n,now);dirty=true}}}else if(m.type==='attributes'){const el=m.target,a=m.attributeName;if(el&&a&&ATTRS.includes(a)&&!el.closest?.(SKIP)){const now=String(el.getAttribute(a)||'').trim(),rendered=RENDERED_ATTR.get(el)?.[a];if(rendered!==undefined&&now===rendered)continue;const rm=RENDERED_ATTR.get(el);if(rm)delete rm[a];if(worth(now)){let mm=ATTRSRC.get(el);if(!mm){mm={};ATTRSRC.set(el,mm)}mm[a]=now;dirty=true}}}for(const n of m.addedNodes||[]){if(n.nodeType===1){capture(n);dirty=true}else if(n.nodeType===3&&!skipped(n)){const now=String(n.nodeValue||'').trim();if(worth(now)){SRC.set(n,now);dirty=true}}}}if(dirty)schedule(PACKS.has(lang())?0:30)}).observe(document.documentElement,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:ATTRS});loadPack(lang()).then(()=>schedule(0));schedule(0);setTimeout(()=>schedule(0),400);setTimeout(()=>schedule(0),1600);setTimeout(()=>schedule(0),4200)}
capture(document);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
window.SEEKVERA_I18N={lang,apply,schedule,t:s=>get(lang(),String(s))||String(s),version:VERSION};window.SEEKVERA_LOCALE_GUARD_R9={apply,schedule,version:VERSION};window.SEEKVERA_I18N_R32={version:VERSION,apply,schedule,lang,loadPack,packReady:l=>PACKS.has(norm(l)),packCount:()=>PACKS.size};
})();