/* SEEKVERA R14 deterministic country locale seal.
   Critical UI is bundled locally so country switching never depends on AI quota. */
(()=>{'use strict';
if(window.__SEEKVERA_LOCALE_R14)return;window.__SEEKVERA_LOCALE_R14=true;
const K=['brand','country','language','currency','worldwide','ai','voice','headline','hero','near','mine','chatmeta','online','hello','placeholder','note','popular','all','live','request'];
const L={
en:[`GLOBAL AI MARKETPLACE`,`Country / Region`,`Language`,`Currency`,`Worldwide`,`AI assisted`,`Voice + Chat`,`Find faster. Compare better.`,`Hotels, homes, cars, jobs, products and services worldwide.`,`Near Me`,`My Country`,`Chat · Voice · Camera · Attach`,`Online`,`I am SEEKVERA AI. Tell me what you need.`,`Message SEEKVERA AI…`,`Changing country updates language, currency and AI automatically.`,`Popular categories`,`All categories`,`Live marketplace`,`Request anything`],
ar:[`سوق عالمي بالذكاء الاصطناعي`,`الدولة / المنطقة`,`اللغة`,`العملة`,`العالم كله`,`بمساعدة الذكاء الاصطناعي`,`صوت + دردشة`,`ابحث أسرع. قارن أفضل.`,`فنادق ومنازل وسيارات ووظائف ومنتجات وخدمات حول العالم.`,`بالقرب مني`,`بلدي`,`دردشة · صوت · كاميرا · إرفاق`,`متصل`,`أنا مساعد SEEKVERA بالذكاء الاصطناعي. أخبرني ماذا تحتاج.`,`راسل SEEKVERA AI…`,`تغيير الدولة يحدّث اللغة والعملة والذكاء الاصطناعي تلقائياً.`,`الأقسام الشائعة`,`كل الأقسام`,`السوق المباشر`,`اطلب أي شيء`],
fr:[`MARCHÉ MONDIAL AVEC IA`,`Pays / région`,`Langue`,`Devise`,`Monde entier`,`Assisté par IA`,`Voix + chat`,`Trouvez plus vite. Comparez mieux.`,`Hôtels, logements, voitures, emplois, produits et services dans le monde entier.`,`Près de moi`,`Mon pays`,`Chat · Voix · Caméra · Joindre`,`En ligne`,`Je suis l’IA SEEKVERA. Dites-moi ce dont vous avez besoin.`,`Message à SEEKVERA AI…`,`Changer de pays met automatiquement à jour la langue, la devise et l’IA.`,`Catégories populaires`,`Toutes les catégories`,`Marché en direct`,`Demandez n’importe quoi`],
zh:[`全球人工智能市场`,`国家 / 地区`,`语言`,`货币`,`全球`,`AI 辅助`,`语音 + 聊天`,`更快找到，更好比较。`,`全球酒店、住房、汽车、工作、商品和服务。`,`附近`,`我的国家`,`聊天 · 语音 · 相机 · 附件`,`在线`,`我是 SEEKVERA AI。告诉我您需要什么。`,`给 SEEKVERA AI 发消息…`,`更改国家后会自动更新语言、货币和 AI。`,`热门分类`,`全部分类`,`实时市场`,`提出任何需求`],
es:[`MERCADO GLOBAL CON IA`,`País / región`,`Idioma`,`Moneda`,`Todo el mundo`,`Con ayuda de IA`,`Voz + chat`,`Encuentra más rápido. Compara mejor.`,`Hoteles, casas, coches, empleos, productos y servicios en todo el mundo.`,`Cerca de mí`,`Mi país`,`Chat · Voz · Cámara · Adjuntar`,`En línea`,`Soy la IA de SEEKVERA. Dime qué necesitas.`,`Mensaje a SEEKVERA AI…`,`Al cambiar de país se actualizan automáticamente el idioma, la moneda y la IA.`,`Categorías populares`,`Todas las categorías`,`Mercado en vivo`,`Pide cualquier cosa`],
hi:[`वैश्विक एआई बाज़ार`,`देश / क्षेत्र`,`भाषा`,`मुद्रा`,`दुनिया भर`,`एआई सहायक`,`आवाज़ + चैट`,`तेज़ी से खोजें। बेहतर तुलना करें।`,`दुनिया भर में होटल, घर, कारें, नौकरियाँ, उत्पाद और सेवाएँ।`,`मेरे पास`,`मेरा देश`,`चैट · आवाज़ · कैमरा · संलग्न करें`,`ऑनलाइन`,`मैं SEEKVERA AI हूँ। बताइए आपको क्या चाहिए।`,`SEEKVERA AI को संदेश…`,`देश बदलने पर भाषा, मुद्रा और AI अपने आप बदलते हैं।`,`लोकप्रिय श्रेणियाँ`,`सभी श्रेणियाँ`,`लाइव बाज़ार`,`कुछ भी माँगें`],
pt:[`MERCADO GLOBAL COM IA`,`País / região`,`Idioma`,`Moeda`,`Mundo inteiro`,`Assistido por IA`,`Voz + chat`,`Encontre mais rápido. Compare melhor.`,`Hotéis, casas, carros, empregos, produtos e serviços no mundo inteiro.`,`Perto de mim`,`Meu país`,`Chat · Voz · Câmara · Anexar`,`Online`,`Sou a IA da SEEKVERA. Diga o que precisa.`,`Mensagem para SEEKVERA AI…`,`Mudar de país atualiza automaticamente idioma, moeda e IA.`,`Categorias populares`,`Todas as categorias`,`Mercado ao vivo`,`Peça qualquer coisa`],
de:[`GLOBALER KI-MARKTPLATZ`,`Land / Region`,`Sprache`,`Währung`,`Weltweit`,`KI-unterstützt`,`Sprache + Chat`,`Schneller finden. Besser vergleichen.`,`Hotels, Wohnungen, Autos, Jobs, Produkte und Dienstleistungen weltweit.`,`In meiner Nähe`,`Mein Land`,`Chat · Sprache · Kamera · Anhang`,`Online`,`Ich bin SEEKVERA AI. Sag mir, was du brauchst.`,`Nachricht an SEEKVERA AI…`,`Ein Länderwechsel aktualisiert Sprache, Währung und KI automatisch.`,`Beliebte Kategorien`,`Alle Kategorien`,`Live-Marktplatz`,`Alles anfragen`],
ja:[`グローバルAIマーケットプレイス`,`国 / 地域`,`言語`,`通貨`,`世界中`,`AI支援`,`音声 + チャット`,`より速く見つけ、より良く比較。`,`世界中のホテル、住宅、車、仕事、商品、サービス。`,`現在地周辺`,`自分の国`,`チャット · 音声 · カメラ · 添付`,`オンライン`,`SEEKVERA AIです。必要なものを教えてください。`,`SEEKVERA AIにメッセージ…`,`国を変更すると言語、通貨、AIが自動更新されます。`,`人気カテゴリ`,`すべてのカテゴリ`,`ライブマーケット`,`何でもリクエスト`],
ko:[`글로벌 AI 마켓플레이스`,`국가 / 지역`,`언어`,`통화`,`전 세계`,`AI 지원`,`음성 + 채팅`,`더 빠르게 찾고 더 잘 비교하세요.`,`전 세계의 호텔, 주택, 자동차, 일자리, 상품과 서비스.`,`내 주변`,`내 국가`,`채팅 · 음성 · 카메라 · 첨부`,`온라인`,`SEEKVERA AI입니다. 필요한 것을 말씀해 주세요.`,`SEEKVERA AI에 메시지…`,`국가를 변경하면 언어, 통화와 AI가 자동으로 업데이트됩니다.`,`인기 카테고리`,`모든 카테고리`,`실시간 마켓`,`무엇이든 요청`],
id:[`PASAR GLOBAL DENGAN AI`,`Negara / Wilayah`,`Bahasa`,`Mata uang`,`Seluruh dunia`,`Dibantu AI`,`Suara + Chat`,`Temukan lebih cepat. Bandingkan lebih baik.`,`Hotel, rumah, mobil, pekerjaan, produk, dan layanan di seluruh dunia.`,`Di dekat saya`,`Negara saya`,`Chat · Suara · Kamera · Lampiran`,`Online`,`Saya SEEKVERA AI. Beri tahu apa yang Anda butuhkan.`,`Pesan SEEKVERA AI…`,`Mengubah negara otomatis memperbarui bahasa, mata uang, dan AI.`,`Kategori populer`,`Semua kategori`,`Pasar langsung`,`Minta apa saja`],
tr:[`KÜRESEL YAPAY ZEKA PAZARI`,`Ülke / Bölge`,`Dil`,`Para birimi`,`Dünya çapında`,`Yapay zeka destekli`,`Ses + Sohbet`,`Daha hızlı bul. Daha iyi karşılaştır.`,`Dünya çapında oteller, evler, arabalar, işler, ürünler ve hizmetler.`,`Yakınımda`,`Ülkem`,`Sohbet · Ses · Kamera · Ekle`,`Çevrimiçi`,`Ben SEEKVERA AI. Neye ihtiyacınız olduğunu söyleyin.`,`SEEKVERA AI’a mesaj…`,`Ülkeyi değiştirmek dili, para birimini ve yapay zekayı otomatik günceller.`,`Popüler kategoriler`,`Tüm kategoriler`,`Canlı pazar`,`Her şeyi isteyin`],
ru:[`ГЛОБАЛЬНЫЙ ИИ-МАРКЕТПЛЕЙС`,`Страна / регион`,`Язык`,`Валюта`,`Весь мир`,`С поддержкой ИИ`,`Голос + чат`,`Находите быстрее. Сравнивайте лучше.`,`Отели, жильё, автомобили, работа, товары и услуги по всему миру.`,`Рядом со мной`,`Моя страна`,`Чат · Голос · Камера · Вложение`,`Онлайн`,`Я SEEKVERA AI. Скажите, что вам нужно.`,`Сообщение SEEKVERA AI…`,`Смена страны автоматически обновляет язык, валюту и ИИ.`,`Популярные категории`,`Все категории`,`Живой маркетплейс`,`Запросить что угодно`],
ur:[`عالمی اے آئی مارکیٹ پلیس`,`ملک / علاقہ`,`زبان`,`کرنسی`,`دنیا بھر`,`اے آئی کی مدد سے`,`آواز + چیٹ`,`تیزی سے تلاش کریں۔ بہتر موازنہ کریں۔`,`دنیا بھر میں ہوٹل، گھر، گاڑیاں، نوکریاں، مصنوعات اور خدمات۔`,`میرے قریب`,`میرا ملک`,`چیٹ · آواز · کیمرا · منسلک کریں`,`آن لائن`,`میں SEEKVERA AI ہوں۔ بتائیں آپ کو کیا چاہیے۔`,`SEEKVERA AI کو پیغام…`,`ملک بدلنے سے زبان، کرنسی اور AI خودکار طور پر بدلتے ہیں۔`,`مقبول زمرے`,`تمام زمرے`,`لائیو مارکیٹ`,`کچھ بھی مانگیں`],
bn:[`বিশ্বব্যাপী এআই মার্কেটপ্লেস`,`দেশ / অঞ্চল`,`ভাষা`,`মুদ্রা`,`বিশ্বব্যাপী`,`এআই সহায়তায়`,`ভয়েস + চ্যাট`,`দ্রুত খুঁজুন। ভালোভাবে তুলনা করুন।`,`বিশ্বজুড়ে হোটেল, বাড়ি, গাড়ি, চাকরি, পণ্য ও সেবা।`,`আমার কাছে`,`আমার দেশ`,`চ্যাট · ভয়েস · ক্যামেরা · সংযুক্তি`,`অনলাইন`,`আমি SEEKVERA AI। আপনার কী দরকার বলুন।`,`SEEKVERA AI-কে বার্তা…`,`দেশ বদলালে ভাষা, মুদ্রা ও AI স্বয়ংক্রিয়ভাবে বদলে যায়।`,`জনপ্রিয় বিভাগ`,`সব বিভাগ`,`লাইভ মার্কেটপ্লেস`,`যেকোনো কিছু চাইুন`],
vi:[`THỊ TRƯỜNG AI TOÀN CẦU`,`Quốc gia / Khu vực`,`Ngôn ngữ`,`Tiền tệ`,`Toàn cầu`,`Có AI hỗ trợ`,`Giọng nói + Trò chuyện`,`Tìm nhanh hơn. So sánh tốt hơn.`,`Khách sạn, nhà ở, ô tô, việc làm, sản phẩm và dịch vụ trên toàn thế giới.`,`Gần tôi`,`Quốc gia của tôi`,`Trò chuyện · Giọng nói · Camera · Đính kèm`,`Trực tuyến`,`Tôi là SEEKVERA AI. Hãy cho tôi biết bạn cần gì.`,`Nhắn SEEKVERA AI…`,`Đổi quốc gia sẽ tự động cập nhật ngôn ngữ, tiền tệ và AI.`,`Danh mục phổ biến`,`Tất cả danh mục`,`Thị trường trực tiếp`,`Yêu cầu bất cứ điều gì`],
it:[`MERCATO GLOBALE CON IA`,`Paese / Regione`,`Lingua`,`Valuta`,`Tutto il mondo`,`Assistito dall’IA`,`Voce + Chat`,`Trova più velocemente. Confronta meglio.`,`Hotel, case, auto, lavori, prodotti e servizi in tutto il mondo.`,`Vicino a me`,`Il mio Paese`,`Chat · Voce · Fotocamera · Allega`,`Online`,`Sono SEEKVERA AI. Dimmi cosa ti serve.`,`Messaggio a SEEKVERA AI…`,`Cambiare Paese aggiorna automaticamente lingua, valuta e IA.`,`Categorie popolari`,`Tutte le categorie`,`Mercato live`,`Chiedi qualsiasi cosa`],
sw:[`SOKO LA KIMATAIFA LENYE AI`,`Nchi / Eneo`,`Lugha`,`Sarafu`,`Duniani kote`,`Kwa msaada wa AI`,`Sauti + Gumzo`,`Pata haraka. Linganisha vizuri.`,`Hoteli, nyumba, magari, kazi, bidhaa na huduma duniani kote.`,`Karibu nami`,`Nchi yangu`,`Gumzo · Sauti · Kamera · Ambatisha`,`Mtandaoni`,`Mimi ni SEEKVERA AI. Niambie unachohitaji.`,`Ujumbe kwa SEEKVERA AI…`,`Kubadilisha nchi husasisha lugha, sarafu na AI kiotomatiki.`,`Makundi maarufu`,`Makundi yote`,`Soko la moja kwa moja`,`Omba chochote`],
th:[`ตลาด AI ระดับโลก`,`ประเทศ / ภูมิภาค`,`ภาษา`,`สกุลเงิน`,`ทั่วโลก`,`ช่วยด้วย AI`,`เสียง + แชต`,`ค้นหาเร็วขึ้น เปรียบเทียบได้ดีกว่า`,`โรงแรม บ้าน รถยนต์ งาน สินค้า และบริการทั่วโลก`,`ใกล้ฉัน`,`ประเทศของฉัน`,`แชต · เสียง · กล้อง · แนบไฟล์`,`ออนไลน์`,`ฉันคือ SEEKVERA AI บอกสิ่งที่คุณต้องการได้เลย`,`ส่งข้อความถึง SEEKVERA AI…`,`เมื่อเปลี่ยนประเทศ ภาษา สกุลเงิน และ AI จะอัปเดตอัตโนมัติ`,`หมวดหมู่ยอดนิยม`,`ทุกหมวดหมู่`,`ตลาดสด`,`ขออะไรก็ได้`],
fa:[`بازار جهانی هوش مصنوعی`,`کشور / منطقه`,`زبان`,`ارز`,`سراسر جهان`,`با کمک هوش مصنوعی`,`صدا + گفتگو`,`سریع‌تر پیدا کنید. بهتر مقایسه کنید.`,`هتل، خانه، خودرو، شغل، محصول و خدمات در سراسر جهان.`,`نزدیک من`,`کشور من`,`گفتگو · صدا · دوربین · پیوست`,`آنلاین`,`من SEEKVERA AI هستم. بگویید چه نیاز دارید.`,`پیام به SEEKVERA AI…`,`تغییر کشور، زبان، ارز و هوش مصنوعی را خودکار به‌روز می‌کند.`,`دسته‌های محبوب`,`همه دسته‌ها`,`بازار زنده`,`هر چیزی درخواست کنید`],
pl:[`GLOBALNY RYNEK AI`,`Kraj / region`,`Język`,`Waluta`,`Cały świat`,`Wspomagane AI`,`Głos + czat`,`Znajdź szybciej. Porównaj lepiej.`,`Hotele, domy, samochody, praca, produkty i usługi na całym świecie.`,`W pobliżu`,`Mój kraj`,`Czat · Głos · Aparat · Załącz`,`Online`,`Jestem SEEKVERA AI. Powiedz, czego potrzebujesz.`,`Wiadomość do SEEKVERA AI…`,`Zmiana kraju automatycznie aktualizuje język, walutę i AI.`,`Popularne kategorie`,`Wszystkie kategorie`,`Rynek na żywo`,`Poproś o cokolwiek`],
nl:[`WERELDWIJDE AI-MARKTPLAATS`,`Land / regio`,`Taal`,`Valuta`,`Wereldwijd`,`Met AI`,`Spraak + chat`,`Vind sneller. Vergelijk beter.`,`Hotels, woningen, auto's, banen, producten en diensten wereldwijd.`,`Bij mij in de buurt`,`Mijn land`,`Chat · Spraak · Camera · Bijlage`,`Online`,`Ik ben SEEKVERA AI. Vertel wat je nodig hebt.`,`Bericht aan SEEKVERA AI…`,`Een ander land kiezen werkt taal, valuta en AI automatisch bij.`,`Populaire categorieën`,`Alle categorieën`,`Live marktplaats`,`Vraag alles`],
ms:[`PASARAN AI GLOBAL`,`Negara / Wilayah`,`Bahasa`,`Mata wang`,`Seluruh dunia`,`Dibantu AI`,`Suara + Sembang`,`Cari lebih cepat. Bandingkan lebih baik.`,`Hotel, rumah, kereta, pekerjaan, produk dan perkhidmatan di seluruh dunia.`,`Berdekatan saya`,`Negara saya`,`Sembang · Suara · Kamera · Lampirkan`,`Dalam talian`,`Saya SEEKVERA AI. Beritahu apa yang anda perlukan.`,`Mesej SEEKVERA AI…`,`Menukar negara mengemas kini bahasa, mata wang dan AI secara automatik.`,`Kategori popular`,`Semua kategori`,`Pasaran langsung`,`Minta apa sahaja`],
fil:[`PANDAIGDIGANG AI MARKETPLACE`,`Bansa / Rehiyon`,`Wika`,`Pera`,`Buong mundo`,`Tulong ng AI`,`Boses + Chat`,`Mas mabilis maghanap. Mas mahusay maghambing.`,`Mga hotel, bahay, kotse, trabaho, produkto at serbisyo sa buong mundo.`,`Malapit sa akin`,`Aking bansa`,`Chat · Boses · Camera · Attach`,`Online`,`Ako ang SEEKVERA AI. Sabihin kung ano ang kailangan mo.`,`Mensahe sa SEEKVERA AI…`,`Kapag binago ang bansa, awtomatikong nagbabago ang wika, pera at AI.`,`Mga sikat na kategorya`,`Lahat ng kategorya`,`Live marketplace`,`Humiling ng anuman`],
ha:[`KASUWAR AI NA DUNIYA`,`Ƙasa / Yanki`,`Harshe`,`Kuɗi`,`Duniya baki ɗaya`,`Taimakon AI`,`Murya + Tattaunawa`,`Nemo da sauri. Kwatanta da kyau.`,`Otal-otal, gidaje, motoci, ayyuka, kayayyaki da hidimomi a duniya.`,`Kusa da ni`,`Ƙasata`,`Tattaunawa · Murya · Kyamara · Haɗa`,`Kan layi`,`Ni SEEKVERA AI ne. Faɗa min abin da kake buƙata.`,`Saƙo ga SEEKVERA AI…`,`Canza ƙasa yana sabunta harshe, kuɗi da AI ta atomatik.`,`Rukunai mashahurai`,`Duk rukunai`,`Kasuwa kai tsaye`,`Nemi komai`],
yo:[`ỌJÀ AI ÀGBÁYÉ`,`Orílẹ̀-èdè / Agbègbè`,`Èdè`,`Owó`,`Kárí ayé`,`Pẹ̀lú ìrànlọ́wọ́ AI`,`Ohùn + Ìfọ̀rọ̀wérọ̀`,`Wa kíákíá. Ṣe àfiwé dáadáa.`,`Hotẹẹli, ilé, ọkọ ayọ́kẹ́lẹ́, iṣẹ́, ọja àti iṣẹ́ káàkiri ayé.`,`Nítòsí mi`,`Orílẹ̀-èdè mi`,`Ìfọ̀rọ̀wérọ̀ · Ohùn · Kámẹ́rà · So pọ̀`,`Lórí ayélujára`,`Èmi ni SEEKVERA AI. Sọ ohun tí o nílò.`,`Ránṣẹ́ sí SEEKVERA AI…`,`Yíyí orílẹ̀-èdè padà máa ń ṣe ìmúdójúìwọ̀n èdè, owó àti AI laifọwọyi.`,`Àwọn ẹ̀ka olókìkí`,`Gbogbo ẹ̀ka`,`Ọjà laaye`,`Béèrè ohunkóhun`],
ig:[`AHỊA AI ỤWA`,`Mba / Mpaghara`,`Asụsụ`,`Ego`,`Ụwa niile`,`Site na enyemaka AI`,`Olu + Nkata`,`Chọta ngwa ngwa. Tụnyere nke ọma.`,`Ụlọ nkwari akụ, ụlọ, ụgbọala, ọrụ, ngwaahịa na ọrụ gburugburu ụwa.`,`Nso m`,`Mba m`,`Nkata · Olu · Kamera · Tinye`,`N'ịntanetị`,`Abụ m SEEKVERA AI. Gwa m ihe ị chọrọ.`,`Ziga SEEKVERA AI ozi…`,`Ịgbanwe mba na-emelite asụsụ, ego na AI na-akpaghị aka.`,`Ngalaba ewu ewu`,`Ngalaba niile`,`Ahịa ndụ`,`Rịọ ihe ọ bụla`],
am:[`ዓለም አቀፍ የAI ገበያ`,`አገር / ክልል`,`ቋንቋ`,`ገንዘብ`,`ዓለም አቀፍ`,`በAI የተደገፈ`,`ድምፅ + ውይይት`,`በፍጥነት ያግኙ። በተሻለ ያነፃፅሩ።`,`ሆቴሎች፣ ቤቶች፣ መኪናዎች፣ ስራዎች፣ ምርቶችና አገልግሎቶች በዓለም ዙሪያ።`,`በአቅራቢያዬ`,`አገሬ`,`ውይይት · ድምፅ · ካሜራ · አያይዝ`,`መስመር ላይ`,`እኔ SEEKVERA AI ነኝ። የሚፈልጉትን ይንገሩኝ።`,`ለ SEEKVERA AI መልእክት…`,`አገር ሲቀየር ቋንቋ፣ ገንዘብ እና AI በራስ-ሰር ይዘምናሉ።`,`ታዋቂ ምድቦች`,`ሁሉም ምድቦች`,`ቀጥታ ገበያ`,`ማንኛውንም ነገር ይጠይቁ`],
he:[`שוק AI עולמי`,`מדינה / אזור`,`שפה`,`מטבע`,`כל העולם`,`בסיוע AI`,`קול + צ'אט`,`מצאו מהר יותר. השוו טוב יותר.`,`מלונות, בתים, מכוניות, משרות, מוצרים ושירותים ברחבי העולם.`,`קרוב אליי`,`המדינה שלי`,`צ'אט · קול · מצלמה · צירוף`,`מקוון`,`אני SEEKVERA AI. ספרו לי מה אתם צריכים.`,`הודעה ל-SEEKVERA AI…`,`שינוי מדינה מעדכן אוטומטית את השפה, המטבע וה-AI.`,`קטגוריות פופולריות`,`כל הקטגוריות`,`שוק חי`,`בקשו כל דבר`],
el:[`ΠΑΓΚΟΣΜΙΑ ΑΓΟΡΑ AI`,`Χώρα / Περιοχή`,`Γλώσσα`,`Νόμισμα`,`Παγκοσμίως`,`Με υποστήριξη AI`,`Φωνή + Συνομιλία`,`Βρείτε γρηγορότερα. Συγκρίνετε καλύτερα.`,`Ξενοδοχεία, σπίτια, αυτοκίνητα, θέσεις εργασίας, προϊόντα και υπηρεσίες παγκοσμίως.`,`Κοντά μου`,`Η χώρα μου`,`Συνομιλία · Φωνή · Κάμερα · Επισύναψη`,`Σε σύνδεση`,`Είμαι το SEEKVERA AI. Πείτε μου τι χρειάζεστε.`,`Μήνυμα στο SEEKVERA AI…`,`Η αλλαγή χώρας ενημερώνει αυτόματα γλώσσα, νόμισμα και AI.`,`Δημοφιλείς κατηγορίες`,`Όλες οι κατηγορίες`,`Ζωντανή αγορά`,`Ζητήστε οτιδήποτε`],
uk:[`ГЛОБАЛЬНИЙ AI-МАРКЕТПЛЕЙС`,`Країна / Регіон`,`Мова`,`Валюта`,`Увесь світ`,`За підтримки AI`,`Голос + чат`,`Знаходьте швидше. Порівнюйте краще.`,`Готелі, житло, авто, робота, товари та послуги по всьому світу.`,`Поруч зі мною`,`Моя країна`,`Чат · Голос · Камера · Вкладення`,`Онлайн`,`Я SEEKVERA AI. Скажіть, що вам потрібно.`,`Повідомлення SEEKVERA AI…`,`Зміна країни автоматично оновлює мову, валюту та AI.`,`Популярні категорії`,`Усі категорії`,`Живий маркетплейс`,`Запитайте будь-що`],
ro:[`PIAȚĂ GLOBALĂ CU AI`,`Țară / Regiune`,`Limbă`,`Monedă`,`În toată lumea`,`Asistat de AI`,`Voce + Chat`,`Găsește mai repede. Compară mai bine.`,`Hoteluri, case, mașini, locuri de muncă, produse și servicii în toată lumea.`,`Lângă mine`,`Țara mea`,`Chat · Voce · Cameră · Atașează`,`Online`,`Sunt SEEKVERA AI. Spune-mi ce ai nevoie.`,`Mesaj către SEEKVERA AI…`,`Schimbarea țării actualizează automat limba, moneda și AI.`,`Categorii populare`,`Toate categoriile`,`Piață live`,`Cere orice`],
cs:[`GLOBÁLNÍ AI TRŽIŠTĚ`,`Země / Region`,`Jazyk`,`Měna`,`Celý svět`,`S podporou AI`,`Hlas + chat`,`Najděte rychleji. Porovnejte lépe.`,`Hotely, bydlení, auta, práce, produkty a služby po celém světě.`,`V mém okolí`,`Moje země`,`Chat · Hlas · Kamera · Příloha`,`Online`,`Jsem SEEKVERA AI. Řekněte mi, co potřebujete.`,`Zpráva pro SEEKVERA AI…`,`Změna země automaticky aktualizuje jazyk, měnu a AI.`,`Oblíbené kategorie`,`Všechny kategorie`,`Živé tržiště`,`Požádejte o cokoli`],
sk:[`GLOBÁLNE AI TRHOVISKO`,`Krajina / Región`,`Jazyk`,`Mena`,`Celý svet`,`S podporou AI`,`Hlas + chat`,`Nájdite rýchlejšie. Porovnajte lepšie.`,`Hotely, bývanie, autá, práca, produkty a služby po celom svete.`,`V mojom okolí`,`Moja krajina`,`Chat · Hlas · Kamera · Príloha`,`Online`,`Som SEEKVERA AI. Povedzte mi, čo potrebujete.`,`Správa pre SEEKVERA AI…`,`Zmena krajiny automaticky aktualizuje jazyk, menu a AI.`,`Obľúbené kategórie`,`Všetky kategórie`,`Živé trhovisko`,`Požiadajte o čokoľvek`],
hu:[`GLOBÁLIS AI PIACTÉR`,`Ország / Régió`,`Nyelv`,`Pénznem`,`Világszerte`,`AI-támogatással`,`Hang + csevegés`,`Találja meg gyorsabban. Hasonlítsa össze jobban.`,`Szállodák, otthonok, autók, állások, termékek és szolgáltatások világszerte.`,`A közelemben`,`Az országom`,`Csevegés · Hang · Kamera · Csatolás`,`Online`,`SEEKVERA AI vagyok. Mondd el, mire van szükséged.`,`Üzenet a SEEKVERA AI-nak…`,`Az országváltás automatikusan frissíti a nyelvet, pénznemet és AI-t.`,`Népszerű kategóriák`,`Minden kategória`,`Élő piactér`,`Kérj bármit`],
sv:[`GLOBAL AI-MARKNADSPLATS`,`Land / Region`,`Språk`,`Valuta`,`Hela världen`,`AI-assisterad`,`Röst + chatt`,`Hitta snabbare. Jämför bättre.`,`Hotell, bostäder, bilar, jobb, produkter och tjänster över hela världen.`,`Nära mig`,`Mitt land`,`Chatt · Röst · Kamera · Bifoga`,`Online`,`Jag är SEEKVERA AI. Berätta vad du behöver.`,`Meddelande till SEEKVERA AI…`,`När du byter land uppdateras språk, valuta och AI automatiskt.`,`Populära kategorier`,`Alla kategorier`,`Live-marknadsplats`,`Be om vad som helst`],
no:[`GLOBAL AI-MARKEDSPLASS`,`Land / Region`,`Språk`,`Valuta`,`Hele verden`,`AI-assistert`,`Stemme + chat`,`Finn raskere. Sammenlign bedre.`,`Hoteller, boliger, biler, jobber, produkter og tjenester over hele verden.`,`Nær meg`,`Mitt land`,`Chat · Stemme · Kamera · Legg ved`,`På nett`,`Jeg er SEEKVERA AI. Fortell hva du trenger.`,`Melding til SEEKVERA AI…`,`Når du bytter land, oppdateres språk, valuta og AI automatisk.`,`Populære kategorier`,`Alle kategorier`,`Live-markedsplass`,`Be om hva som helst`],
da:[`GLOBAL AI-MARKEDSPLADS`,`Land / Region`,`Sprog`,`Valuta`,`Hele verden`,`AI-assisteret`,`Stemme + chat`,`Find hurtigere. Sammenlign bedre.`,`Hoteller, boliger, biler, job, produkter og tjenester i hele verden.`,`I nærheden`,`Mit land`,`Chat · Stemme · Kamera · Vedhæft`,`Online`,`Jeg er SEEKVERA AI. Fortæl mig, hvad du har brug for.`,`Besked til SEEKVERA AI…`,`Skift af land opdaterer automatisk sprog, valuta og AI.`,`Populære kategorier`,`Alle kategorier`,`Live markedsplads`,`Bed om hvad som helst`],
fi:[`MAAILMANLAAJUINEN AI-MARKKINAPAIKKA`,`Maa / Alue`,`Kieli`,`Valuutta`,`Koko maailma`,`AI-avusteinen`,`Ääni + chat`,`Löydä nopeammin. Vertaa paremmin.`,`Hotellit, kodit, autot, työpaikat, tuotteet ja palvelut ympäri maailmaa.`,`Lähellä minua`,`Oma maani`,`Chat · Ääni · Kamera · Liite`,`Verkossa`,`Olen SEEKVERA AI. Kerro mitä tarvitset.`,`Viesti SEEKVERA AI:lle…`,`Maan vaihtaminen päivittää kielen, valuutan ja AI:n automaattisesti.`,`Suositut kategoriat`,`Kaikki kategoriat`,`Live-markkinapaikka`,`Pyydä mitä tahansa`],
bg:[`ГЛОБАЛЕН AI ПАЗАР`,`Държава / Регион`,`Език`,`Валута`,`Целият свят`,`С помощта на AI`,`Глас + чат`,`Намерете по-бързо. Сравнете по-добре.`,`Хотели, домове, автомобили, работа, продукти и услуги по целия свят.`,`Близо до мен`,`Моята държава`,`Чат · Глас · Камера · Прикачи`,`Онлайн`,`Аз съм SEEKVERA AI. Кажете ми от какво имате нужда.`,`Съобщение до SEEKVERA AI…`,`Смяната на държавата автоматично обновява езика, валутата и AI.`,`Популярни категории`,`Всички категории`,`Пазар на живо`,`Поискайте всичко`],
hr:[`GLOBALNA AI TRŽNICA`,`Država / Regija`,`Jezik`,`Valuta`,`Cijeli svijet`,`Uz pomoć AI-ja`,`Glas + chat`,`Pronađite brže. Usporedite bolje.`,`Hoteli, domovi, automobili, poslovi, proizvodi i usluge diljem svijeta.`,`U blizini`,`Moja država`,`Chat · Glas · Kamera · Priloži`,`Online`,`Ja sam SEEKVERA AI. Recite mi što trebate.`,`Poruka SEEKVERA AI-u…`,`Promjena države automatski ažurira jezik, valutu i AI.`,`Popularne kategorije`,`Sve kategorije`,`Tržnica uživo`,`Zatražite bilo što`],
sr:[`ГЛОБАЛНО AI ТРЖИШТЕ`,`Држава / Регион`,`Језик`,`Валута`,`Цео свет`,`Уз помоћ AI`,`Глас + чет`,`Пронађите брже. Упоредите боље.`,`Хотели, куће, аутомобили, послови, производи и услуге широм света.`,`У близини`,`Моја држава`,`Чет · Глас · Камера · Прилог`,`Онлајн`,`Ја сам SEEKVERA AI. Реците ми шта вам треба.`,`Порука за SEEKVERA AI…`,`Промена државе аутоматски ажурира језик, валуту и AI.`,`Популарне категорије`,`Све категорије`,`Тржиште уживо`,`Тражите било шта`],
sl:[`GLOBALNA AI TRŽNICA`,`Država / Regija`,`Jezik`,`Valuta`,`Ves svet`,`S pomočjo AI`,`Glas + klepet`,`Najdite hitreje. Primerjajte bolje.`,`Hoteli, domovi, avtomobili, službe, izdelki in storitve po vsem svetu.`,`V bližini`,`Moja država`,`Klepet · Glas · Kamera · Priponka`,`Na spletu`,`Sem SEEKVERA AI. Povejte, kaj potrebujete.`,`Sporočilo SEEKVERA AI…`,`Sprememba države samodejno posodobi jezik, valuto in AI.`,`Priljubljene kategorije`,`Vse kategorije`,`Tržnica v živo`,`Zahtevajte karkoli`],
lt:[`PASAULINĖ AI RINKA`,`Šalis / Regionas`,`Kalba`,`Valiuta`,`Visas pasaulis`,`Su AI pagalba`,`Balsas + pokalbis`,`Raskite greičiau. Palyginkite geriau.`,`Viešbučiai, namai, automobiliai, darbai, produktai ir paslaugos visame pasaulyje.`,`Netoli manęs`,`Mano šalis`,`Pokalbis · Balsas · Kamera · Priedas`,`Prisijungę`,`Aš esu SEEKVERA AI. Pasakykite, ko jums reikia.`,`Žinutė SEEKVERA AI…`,`Pakeitus šalį automatiškai atnaujinama kalba, valiuta ir AI.`,`Populiarios kategorijos`,`Visos kategorijos`,`Gyva rinka`,`Prašykite bet ko`],
lv:[`GLOBĀLS AI TIRGUS`,`Valsts / Reģions`,`Valoda`,`Valūta`,`Visa pasaule`,`Ar AI palīdzību`,`Balss + tērzēšana`,`Atrodiet ātrāk. Salīdziniet labāk.`,`Viesnīcas, mājas, automašīnas, darbi, produkti un pakalpojumi visā pasaulē.`,`Man tuvumā`,`Mana valsts`,`Tērzēšana · Balss · Kamera · Pielikums`,`Tiešsaistē`,`Es esmu SEEKVERA AI. Pastāstiet, kas jums vajadzīgs.`,`Ziņa SEEKVERA AI…`,`Mainot valsti, valoda, valūta un AI tiek atjaunināti automātiski.`,`Populāras kategorijas`,`Visas kategorijas`,`Tiešais tirgus`,`Lūdziet jebko`],
et:[`ÜLEMAAILMNE AI TURG`,`Riik / Piirkond`,`Keel`,`Valuuta`,`Kogu maailm`,`AI-toega`,`Hääl + vestlus`,`Leia kiiremini. Võrdle paremini.`,`Hotellid, kodud, autod, töökohad, tooted ja teenused üle maailma.`,`Minu lähedal`,`Minu riik`,`Vestlus · Hääl · Kaamera · Lisa`,`Veebis`,`Olen SEEKVERA AI. Ütle, mida vajad.`,`Sõnum SEEKVERA AI-le…`,`Riigi muutmine uuendab keelt, valuutat ja AI-d automaatselt.`,`Populaarsed kategooriad`,`Kõik kategooriad`,`Reaalajas turg`,`Küsi mida tahes`],
ca:[`MERCAT GLOBAL AMB IA`,`País / Regió`,`Idioma`,`Moneda`,`Tot el món`,`Assistit per IA`,`Veu + xat`,`Troba més ràpid. Compara millor.`,`Hotels, cases, cotxes, feines, productes i serveis arreu del món.`,`A prop meu`,`El meu país`,`Xat · Veu · Càmera · Adjunta`,`En línia`,`Sóc SEEKVERA AI. Digues-me què necessites.`,`Missatge a SEEKVERA AI…`,`Canviar de país actualitza automàticament l’idioma, la moneda i la IA.`,`Categories populars`,`Totes les categories`,`Mercat en directe`,`Demana qualsevol cosa`],
is:[`ALÞJÓÐLEGUR AI-MARKAÐUR`,`Land / Svæði`,`Tungumál`,`Gjaldmiðill`,`Um allan heim`,`Með AI aðstoð`,`Rödd + spjall`,`Finndu hraðar. Berðu betur saman.`,`Hótel, heimili, bílar, störf, vörur og þjónusta um allan heim.`,`Nálægt mér`,`Landið mitt`,`Spjall · Rödd · Myndavél · Viðhengi`,`Á netinu`,`Ég er SEEKVERA AI. Segðu mér hvað þú þarft.`,`Skilaboð til SEEKVERA AI…`,`Að skipta um land uppfærir tungumál, gjaldmiðil og AI sjálfkrafa.`,`Vinsælir flokkar`,`Allir flokkar`,`Lifandi markaður`,`Biddu um hvað sem er`],
sq:[`TREG GLOBAL ME AI`,`Shteti / Rajoni`,`Gjuha`,`Monedha`,`Në mbarë botën`,`Me ndihmën e AI`,`Zë + bisedë`,`Gjeni më shpejt. Krahasoni më mirë.`,`Hotele, shtëpi, makina, punë, produkte dhe shërbime në mbarë botën.`,`Pranë meje`,`Shteti im`,`Bisedë · Zë · Kamera · Bashkëngjit`,`Online`,`Jam SEEKVERA AI. Më tregoni çfarë ju duhet.`,`Mesazh për SEEKVERA AI…`,`Ndryshimi i shtetit përditëson automatikisht gjuhën, monedhën dhe AI.`,`Kategoritë popullore`,`Të gjitha kategoritë`,`Tregu live`,`Kërkoni çfarëdo`],
mk:[`ГЛОБАЛЕН AI ПАЗАР`,`Држава / Регион`,`Јазик`,`Валута`,`Цел свет`,`Со помош на AI`,`Глас + разговор`,`Најдете побрзо. Споредете подобро.`,`Хотели, домови, автомобили, работни места, производи и услуги низ светот.`,`Во моја близина`,`Мојата држава`,`Разговор · Глас · Камера · Прилог`,`Онлајн`,`Јас сум SEEKVERA AI. Кажете ми што ви треба.`,`Порака до SEEKVERA AI…`,`Промена на државата автоматски ги ажурира јазикот, валутата и AI.`,`Популарни категории`,`Сите категории`,`Пазар во живо`,`Побарајте што било`],
ka:[`გლობალური AI ბაზარი`,`ქვეყანა / რეგიონი`,`ენა`,`ვალუტა`,`მთელი მსოფლიო`,`AI-ის დახმარებით`,`ხმა + ჩატი`,`იპოვეთ უფრო სწრაფად. შეადარეთ უკეთ.`,`სასტუმროები, სახლები, მანქანები, სამუშაოები, პროდუქტები და სერვისები მთელ მსოფლიოში.`,`ჩემთან ახლოს`,`ჩემი ქვეყანა`,`ჩატი · ხმა · კამერა · დანართი`,`ონლაინ`,`მე ვარ SEEKVERA AI. მითხარით, რა გჭირდებათ.`,`შეტყობინება SEEKVERA AI-ს…`,`ქვეყნის შეცვლა ავტომატურად ანახლებს ენას, ვალუტასა და AI-ს.`,`პოპულარული კატეგორიები`,`ყველა კატეგორია`,`ცოცხალი ბაზარი`,`მოითხოვეთ ყველაფერი`],
hy:[`ԳԼՈԲԱԼ AI ՇՈՒԿԱ`,`Երկիր / Տարածաշրջան`,`Լեզու`,`Արժույթ`,`Ամբողջ աշխարհում`,`AI-ի աջակցությամբ`,`Ձայն + զրույց`,`Գտեք ավելի արագ։ Համեմատեք ավելի լավ։`,`Հյուրանոցներ, տներ, մեքենաներ, աշխատանքներ, ապրանքներ և ծառայություններ ամբողջ աշխարհում։`,`Ինձ մոտ`,`Իմ երկիրը`,`Զրույց · Ձայն · Տեսախցիկ · Կցել`,`Առցանց`,`Ես SEEKVERA AI-ն եմ։ Ասեք՝ ինչ է ձեզ պետք։`,`Հաղորդագրություն SEEKVERA AI-ին…`,`Երկիրը փոխելիս լեզուն, արժույթը և AI-ն ինքնաբար թարմացվում են։`,`Հայտնի կատեգորիաներ`,`Բոլոր կատեգորիաները`,`Ուղիղ շուկա`,`Խնդրեք ցանկացած բան`],
az:[`QLOBAL AI BAZARI`,`Ölkə / Region`,`Dil`,`Valyuta`,`Bütün dünya`,`AI dəstəyi ilə`,`Səs + söhbət`,`Daha tez tapın. Daha yaxşı müqayisə edin.`,`Dünyada otellər, evlər, avtomobillər, işlər, məhsullar və xidmətlər.`,`Yaxınımda`,`Ölkəm`,`Söhbət · Səs · Kamera · Əlavə et`,`Onlayn`,`Mən SEEKVERA AI-yam. Nəyə ehtiyacınız olduğunu deyin.`,`SEEKVERA AI-a mesaj…`,`Ölkəni dəyişmək dili, valyutanı və AI-ni avtomatik yeniləyir.`,`Populyar kateqoriyalar`,`Bütün kateqoriyalar`,`Canlı bazar`,`İstənilən şeyi istəyin`],
kk:[`ЖАҺАНДЫҚ AI НАРЫҒЫ`,`Ел / Аймақ`,`Тіл`,`Валюта`,`Бүкіл әлем`,`AI көмегімен`,`Дауыс + чат`,`Тезірек табыңыз. Жақсырақ салыстырыңыз.`,`Әлем бойынша қонақүйлер, үйлер, көліктер, жұмыс, өнімдер және қызметтер.`,`Маған жақын`,`Менің елім`,`Чат · Дауыс · Камера · Тіркеу`,`Онлайн`,`Мен SEEKVERA AI-мын. Не керегін айтыңыз.`,`SEEKVERA AI-ға хабарлама…`,`Елді өзгерту тіл, валюта және AI-ды автоматты жаңартады.`,`Танымал санаттар`,`Барлық санаттар`,`Тікелей нарық`,`Кез келген нәрсені сұраңыз`],
uz:[`GLOBAL AI BOZORI`,`Mamlakat / Hudud`,`Til`,`Valyuta`,`Butun dunyo`,`AI yordamida`,`Ovoz + chat`,`Tezroq toping. Yaxshiroq solishtiring.`,`Dunyo bo‘ylab mehmonxonalar, uylar, avtomobillar, ishlar, mahsulotlar va xizmatlar.`,`Yaqinimda`,`Mening mamlakatim`,`Chat · Ovoz · Kamera · Biriktirish`,`Onlayn`,`Men SEEKVERA AIman. Nima kerakligini ayting.`,`SEEKVERA AIga xabar…`,`Mamlakatni o‘zgartirish til, valyuta va AI-ni avtomatik yangilaydi.`,`Ommabop toifalar`,`Barcha toifalar`,`Jonli bozor`,`Istalgan narsani so‘rang`],
ky:[`ДҮЙНӨЛҮК AI БАЗАР`,`Өлкө / Аймак`,`Тил`,`Валюта`,`Бүткүл дүйнө`,`AI жардамы менен`,`Үн + чат`,`Тезирээк табыңыз. Жакшыраак салыштырыңыз.`,`Дүйнө жүзү боюнча мейманканалар, үйлөр, унаалар, жумуштар, товарлар жана кызматтар.`,`Мага жакын`,`Менин өлкөм`,`Чат · Үн · Камера · Тиркөө`,`Онлайн`,`Мен SEEKVERA AIмин. Эмне керек экенин айтыңыз.`,`SEEKVERA AIга билдирүү…`,`Өлкөнү өзгөртүү тилди, валютаны жана AIды автоматтык жаңыртат.`,`Популярдуу категориялар`,`Бардык категориялар`,`Жандуу базар`,`Каалаган нерсени сураңыз`],
tg:[`БОЗОРИ ҶАҲОНИИ AI`,`Кишвар / Минтақа`,`Забон`,`Асъор`,`Тамоми ҷаҳон`,`Бо ёрии AI`,`Овоз + чат`,`Тезтар ёбед. Беҳтар муқоиса кунед.`,`Меҳмонхонаҳо, хонаҳо, мошинҳо, ҷойҳои корӣ, маҳсулот ва хизматрасониҳо дар саросари ҷаҳон.`,`Наздики ман`,`Кишвари ман`,`Чат · Овоз · Камера · Замима`,`Онлайн`,`Ман SEEKVERA AI ҳастам. Бигӯед, ба шумо чӣ лозим аст.`,`Паём ба SEEKVERA AI…`,`Иваз кардани кишвар забон, асъор ва AI-ро худкор нав мекунад.`,`Категорияҳои маъмул`,`Ҳама категорияҳо`,`Бозори зинда`,`Ҳар чизро дархост кунед`],
tk:[`DÜNÝÄLIK AI BAZARY`,`Ýurt / Sebit`,`Dil`,`Pul birligi`,`Bütin dünýä`,`AI kömegi bilen`,`Ses + söhbet`,`Has çalt tapyň. Has gowy deňeşdiriň.`,`Dünýä boýunça myhmanhanalar, öýler, awtoulaglar, işler, önümler we hyzmatlar.`,`Ýakynymda`,`Meniň ýurdum`,`Söhbet · Ses · Kamera · Goşmak`,`Onlaýn`,`Men SEEKVERA AI. Size näme gerekdigini aýdyň.`,`SEEKVERA AI-a habar…`,`Ýurdy üýtgetmek dili, pul birligini we AI-ny awtomatiki täzeleýär.`,`Meşhur kategoriýalar`,`Ähli kategoriýalar`,`Göni bazar`,`Islendik zady soraň`],
ne:[`विश्वव्यापी एआई बजार`,`देश / क्षेत्र`,`भाषा`,`मुद्रा`,`विश्वभर`,`एआई सहयोग`,`आवाज + च्याट`,`छिटो फेला पार्नुहोस्। राम्रोसँग तुलना गर्नुहोस्।`,`विश्वभर होटल, घर, कार, रोजगारी, उत्पादन र सेवाहरू।`,`मेरो नजिक`,`मेरो देश`,`च्याट · आवाज · क्यामेरा · संलग्न`,`अनलाइन`,`म SEEKVERA AI हुँ। तपाईंलाई के चाहिन्छ भन्नुहोस्।`,`SEEKVERA AI लाई सन्देश…`,`देश परिवर्तन गर्दा भाषा, मुद्रा र AI स्वतः अपडेट हुन्छ।`,`लोकप्रिय श्रेणीहरू`,`सबै श्रेणीहरू`,`लाइभ बजार`,`जे पनि अनुरोध गर्नुहोस्`],
si:[`ගෝලීය AI වෙළඳපොළ`,`රට / කලාපය`,`භාෂාව`,`මුදල්`,`ලොව පුරා`,`AI සහාය`,`හඬ + චැට්`,`වේගයෙන් සොයන්න. වඩා හොඳින් සසඳන්න.`,`ලොව පුරා හෝටල්, නිවාස, මෝටර් රථ, රැකියා, නිෂ්පාදන සහ සේවා.`,`මා අසල`,`මගේ රට`,`චැට් · හඬ · කැමරාව · අමුණන්න`,`ඔන්ලයින්`,`මම SEEKVERA AI. ඔබට අවශ්‍ය දේ කියන්න.`,`SEEKVERA AI වෙත පණිවිඩයක්…`,`රට වෙනස් කළ විට භාෂාව, මුදල් සහ AI ස්වයංක්‍රීයව යාවත්කාලීන වේ.`,`ජනප්‍රිය කාණ්ඩ`,`සියලු කාණ්ඩ`,`සජීවී වෙළඳපොළ`,`ඕනෑම දෙයක් ඉල්ලන්න`],
ta:[`உலகளாவிய AI சந்தை`,`நாடு / பகுதி`,`மொழி`,`நாணயம்`,`உலகம் முழுவதும்`,`AI உதவியுடன்`,`குரல் + அரட்டை`,`வேகமாக கண்டுபிடிக்கவும். சிறப்பாக ஒப்பிடவும்.`,`உலகம் முழுவதும் ஹோட்டல்கள், வீடுகள், கார்கள், வேலைகள், பொருட்கள் மற்றும் சேவைகள்.`,`என் அருகில்`,`என் நாடு`,`அரட்டை · குரல் · கேமரா · இணைப்பு`,`ஆன்லைன்`,`நான் SEEKVERA AI. உங்களுக்கு என்ன வேண்டும் என்று சொல்லுங்கள்.`,`SEEKVERA AI-க்கு செய்தி…`,`நாடு மாறும்போது மொழி, நாணயம் மற்றும் AI தானாக புதுப்பிக்கப்படும்.`,`பிரபல வகைகள்`,`அனைத்து வகைகள்`,`நேரடி சந்தை`,`எதையும் கேளுங்கள்`],
km:[`ទីផ្សារ AI សកល`,`ប្រទេស / តំបន់`,`ភាសា`,`រូបិយប័ណ្ណ`,`ទូទាំងពិភពលោក`,`ជំនួយដោយ AI`,`សំឡេង + ជជែក`,`ស្វែងរកលឿនជាងមុន។ ប្រៀបធៀបបានល្អជាងមុន។`,`សណ្ឋាគារ ផ្ទះ រថយន្ត ការងារ ផលិតផល និងសេវាកម្មទូទាំងពិភពលោក។`,`នៅជិតខ្ញុំ`,`ប្រទេសរបស់ខ្ញុំ`,`ជជែក · សំឡេង · កាមេរ៉ា · ភ្ជាប់`,`អនឡាញ`,`ខ្ញុំគឺ SEEKVERA AI។ ប្រាប់ខ្ញុំថាអ្នកត្រូវការអ្វី។`,`ផ្ញើសារទៅ SEEKVERA AI…`,`ការប្តូរប្រទេសនឹងធ្វើបច្ចុប្បន្នភាពភាសា រូបិយប័ណ្ណ និង AI ដោយស្វ័យប្រវត្តិ។`,`ប្រភេទពេញនិយម`,`ប្រភេទទាំងអស់`,`ទីផ្សារផ្ទាល់`,`ស្នើសុំអ្វីក៏បាន`],
lo:[`ຕະຫຼາດ AI ທົ່ວໂລກ`,`ປະເທດ / ພາກພື້ນ`,`ພາສາ`,`ສະກຸນເງິນ`,`ທົ່ວໂລກ`,`ຊ່ວຍໂດຍ AI`,`ສຽງ + ແຊັດ`,`ຊອກຫາໄວຂຶ້ນ. ປຽບທຽບໄດ້ດີຂຶ້ນ.`,`ໂຮງແຮມ, ເຮືອນ, ລົດ, ວຽກ, ສິນຄ້າ ແລະ ບໍລິການທົ່ວໂລກ.`,`ໃກ້ຂ້ອຍ`,`ປະເທດຂອງຂ້ອຍ`,`ແຊັດ · ສຽງ · ກ້ອງ · ແນບ`,`ອອນລາຍ`,`ຂ້ອຍແມ່ນ SEEKVERA AI. ບອກສິ່ງທີ່ທ່ານຕ້ອງການ.`,`ຂໍ້ຄວາມຫາ SEEKVERA AI…`,`ການປ່ຽນປະເທດຈະອັບເດດພາສາ, ສະກຸນເງິນ ແລະ AI ອັດຕະໂນມັດ.`,`ໝວດໝູ່ຍອດນິຍົມ`,`ໝວດໝູ່ທັງໝົດ`,`ຕະຫຼາດສົດ`,`ຂໍສິ່ງໃດກໍໄດ້`],
my:[`ကမ္ဘာလုံးဆိုင်ရာ AI စျေးကွက်`,`နိုင်ငံ / ဒေသ`,`ဘာသာစကား`,`ငွေကြေး`,`ကမ္ဘာတစ်ဝန်း`,`AI အကူအညီ`,`အသံ + စကားပြော`,`ပိုမြန်မြန်ရှာပါ။ ပိုကောင်းကောင်းနှိုင်းယှဉ်ပါ။`,`ကမ္ဘာတစ်ဝန်း ဟိုတယ်များ၊ အိမ်များ၊ ကားများ၊ အလုပ်များ၊ ထုတ်ကုန်များနှင့် ဝန်ဆောင်မှုများ။`,`ကျွန်ုပ်အနီး`,`ကျွန်ုပ်၏နိုင်ငံ`,`စကားပြော · အသံ · ကင်မရာ · ပူးတွဲ`,`အွန်လိုင်း`,`ကျွန်ုပ်သည် SEEKVERA AI ဖြစ်သည်။ သင်လိုအပ်တာကို ပြောပါ။`,`SEEKVERA AI သို့ စာပို့ရန်…`,`နိုင်ငံပြောင်းလဲပါက ဘာသာစကား၊ ငွေကြေးနှင့် AI ကို အလိုအလျောက် အပ်ဒိတ်လုပ်ပါမည်။`,`လူကြိုက်များသောအမျိုးအစားများ`,`အမျိုးအစားအားလုံး`,`တိုက်ရိုက်စျေးကွက်`,`မည်သည့်အရာမဆို တောင်းဆိုပါ`],
mn:[`ДЭЛХИЙН AI ЗАХ ЗЭЭЛ`,`Улс / Бүс`,`Хэл`,`Валют`,`Дэлхий даяар`,`AI тусламжтай`,`Дуу + чат`,`Илүү хурдан ол. Илүү сайн харьцуул.`,`Дэлхий даяарх зочид буудал, орон сууц, машин, ажил, бүтээгдэхүүн, үйлчилгээ.`,`Надад ойр`,`Миний улс`,`Чат · Дуу · Камер · Хавсаргах`,`Онлайн`,`Би SEEKVERA AI. Танд юу хэрэгтэйг хэлээрэй.`,`SEEKVERA AI-д мессеж…`,`Улс солиход хэл, валют болон AI автоматаар шинэчлэгдэнэ.`,`Алдартай ангиллууд`,`Бүх ангилал`,`Шууд зах зээл`,`Юуг ч хүс`],
zu:[`IMAKETHE YE-AI YOMHLABA`,`Izwe / Isifunda`,`Ulimi`,`Imali`,`Umhlaba wonke`,`Ngosizo lwe-AI`,`Izwi + Ingxoxo`,`Thola ngokushesha. Qhathanisa kangcono.`,`Amahhotela, amakhaya, izimoto, imisebenzi, imikhiqizo nezinsizakalo emhlabeni wonke.`,`Eduze kwami`,`Izwe lami`,`Ingxoxo · Izwi · Ikhamera · Namathisela`,`Ku-inthanethi`,`Ngingu SEEKVERA AI. Ngitshele okudingayo.`,`Umlayezo ku-SEEKVERA AI…`,`Ukushintsha izwe kuvuselela ulimi, imali ne-AI ngokuzenzakalela.`,`Izigaba ezidumile`,`Zonke izigaba`,`Imakethe ebukhoma`,`Cela noma yini`],
af:[`WÊRELDWYE AI-MARKPLEK`,`Land / Streek`,`Taal`,`Geldeenheid`,`Wêreldwyd`,`Met AI-hulp`,`Stem + klets`,`Vind vinniger. Vergelyk beter.`,`Hotelle, huise, motors, werk, produkte en dienste wêreldwyd.`,`Naby my`,`My land`,`Klets · Stem · Kamera · Heg aan`,`Aanlyn`,`Ek is SEEKVERA AI. Sê vir my wat jy nodig het.`,`Boodskap aan SEEKVERA AI…`,`Wanneer jy land verander, word taal, geldeenheid en AI outomaties opgedateer.`,`Gewilde kategorieë`,`Alle kategorieë`,`Regstreekse mark`,`Vra enigiets`],
be:[`ГЛАБАЛЬНЫ AI-МАРКЕТПЛЭЙС`,`Краіна / Рэгіён`,`Мова`,`Валюта`,`Увесь свет`,`З дапамогай AI`,`Голас + чат`,`Знаходзьце хутчэй. Параўноўвайце лепш.`,`Гатэлі, дамы, аўтамабілі, праца, тавары і паслугі па ўсім свеце.`,`Побач са мной`,`Мая краіна`,`Чат · Голас · Камера · Далучыць`,`Анлайн`,`Я SEEKVERA AI. Скажыце, што вам патрэбна.`,`Паведамленне SEEKVERA AI…`,`Змена краіны аўтаматычна абнаўляе мову, валюту і AI.`,`Папулярныя катэгорыі`,`Усе катэгорыі`,`Жывы маркетплейс`,`Запытайце што заўгодна`],
bs:[`GLOBALNO AI TRŽIŠTE`,`Država / Regija`,`Jezik`,`Valuta`,`Cijeli svijet`,`Uz pomoć AI`,`Glas + chat`,`Pronađite brže. Uporedite bolje.`,`Hoteli, domovi, automobili, poslovi, proizvodi i usluge širom svijeta.`,`U blizini`,`Moja država`,`Chat · Glas · Kamera · Priloži`,`Online`,`Ja sam SEEKVERA AI. Recite mi šta vam treba.`,`Poruka za SEEKVERA AI…`,`Promjena države automatski ažurira jezik, valutu i AI.`,`Popularne kategorije`,`Sve kategorije`,`Tržište uživo`,`Tražite bilo šta`],
dz:[`འཛམ་གླིང་ AI ཚོང་ར`,`རྒྱལ་ཁབ / ས་ཁོངས`,`སྐད་ཡིག`,`དངུལ་ལོར`,`འཛམ་གླིང་ཡོངས`,`AI རོགས་རམ`,`སྐད + གླེང་མོལ`,`མགྱོགས་པར་འཚོལ། ལེགས་པར་བསྡུར།`,`འཛམ་གླིང་ཡོངས་ཀྱི་མགྲོན་ཁང་། ཁང་པ། མོ་ཊ། ལས་ཀ། ཐོན་རྫས་དང་ཞབས་ཏོག`,`ངའི་ཉེ་འགྲམ`,`ངའི་རྒྱལ་ཁབ`,`གླེང་མོལ · སྐད · པར་ཆས · ཟུར་སྦྱར`,`དྲ་ཐོག`,`ང་ SEEKVERA AI ཡིན། ཁྱེད་ལ་ག་རེ་དགོས་སམ།`,`SEEKVERA AI ལ་འཕྲིན་ཐུང…`,`རྒྱལ་ཁབ་བསྒྱུར་ན་སྐད་ཡིག དངུལ་ལོར་དང AI རང་འགུལ་གྱིས་གསར་བཅོས་བྱེད།`,`དར་ཁྱབ་ཆེ་བའི་རིགས`,`རིགས་ཚང་མ`,`ཐད་ཀར་ཚོང་ར`,`ག་རེ་ཡང་ཞུ་ཆོག`],
ti:[`ዓለምለኻዊ ዕዳጋ AI`,`ሃገር / ክልል`,`ቋንቋ`,`ገንዘብ`,`መላእ ዓለም`,`ብAI ዝተሓገዘ`,`ድምጺ + ዕላል`,`ብቕልጡፍ ርኸብ። ብዝሓሸ ኣወዳድር።`,`ሆቴላት፣ ኣባይቲ፣ መካይን፣ ስራሕ፣ ፍርያትን ኣገልግሎታትን ኣብ መላእ ዓለም።`,`ኣብ ጥቓይ`,`ሃገረይ`,`ዕላል · ድምጺ · ካሜራ · ኣተሓሕዝ`,`ኦንላይን`,`ኣነ SEEKVERA AI እየ። ዘድልየካ ንገረኒ።`,`ናብ SEEKVERA AI መልእኽቲ…`,`ሃገር ምቕያር ቋንቋ፣ ገንዘብን AIን ብራሱ የሐድስ።`,`ተፈተውቲ ምድባት`,`ኩሎም ምድባት`,`ቀጥታ ዕዳጋ`,`ዝደለኻዮ ሕተት`],
fo:[`ALTJÓÐA AI-MARKNAÐUR`,`Land / Øki`,`Mál`,`Gjaldoyra`,`Allur heimurin`,`Við AI-hjálp`,`Rødd + kjatt`,`Finn skjótari. Samanber betri.`,`Hotell, heim, bilar, størv, vørur og tænastur um allan heim.`,`Nær hjá mær`,`Mítt land`,`Kjatt · Rødd · Kamera · Legg við`,`Á netinum`,`Eg eri SEEKVERA AI. Sig mær, hvat tú hevur brúk fyri.`,`Boð til SEEKVERA AI…`,`Tá land verður broytt, verða mál, gjaldoyra og AI dagførd sjálvvirkandi.`,`Væl umtóktir bólkar`,`Allir bólkar`,`Livandi marknaður`,`Bið um hvat sum helst`],
kl:[`SILARSUARMI AI NIUERFIK`,`Nuna / Immikkoortoq`,`Oqaatsit`,`Aningaasat`,`Silarsuaq tamakkerlugu`,`AI-mit ikiorneqarluni`,`Nipaa + oqaloqatigiinneq`,`Sukkanerusumik nassaaruk. Pitsaanerusumik sanilliuguk.`,`Hotellit, illut, biilit, suliffiit, nioqqutissat sullissinerillu silarsuaq tamakkerlugu.`,`Uannut qanittumi`,`Nunaga`,`Oqaloqatigiinneq · Nipaa · Kamera · Ilanngussaq`,`Online`,`Uanga SEEKVERA AI. Suna pisariaqartippiuk?`,`SEEKVERA AI-mut nalunaarut…`,`Nuna allanngortikkukku oqaatsit, aningaasat AI-lu nammineerlutik nutarterneqassapput.`,`Immikkoortut nuannarineqartut`,`Immikkoortut tamarmik`,`Toqqaannartumik niuerfik`,`Sunilluunniit qinnuteqarit`],
rw:[`ISOKO RYA AI RYO KU ISI`,`Igihugu / Akarere`,`Ururimi`,`Ifaranga`,`Isi yose`,`Ifashijwe na AI`,`Ijwi + Ikiganiro`,`Shaka vuba. Gereranya neza.`,`Amahoteri, amazu, imodoka, akazi, ibicuruzwa na serivisi ku isi yose.`,`Hafi yanjye`,`Igihugu cyanjye`,`Ikiganiro · Ijwi · Kamera · Ongeraho`,`Kuri murandasi`,`Ndi SEEKVERA AI. Mbwira icyo ukeneye.`,`Ubutumwa kuri SEEKVERA AI…`,`Guhindura igihugu bihita bivugurura ururimi, ifaranga na AI.`,`Ibyiciro bikunzwe`,`Ibyiciro byose`,`Isoko ririho ubu`,`Saba icyo ushaka cyose`],
sm:[`MAKETI AI FAAVAOMALO`,`Atunuʻu / Itulagi`,`Gagana`,`Tupe`,`Lalolagi atoa`,`Fesoasoani a le AI`,`Leo + Talanoaga`,`Saili vave. Faatusatusa lelei.`,`Faletalimalo, fale, taavale, galuega, oloa ma auaunaga i le lalolagi atoa.`,`Latalata mai`,`Loʻu atunuu`,`Talanoaga · Leo · Meapueata · Faapipii`,`Luga o le initaneti`,`O aʻu o SEEKVERA AI. Taʻu mai le mea e te manaʻomia.`,`Savali i SEEKVERA AI…`,`A suia le atunuu, e otometi ona faafou le gagana, tupe ma AI.`,`Vaega lauiloa`,`Vaega uma`,`Maketi ola`,`Talosaga soʻo se mea`],
to:[`MAKETI AI FAKAMĀMANI`,`Fonua / Vahefonua`,`Lea`,`Paʻanga`,`Māmani kotoa`,`Tokoni AI`,`Leʻo + Talanoa`,`Kumi vave ange. Fakafehoanaki lelei ange.`,`Hotele, ʻapi, meʻalele, ngāue, koloa mo e ngaahi ngāue ʻi he māmani kotoa.`,`Ofi kiate au`,`Hoku fonua`,`Talanoa · Leʻo · Meʻafaitā · Fakapipiki`,`ʻI he ʻinitaneti`,`Ko au ko SEEKVERA AI. Tala mai ʻa e meʻa ʻoku ke fiemaʻu.`,`Pōpoaki ki SEEKVERA AI…`,`ʻI hono liliu e fonua ʻoku fakafoʻou fakahangatonu e lea, paʻanga mo e AI.`,`Ngaahi faʻahinga manakoa`,`Ngaahi faʻahinga kotoa`,`Maketi moʻui`,`Kole ha meʻa pē`],
so:[`SUUQA AI EE CAALAMKA`,`Dal / Gobol`,`Luqad`,`Lacag`,`Adduunka oo dhan`,`Caawinta AI`,`Cod + Sheeko`,`Si dhakhso ah u hel. Si fiican u barbar dhig.`,`Hoteello, guryo, baabuur, shaqooyin, badeecooyin iyo adeegyo adduunka oo dhan.`,`Ii dhow`,`Dalkayga`,`Sheeko · Cod · Kamarad · Ku lifaaq`,`Khadka tooska ah`,`Waxaan ahay SEEKVERA AI. Ii sheeg waxa aad u baahan tahay.`,`Farriin u dir SEEKVERA AI…`,`Beddelka dalka wuxuu si toos ah u cusboonaysiiyaa luqadda, lacagta iyo AI.`,`Qaybaha caanka ah`,`Dhammaan qaybaha`,`Suuqa tooska ah`,`Codso wax kasta`],
dv:[`ދުނިޔޭގެ AI މާކެޓް`,`ޤައުމު / ސަރަޙައްދު`,`ބަސް`,`ފައިސާ`,`ދުނިޔެ މުޅިން`,`AI އެހީއާއެކު`,`އަޑު + ޗެޓް`,`އަވަހަށް ހޯދާ. ރަނގަޅަށް އަޅާކިޔާ.`,`ދުނިޔެ މުޅީގައި ހޮޓެލް، ގެ، ކާރު، ވަޒީފާ، މުދާ އަދި ޚިދުމަތް.`,`އަހަރެންގެ ކައިރީގައި`,`އަހަރެންގެ ޤައުމު`,`ޗެޓް · އަޑު · ކެމެރާ · އެޓޭޗް`,`އޮންލައިން`,`އަހަރެން SEEKVERA AI. ތިބާއަށް ބޭނުންވާ ކަމެއް ބުނެލާ.`,`SEEKVERA AI އަށް މެސެޖް…`,`ޤައުމު ބަދަލުކުރުމުން ބަސް، ފައިސާ އަދި AI އޮޓޮމެޓިކަލީ ބަދަލުވާނެ.`,`މަޝްހޫރު ކެޓަގަރީތައް`,`ހުރިހާ ކެޓަގަރީތައް`,`ލައިވް މާކެޓް`,`ކޮންމެ އެއްޗެއް ވެސް އެދޭ`],
mt:[`SUQ GLOBALI BL-AI`,`Pajjiż / Reġjun`,`Lingwa`,`Munita`,`Madwar id-dinja`,`Megħjun bl-AI`,`Vuċi + Chat`,`Sib aktar malajr. Qabbel aħjar.`,`Lukandi, djar, karozzi, impjiegi, prodotti u servizzi madwar id-dinja.`,`Qrib tiegħi`,`Pajjiżi`,`Chat · Vuċi · Kamera · Ehmeż`,`Online`,`Jien SEEKVERA AI. Għidli x’għandek bżonn.`,`Messaġġ lil SEEKVERA AI…`,`Meta tbiddel il-pajjiż, il-lingwa, il-munita u l-AI jiġu aġġornati awtomatikament.`,`Kategoriji popolari`,`Il-kategoriji kollha`,`Suq live`,`Itlob kwalunkwe ħaġa`],
mg:[`TSENA AI MANERAN-TANY`,`Firenena / Faritra`,`Fiteny`,`Vola`,`Maneran-tany`,`Ampian’ny AI`,`Feo + Resaka`,`Mitadiava haingana kokoa. Ampitahao tsara kokoa.`,`Hotely, trano, fiara, asa, vokatra ary tolotra maneran-tany.`,`Akaiky ahy`,`Fireneko`,`Resaka · Feo · Fakan-tsary · Ampidiro`,`An-tserasera`,`Izaho no SEEKVERA AI. Lazao izay ilainao.`,`Hafatra ho an'ny SEEKVERA AI…`,`Ny fanovana firenena dia manavao ho azy ny fiteny, vola ary AI.`,`Sokajy malaza`,`Sokajy rehetra`,`Tsena mivantana`,`Mangataha na inona na inona`]
};
const RTL=new Set(['ar','fa','ur','he','dv']);
const IDX=Object.fromEntries(K.map((k,i)=>[k,i]));
function code(){let v=document.querySelector('.sv-controls select#lang,select#lang.sv-select')?.value||localStorage.getItem('seekvera_lang')||document.documentElement.lang||navigator.language||'en';if(v==='auto')v=navigator.language||'en';return String(v).toLowerCase().split(/[-_]/)[0]||'en'}
function pack(){const c=code();return {c,p:L[c]||L.en}}
function setText(el,v){if(el&&v&&el.textContent!==v)el.textContent=v}
function setHTMLText(el,v){if(el&&v&&el.textContent.trim()!==v)el.textContent=v}
function apply(){const {c,p}=pack();const t=k=>p[IDX[k]]||L.en[IDX[k]];
 document.documentElement.lang=c;document.documentElement.dir=RTL.has(c)?'rtl':'ltr';
 setText(document.querySelector('.r5-brand small'),t('brand'));
 const caps=[...document.querySelectorAll('.sv-controls .sv-control-field small')];if(caps[0])setText(caps[0],t('country'));if(caps[1])setText(caps[1],t('language'));if(caps[2])setText(caps[2],t('currency'));
 const kick=document.querySelectorAll('.r5-kicker span');if(kick[0])setText(kick[0],'🌍 '+t('worldwide'));if(kick[2])setText(kick[2],t('ai'));if(kick[4])setText(kick[4],t('voice'));
 setText(document.querySelector('.r5-hero h1'),t('headline'));setText(document.querySelector('.r5-hero>p'),t('hero'));
 setText(document.querySelector('[data-scope="near"]'),'📍 '+t('near'));setText(document.querySelector('[data-scope="country"]'),t('mine'));setText(document.querySelector('[data-scope="worldwide"]'),'🌐 '+t('worldwide'));
 setText(document.querySelector('.sv-chat-head small'),t('chatmeta'));const online=document.querySelector('.sv-chat-head>span');if(online)setText(online,'● '+t('online'));
 const first=document.querySelector('#aiMessages .ai-msg.bot:first-child');if(first&&!first.dataset.r14UserReply)setText(first,t('hello'));
 const input=document.getElementById('aiChatInput');if(input)input.placeholder=t('placeholder');
 setText(document.querySelector('.r5-ai-note'),t('note'));setText(document.querySelector('#categories h2'),t('popular'));setText(document.querySelector('#categories .r5-section-head>a'),t('all')+' →');
 const heads=[...document.querySelectorAll('.r5-section h2')];for(const h of heads){const s=(h.dataset.r14Source||h.textContent||'').trim();if(!h.dataset.r14Source)h.dataset.r14Source=s;if(/Live marketplace/i.test(s))setText(h,t('live'));if(/Request anything/i.test(s))setText(h,t('request'))}
 if(c!=='en'){document.documentElement.classList.add('sv-r14-localized')}else document.documentElement.classList.remove('sv-r14-localized');
 document.title='SEEKVERA — '+t('headline');
}
let timer=0;function schedule(ms=0){clearTimeout(timer);timer=setTimeout(apply,ms)}
function bind(){schedule();document.addEventListener('change',e=>{if(e.target?.id==='country'||e.target?.id==='lang')schedule(40)},true);window.addEventListener('seekvera:languagechange',()=>schedule(20));window.addEventListener('seekvera:countrychange',()=>schedule(20));window.addEventListener('pageshow',()=>schedule(20));new MutationObserver(ms=>{if(ms.some(m=>m.target===document.documentElement||m.target?.id==='lang'||m.target?.id==='country'))schedule(30)}).observe(document.documentElement,{attributes:true,attributeFilter:['lang','dir'],subtree:true});}
const st=document.createElement('style');st.textContent=`html.sv-r14-localized .r5-tile small{display:none!important}html.sv-r14-localized .r5-section-head p{display:none!important}@media(max-width:780px){html.sv-r14-localized .r5-hero>p{display:block!important}}`;document.head.appendChild(st);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
window.SEEKVERA_LOCALE_R14={apply,schedule,t:k=>{const {p}=pack();return p[IDX[k]]||L.en[IDX[k]]},languages:Object.keys(L),version:'20260924-r15'};
})();
