(()=>{
'use strict';
if(window.__seekveraVoiceAI)return;window.__seekveraVoiceAI=true;
const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;
const LANGS={en:'en-US',ar:'ar-SA',fr:'fr-FR',zh:'zh-CN',es:'es-ES',hi:'hi-IN',pt:'pt-BR',de:'de-DE',ja:'ja-JP',ko:'ko-KR',id:'id-ID',tr:'tr-TR',ru:'ru-RU',ur:'ur-PK',bn:'bn-BD',vi:'vi-VN',it:'it-IT',sw:'sw-KE',th:'th-TH',fa:'fa-IR',pl:'pl-PL',nl:'nl-NL',ms:'ms-MY',fil:'fil-PH',ha:'ha-NG',yo:'yo-NG',ig:'ig-NG',am:'am-ET'};
const FEMALE_HINTS=/aria|jenny|zira|samantha|victoria|karen|moira|tessa|ava|allison|susan|hazel|fiona|serena|veena|heera|lekha|monica|amelie|audrey|julie|celine|hortense|laila|layla|salma|hoda|farah|mariam|maryam|amira|zahra|female|woman/i;
const MALE_HINTS=/david|mark|george|daniel|fred|ralph|bruce|hammad|hamed|majed|maged|male|man/i;
const QUALITY_HINTS=/neural|natural|enhanced|premium|online|google|microsoft|siri/i;
let recognition=null,lastAnswer='',lastLocale='',muted=localStorage.getItem('seekvera_voice_muted')==='1',activeButton=null;
function locale(){const e=document.getElementById('lang');let code=(e?.value||localStorage.getItem('seekvera_lang')||navigator.language||'en').toLowerCase();const label=e?.options?.[e.selectedIndex]?.textContent||'';if(code==='auto'||/auto/i.test(label))return navigator.language||'en-US';code=code.split('_')[0];return LANGS[code]||navigator.language||'en-US'}
function localeForText(t,requested){t=String(t||'');const r=String(requested||'').toLowerCase();if(r&&r!=='auto'&&LANGS[r])return LANGS[r];if(/[\u0600-\u06ff]/.test(t))return 'ar-SA';if(/[\u4e00-\u9fff]/.test(t))return 'zh-CN';if(/[\u3040-\u30ff]/.test(t))return 'ja-JP';if(/[\uac00-\ud7af]/.test(t))return 'ko-KR';if(/[\u0900-\u097f]/.test(t))return 'hi-IN';if(/[\u0980-\u09ff]/.test(t))return 'bn-BD';if(/[\u0400-\u04ff]/.test(t))return 'ru-RU';return locale()}
function pickVoice(l){const vs=speechSynthesis?.getVoices?.()||[];if(!vs.length)return null;const w=String(l||'').toLowerCase(),b=w.split('-')[0];let c=vs.filter(v=>String(v.lang||'').toLowerCase().startsWith(b));if(!c.length)c=vs;const sc=v=>{const n=(v.name||'')+' '+(v.voiceURI||''),vl=String(v.lang||'').toLowerCase();let x=0;if(vl===w)x+=120;else if(vl.startsWith(b))x+=75;if(QUALITY_HINTS.test(n))x+=40;if(FEMALE_HINTS.test(n))x+=48;if(MALE_HINTS.test(n))x-=60;if(v.default)x+=8;return x};return [...c].sort((a,b)=>sc(b)-sc(a))[0]||null}
function stopSpeech(){try{speechSynthesis.cancel()}catch(_){}}
function cleanSpeech(t){return String(t||'').replace(/```[\s\S]*?```/g,' ').replace(/https?:\/\/\S+/g,' ').replace(/[*_#>`~|]/g,' ').replace(/\s+/g,' ').trim()}
function speak(text,l){lastAnswer=String(text||'');lastLocale=localeForText(lastAnswer,l);if(muted||!lastAnswer||!('speechSynthesis'in window))return;stopSpeech();const u=new SpeechSynthesisUtterance(cleanSpeech(lastAnswer));u.lang=lastLocale;const v=pickVoice(lastLocale);if(v)u.voice=v;u.rate=1.02;u.pitch=1.07;u.volume=1;speechSynthesis.speak(u)}
function setMic(on){if(!activeButton)return;activeButton.classList.toggle('listening',on);activeButton.textContent=on?'■':'🎤'}
function start(targetId,button){stopSpeech();if(recognition){try{recognition.stop()}catch(_){ }return}activeButton=button||document.getElementById('aiChatMic')||document.querySelector('.sv-global-compose .mic');if(!SpeechRecognition){const i=document.getElementById(targetId||'aiChatInput');if(i)i.placeholder='Voice recognition is unavailable here — please type your message.';return}const r=new SpeechRecognition();recognition=r;r.lang=locale();r.interimResults=true;r.continuous=false;r.maxAlternatives=1;let final='';r.onstart=()=>setMic(true);r.onresult=e=>{let interim='';for(let x=e.resultIndex;x<e.results.length;x++){const t=e.results[x][0].transcript;if(e.results[x].isFinal)final+=(final?' ':'')+t;else interim+=t}const i=document.getElementById(targetId||'aiChatInput');if(i)i.value=(final||interim).trim()};r.onerror=()=>{};r.onend=()=>{setMic(false);recognition=null;const i=document.getElementById(targetId||'aiChatInput');if(i&&i.value.trim())i.form?.requestSubmit?.()};try{r.start()}catch(_){recognition=null;setMic(false)}}
function toggleMute(btn){muted=!muted;localStorage.setItem('seekvera_voice_muted',muted?'1':'0');document.querySelectorAll('#aiChatSpeaker,.sv-global-speaker').forEach(b=>b.textContent=muted?'🔇':'🔊');if(muted)stopSpeech();else if(lastAnswer)speak(lastAnswer,lastLocale);if(btn)btn.textContent=muted?'🔇':'🔊'}
window.addEventListener('seekvera:voice',e=>start(e.detail?.targetId,e.detail?.button));
window.addEventListener('seekvera:ai-response',e=>speak(e.detail?.text,e.detail?.language));
document.addEventListener('click',e=>{const mic=e.target.closest('#aiChatMic,.sv-global-compose .mic');if(mic){e.preventDefault();const input=mic.closest('form')?.querySelector('input[type="text"],input:not([type])');start(input?.id,mic)}const sp=e.target.closest('#aiChatSpeaker,.sv-global-speaker');if(sp){e.preventDefault();toggleMute(sp)}});
document.addEventListener('DOMContentLoaded',()=>document.querySelectorAll('#aiChatSpeaker,.sv-global-speaker').forEach(b=>b.textContent=muted?'🔇':'🔊'),{once:true});
})();
