import r30 from './worker-r30.js';

const FAST='@cf/meta/llama-3.1-8b-instruct-fast';
const STRONG='@cf/zai-org/glm-4.7-flash';
const BACKUP='@cf/google/gemma-4-26b-a4b-it';
const ALLOWED=new Set(['https://seekveraglobal.com','https://www.seekveraglobal.com','https://seekvera-global.github.io','https://seekvera-main.seekvera-global.workers.dev']);
const ROUTE={travel:'travel.html',property:'property.html',cars:'cars-auto.html',jobs:'jobs.html',shopping:'shopping.html',business:'import-export.html',health:'health.html',restaurants:'restaurants-food.html',connectivity:'connectivity.html',media:'media.html',general:'marketplace.html'};
const clean=(v,n=4000)=>String(v??'').replace(/[\u0000-\u001F\u007F]/g,' ').trim().slice(0,n);
const out=x=>typeof x==='string'?x.trim():typeof x?.response==='string'?x.response.trim():typeof x?.result?.response==='string'?x.result.response.trim():typeof x?.result==='string'?x.result.trim():typeof x?.choices?.[0]?.message?.content==='string'?x.choices[0].message.content.trim():'';
function headers(req){const o=req.headers.get('origin')||'';return{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff',...(ALLOWED.has(o)?{'access-control-allow-origin':o}:{}),'vary':'Origin'}}
function json(req,d,status=200){return new Response(JSON.stringify(d),{status,headers:headers(req)})}
function langName(v,text=''){const raw=String(v||'').trim();const map={en:'English',ar:'Arabic',fr:'French',zh:'Chinese',es:'Spanish',hi:'Hindi',pt:'Portuguese',de:'German',ja:'Japanese',ko:'Korean',id:'Indonesian',tr:'Turkish',ru:'Russian',ur:'Urdu',bn:'Bengali',vi:'Vietnamese',it:'Italian',sw:'Swahili',th:'Thai',fa:'Persian',pl:'Polish',nl:'Dutch',ms:'Malay',fil:'Filipino',ha:'Hausa',yo:'Yoruba',ig:'Igbo',am:'Amharic',he:'Hebrew',el:'Greek',uk:'Ukrainian',ro:'Romanian',cs:'Czech',sk:'Slovak',hu:'Hungarian',sv:'Swedish',no:'Norwegian',da:'Danish',fi:'Finnish',bg:'Bulgarian',hr:'Croatian',sr:'Serbian',sl:'Slovenian',lt:'Lithuanian',lv:'Latvian',et:'Estonian',ca:'Catalan',eu:'Basque',gl:'Galician',is:'Icelandic',sq:'Albanian',mk:'Macedonian',ka:'Georgian',hy:'Armenian',az:'Azerbaijani',kk:'Kazakh',uz:'Uzbek',ky:'Kyrgyz',tg:'Tajik',tk:'Turkmen',ne:'Nepali',si:'Sinhala',ta:'Tamil',te:'Telugu',ml:'Malayalam',mr:'Marathi',gu:'Gujarati',pa:'Punjabi',km:'Khmer',lo:'Lao',my:'Burmese',mn:'Mongolian',zu:'Zulu',af:'Afrikaans',be:'Belarusian',bs:'Bosnian',dz:'Dzongkha',ti:'Tigrinya',fo:'Faroese',kl:'Greenlandic',rw:'Kinyarwanda',sm:'Samoan',to:'Tongan',so:'Somali',ps:'Pashto',dv:'Dhivehi',mt:'Maltese',mg:'Malagasy',ga:'Irish',cy:'Welsh',mi:'Maori',fy:'Frisian',lb:'Luxembourgish',rm:'Romansh',ku:'Kurdish',xh:'Xhosa',st:'Sesotho',tn:'Tswana'};if(raw&&!/^auto$/i.test(raw)){const c=raw.toLowerCase().split(/[-_ ]/)[0];return map[c]||raw}if(/[\u0600-\u06ff]/u.test(text))return'Arabic';if(/[\u4e00-\u9fff]/u.test(text))return'Chinese';if(/[\u3040-\u30ff]/u.test(text))return'Japanese';if(/[\uac00-\ud7af]/u.test(text))return'Korean';if(/[\u0900-\u097f]/u.test(text))return'Hindi';if(/[\u0400-\u04ff]/u.test(text))return'Russian';return'English'}
function category(t){t=String(t||'').toLowerCase();for(const[c,r]of [['connectivity',/esim|wi-?fi|internet|sim card|mobile data|واي فاي|انترنت|شريحة/u],['travel',/hotel|flight|travel|tourism|airport|visa|فندق|سفر|سياحة|طيران/u],['property',/property|house|apartment|land|rent|عقار|بيت|ارض|إيجار/u],['cars',/car|vehicle|spare part|سيارة|قطع غيار/u],['jobs',/job|career|vacancy|وظيفة|عمل/u],['business',/supplier|manufacturer|import|export|rfq|procurement|مورد|مصنع|استيراد|تصدير/u],['health',/hospital|clinic|doctor|pharmacy|مستشفى|طبيب|صيدلية/u],['restaurants',/restaurant|food|cafe|مطعم|قهوة/u],['shopping',/shop|buy|product|shopping|شراء|تسوق/u],['media',/movie|film|cinema|news|music|radio|tv|أخبار|موسيقى|فيلم/u]])if(r.test(t))return c;return'general'}
function simple(t){const s=String(t||'').trim().toLowerCase();if(s.length<=40&&/^(hi|hello|hey|مرحبا|مرحباً|هاي|هلا|اهلا|أهلا|bonjour|salut|hola|ciao|hallo|नमस्ते|你好|こんにちは|안녕)/u.test(s))return true;if(s.length<=70&&/(open|go to|show me|افتح|وديني|اذهب|روح|غيّر|غير|change language|change country)/u.test(s))return true;return false}
function blocked(t){const s=String(t||'').toLowerCase();const rules=[/\b(gun|firearm|rifle|pistol|shotgun|ammunition|grenade|explosive|bomb|taser|switchblade)\b|سلاح|مسدس|بندقية|ذخيرة|قنبلة|متفجر/u,/\b(nude|naked|porn|pornography|sexual services?|escort services?)\b|عاري|إباحي|خدمات جنسية/u,/\b(cocaine|heroin|meth|fentanyl|mdma|lsd|illegal drugs?)\b|كوكايين|هيروين|مخدرات/u,/\b(otp|one.time password|cvv|cvc|bank password|email password|gmail password|password)\b|كلمة المرور|رمز التحقق|الرقم السري/u];return rules.some(r=>r.test(s))}
async function smartAI(req,env,b){const m=clean(b.message??b.prompt);if(!m)return json(req,{ok:false,error:'Message is required'},400);if(blocked(m))return null;if(!env.AI)return null;const hist=Array.isArray(b.history)?b.history.slice(-8).map(x=>({role:x?.role==='assistant'?'assistant':'user',content:clean(x?.content,1000)})).filter(x=>x.content):[];const language=langName(b.language,m),cat=category(hist.map(x=>x.content).join(' ')+' '+m),market=clean(b.country,120)||'Worldwide';const quick=simple(m);const models=[FAST,STRONG,BACKUP];const system=`You are SEEKVERA AI, the conversational assistant inside a worldwide marketplace and super-app. LANGUAGE LOCK: answer fully in ${language}. Selected market: ${market}. Be fast, natural, capable and practical. Understand ordinary conversation, short greetings, follow-up questions and imperfect wording. Help users find the right SEEKVERA section, narrow choices, compare options, plan next steps and explain what to do inside the app. For products, travel, property, cars, jobs, services and business sourcing, ask at most one essential follow-up question when needed. Do not invent live prices, inventory, availability, bookings, company replies or guarantees. Never request passwords, OTP, PIN or CVV. Keep voice answers easy to listen to; default to a concise answer, but give useful detail when the question needs it.`;let response='',model='';for(const md of models){try{const r=await env.AI.run(md,{messages:[{role:'system',content:system},...hist,{role:'user',content:m}],temperature:.18,max_tokens:quick?180:360});response=out(r);if(response){model=md;break}}catch{}}if(!response)return null;return json(req,{ok:true,response,model,language,category:cat,route:ROUTE[cat]||ROUTE.general,countryAction:null,languageAction:null,liveData:false,fastPath:quick?'r31-instant':'r31-fast-context'})}
async function inject(resp){const ct=resp.headers.get('content-type')||'';if(!ct.includes('text/html'))return resp;let text=await resp.text();if(!text.includes('r31-ui-polish.js'))text=text.replace(/<\/body>/i,'<script src="/r31-ui-polish.js?v=20260925-r31b" defer></script></body>');const h=new Headers(resp.headers);h.delete('content-length');h.set('cache-control','no-store');h.set('x-seekvera-release','r31b');return new Response(text,{status:resp.status,statusText:resp.statusText,headers:h})}
export default{async fetch(request,env,ctx){const u=new URL(request.url);if(u.pathname==='/api/ai'&&request.method==='POST'){let b={};try{b=await request.clone().json()}catch{}if(b?.fast===true){const x=await smartAI(request,env,b);if(x)return x}}if(u.pathname==='/api/health'){const r=await r30.fetch(request,env,ctx);let d={};try{d=await r.clone().json()}catch{}return json(request,{...d,r31:true,r31Runtime:'atomic-locale-localized-currency-fast-voice-smart-ai'})}const r=await r30.fetch(request,env,ctx);return u.pathname.startsWith('/api/')?r:inject(r)}};