import baseWorker from './worker.js';

const FAST='@cf/meta/llama-3.1-8b-instruct-fast';
const FALLBACK='@cf/zai-org/glm-4.7-flash';
const ALLOWED_ORIGINS=new Set(['https://seekveraglobal.com','https://www.seekveraglobal.com','https://seekvera-global.github.io','https://seekvera-main.seekvera-global.workers.dev']);
const ROUTE={travel:'travel.html',property:'property.html',cars:'cars-auto.html',jobs:'jobs.html',shopping:'shopping.html',business:'import-export.html',health:'health.html',restaurants:'restaurants-food.html',connectivity:'connectivity.html',media:'media.html',general:'marketplace.html'};

const clean=(v,n=3500)=>String(v??'').replace(/[\u0000-\u001F\u007F]/g,' ').trim().slice(0,n);
const out=x=>typeof x==='string'?x.trim():typeof x?.response==='string'?x.response.trim():typeof x?.result?.response==='string'?x.result.response.trim():typeof x?.result==='string'?x.result.trim():typeof x?.choices?.[0]?.message?.content==='string'?x.choices[0].message.content.trim():'';
function headers(req){const o=req.headers.get('origin')||'';return{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff',...(ALLOWED_ORIGINS.has(o)?{'access-control-allow-origin':o}:{}) ,'vary':'Origin'}}
function json(req,d,status=200){return new Response(JSON.stringify(d),{status,headers:headers(req)})}
function blocked(t){const s=String(t||'').toLowerCase();const rules=[[/\b(gun|firearm|rifle|pistol|shotgun|ammunition|grenade|explosive|bomb|taser|switchblade)\b|سلاح|مسدس|بندقية|ذخيرة|قنبلة|متفجر/u,'weapons_or_explosives'],[/\b(nude|naked|porn|pornography|sexual services?|escort services?)\b|عاري|إباحي|خدمات جنسية/u,'explicit_sexual_content'],[/\b(cocaine|heroin|meth|fentanyl|mdma|lsd|illegal drugs?)\b|كوكايين|هيروين|مخدرات/u,'controlled_drugs'],[/\b(stolen goods?|counterfeit|fake passport|forged id)\b|مسروق|مزور/u,'stolen_counterfeit_or_fake_documents'],[/human trafficking|child sexual|terrorist propaganda|extremist propaganda|اتجار بالبشر|استغلال أطفال|دعاية إرهابية/u,'severe_illegal_content'],[/\b(otp|one.time password|cvv|cvc|bank password|email password|gmail password|password)\b|كلمة المرور|رمز التحقق|الرقم السري/u,'sensitive_credentials'],[/\b(seed phrase|recovery phrase|private key)\b|عبارة الاسترداد|مفتاح خاص/u,'financial_secret']];for(const[r,reason]of rules)if(r.test(s))return reason;return''}
function category(t){t=String(t||'').toLowerCase();for(const[c,r]of [['connectivity',/esim|wi-?fi|internet|sim card|mobile data|واي فاي|انترنت|شريحة/u],['travel',/hotel|flight|travel|tourism|airport|visa|فندق|سفر|سياحة|طيران/u],['property',/property|house|apartment|land|rent|عقار|بيت|ارض|إيجار/u],['cars',/car|vehicle|spare part|سيارة|قطع غيار/u],['jobs',/job|career|vacancy|وظيفة|عمل/u],['business',/supplier|manufacturer|import|export|rfq|procurement|مورد|مصنع|استيراد|تصدير/u],['health',/hospital|clinic|doctor|pharmacy|مستشفى|طبيب|صيدلية/u],['restaurants',/restaurant|food|cafe|مطعم|قهوة/u],['shopping',/shop|buy|product|shopping|شراء|تسوق/u],['media',/movie|film|cinema|news|music|radio|tv|أخبار|موسيقى|فيلم/u]])if(r.test(t))return c;return'general'}
function languageName(v,text=''){const raw=String(v||'').trim();if(raw&&!/^auto$/i.test(raw)){const m={en:'English',ar:'Arabic',fr:'French',zh:'Chinese',es:'Spanish',hi:'Hindi',pt:'Portuguese',de:'German',ja:'Japanese',ko:'Korean',id:'Indonesian',tr:'Turkish',ru:'Russian',ur:'Urdu',bn:'Bengali',vi:'Vietnamese',it:'Italian',sw:'Swahili',th:'Thai',fa:'Persian',pl:'Polish',nl:'Dutch',ms:'Malay',fil:'Filipino',ha:'Hausa',yo:'Yoruba',ig:'Igbo',am:'Amharic',he:'Hebrew',el:'Greek',uk:'Ukrainian'};const c=raw.toLowerCase().split(/[-_ ]/)[0];return m[c]||raw}if(/[\u0600-\u06ff]/u.test(text))return'Arabic';if(/[\u3040-\u30ff]/u.test(text))return'Japanese';if(/[\uac00-\ud7af]/u.test(text))return'Korean';if(/[\u4e00-\u9fff]/u.test(text))return'Chinese';if(/[\u0900-\u097f]/u.test(text))return'Hindi';if(/[\u0400-\u04ff]/u.test(text))return'Russian';return'English'}
async function fastAI(req,env,body){const m=clean(body.message??body.prompt);if(!m)return json(req,{ok:false,error:'Message is required'},400);const reason=blocked(m);if(reason)return json(req,{ok:true,blocked:true,response:'SEEKVERA cannot help buy, sell, advertise, source or promote prohibited or illegal items or services.',reason,provider:'SEEKVERA Safety'});if(!env.AI)return null;const history=Array.isArray(body.history)?body.history.slice(-8).map(x=>({role:x?.role==='assistant'?'assistant':'user',content:clean(x?.content,900)})).filter(x=>x.content):[];const lang=languageName(body.language,m),cat=category(history.map(x=>x.content).join(' ')+' '+m),country=clean(body.country,100)||'Worldwide';const system=`You are SEEKVERA AI, a fast helpful assistant inside a worldwide marketplace and discovery app. LANGUAGE LOCK: reply entirely in ${lang}. Be natural, concise and useful. The selected market is ${country}. Help the customer search, compare and move to the right SEEKVERA category. Do not invent live prices, availability, bookings, jobs, inventory, company replies or guarantees. Never request passwords, OTP, PIN or CVV. Ask only one short follow-up when an essential detail is missing. For voice-friendly replies, use short clear sentences.`;let result=null,model='';for(const md of [FAST,FALLBACK]){try{const r=await env.AI.run(md,{messages:[{role:'system',content:system},...history,{role:'user',content:m}],temperature:.15,max_tokens:320});const text=out(r);if(text){result=text;model=md;break}}catch{}}if(!result)return null;return json(req,{ok:true,response:result,model,language:lang,category:cat,route:ROUTE[cat]||ROUTE.general,countryAction:null,languageAction:null,liveData:false,fastPath:'r30-one-call'})}
async function injectRuntime(resp){const ct=resp.headers.get('content-type')||'';if(!ct.includes('text/html'))return resp;let text=await resp.text();if(!text.includes('r30-runtime.js'))text=text.replace(/<\/body>/i,'<script src="/r30-runtime.js?v=20260925-r30" defer></script></body>');const h=new Headers(resp.headers);h.delete('content-length');h.set('cache-control','no-cache');return new Response(text,{status:resp.status,statusText:resp.statusText,headers:h})}

export default{async fetch(request,env,ctx){const u=new URL(request.url);if(u.pathname==='/api/health'){const r=await baseWorker.fetch(request,env,ctx);let d={};try{d=await r.clone().json()}catch{}return json(request,{...d,r30:true,r30Runtime:'full-language-fast-ai-voice-continuity'})}if(u.pathname==='/api/ai'&&request.method==='POST'){let b={};try{b=await request.clone().json()}catch{}if(b?.fast===true){const r=await fastAI(request,env,b);if(r)return r}}const r=await baseWorker.fetch(request,env,ctx);return u.pathname.startsWith('/api/')?r:injectRuntime(r)}};
