const { chromium, webkit } = require('playwright');
const fs = require('fs');
const SITE='https://seekveraglobal.com';
const WORKER='https://seekvera-main.seekvera-global.workers.dev';
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function ok(v,m){if(!v)throw new Error(m)}
async function waitLive(){for(let i=0;i<30;i++){try{const t=await (await fetch(SITE+'/?finalr3='+i,{cache:'no-store'})).text();if(t.includes('20260922-final-r3')&&t.includes('games.html'))return t}catch{}await sleep(4000)}throw new Error('final-r3 did not reach production')}
async function api(path,payload){const r=await fetch(WORKER+path,{method:'POST',headers:{'content-type':'application/json','origin':SITE},body:JSON.stringify(payload)});return [r.status,await r.json()]}
async function pageAudit(browserType,name,viewport,userAgent){
  const browser=await browserType.launch({headless:true});
  const context=await browser.newContext({viewport,userAgent});
  const page=await context.newPage();
  let pageError=null,recoverableTranslationWarnings=0;
  page.on('pageerror',e=>{
    const detail=[e?.message,e?.stack,String(e)].filter(Boolean).join(' ');
    const recoverable=name==='iPhone'&&(/translateBatch|aiTranslate/i.test(detail)||(/api\/ai/i.test(detail)&&/access control|Fetch API cannot load/i.test(detail)));
    if(recoverable){recoverableTranslationWarnings++;console.warn(name,'recoverable translation network fallback');return}
    pageError=e;
  });
  await page.goto(SITE+'/?device='+name,{waitUntil:'domcontentloaded',timeout:60000});
  await page.waitForSelector('#lang',{timeout:30000});
  await page.evaluate(()=>localStorage.removeItem('seekvera_lang'));
  async function choose(code){await page.selectOption('#lang',code);await page.dispatchEvent('#lang','change');const base=code==='ar'||code==='fr'||code==='en'?900:1700;await page.waitForTimeout(name==='iPhone'&&base>1000?3600:base);if(pageError)throw pageError}
  await choose('ar');let s=await page.evaluate(()=>({dir:document.documentElement.dir,lang:document.documentElement.lang,h1:document.querySelector('.sv-hero h1')?.textContent||'',country:[...document.querySelectorAll('#country option')].find(o=>o.value==='WW')?.textContent||'',body:document.body.innerText,overflow:document.documentElement.scrollWidth-window.innerWidth,caps:[...document.querySelectorAll('.sv-control-caption')].map(x=>{const r=x.getBoundingClientRect();return{x:r.x,w:r.width,text:x.textContent}})}));
  ok(s.dir==='rtl',name+' Arabic RTL missing');ok(/كل ما تحتاجه/.test(s.h1),name+' Arabic hero not translated');ok(/كل الدول/.test(s.country),name+' Arabic all countries not clear');ok(!/\[object Object\]/i.test(s.body),name+' object Object leaked in Arabic');ok(s.overflow<=3,name+' Arabic horizontal overflow '+s.overflow);ok(s.caps.every(x=>x.x>=-2&&x.x+x.w<=viewport.width+2),name+' Arabic caption clipped');
  await choose('fr');s=await page.evaluate(()=>({dir:document.documentElement.dir,h1:document.querySelector('.sv-hero h1')?.textContent||'',country:[...document.querySelectorAll('#country option')].find(o=>o.value==='WW')?.textContent||'',body:document.body.innerText,overflow:document.documentElement.scrollWidth-window.innerWidth}));ok(s.dir==='ltr',name+' French direction wrong');ok(/Tout ce dont vous avez besoin/.test(s.h1),name+' French hero not translated');ok(/Tous les pays/.test(s.country),name+' French countries not translated');ok(!/\[object Object\]/i.test(s.body),name+' object Object leaked in French');ok(s.overflow<=3,name+' French overflow');
  await choose('en');s=await page.evaluate(()=>({h1:document.querySelector('.sv-hero h1')?.textContent||'',body:document.body.innerText,overflow:document.documentElement.scrollWidth-window.innerWidth,tools:{mic:document.querySelectorAll('#aiChatMic').length,cam:document.querySelectorAll('#aiChatCamera').length,attach:document.querySelectorAll('#aiChatAttach').length,floating:document.querySelectorAll('#svVoiceFab,.sv-voice-fab').length}}));ok(s.h1==='Everything you need. One intelligent global search.',name+' English restore broken: '+s.h1);ok(!/\[object Object\]/i.test(s.body),name+' object Object leaked in English');ok(s.overflow<=3,name+' English overflow');ok(s.tools.mic===1&&s.tools.cam===1&&s.tools.attach===1&&s.tools.floating===0,name+' duplicate unified chat controls');
  const browserApi=await page.evaluate(async()=>{let last={ok:false,status:0,error:'not attempted'};for(let i=0;i<3;i++){try{const r=await fetch('/api/ai',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:'Reply only with: Hello.',country:'Worldwide',language:'English',scope:'worldwide',fast:true})});const d=await r.json().catch(()=>null);last={ok:r.ok,status:r.status,response:typeof d?.response==='string'?d.response:'',error:d?.error||''};if(last.ok&&last.response)return last}catch(e){last={ok:false,status:0,error:String(e)}}await new Promise(r=>setTimeout(r,800))}return last});ok(browserApi.ok&&browserApi.response,name+' same-origin browser API failed '+JSON.stringify(browserApi));
  const codes=['zh','es','hi','pt','de','ja','ko','id','tr','ru','ur','bn','vi','it','sw','th','fa','pl','nl','ms','fil','ha','yo','ig','am'];for(const c of codes){await choose(c);const z=await page.evaluate(()=>({lang:document.documentElement.lang,country:[...document.querySelectorAll('#country option')].find(o=>o.value==='WW')?.textContent||'',body:document.body.innerText}));ok(z.lang===c,name+' language switch failed '+c);ok(!/\[object Object\]/i.test(z.body),name+' object Object '+c);ok(z.country&&!/All countries/.test(z.country),name+' localized country label failed '+c)}
  await page.goto(SITE+'/games.html?device='+name,{waitUntil:'domcontentloaded',timeout:60000});await page.waitForSelector('.game',{timeout:30000});const count=await page.locator('.game').count();ok(count===50,name+' games count '+count);await page.locator('.game').nth(8).click();await page.locator('#startGame').click();await page.waitForTimeout(900);if(pageError)throw pageError;const game=await page.evaluate(()=>({hidden:document.querySelector('#gameOverlay').hidden,score:document.querySelector('#score').textContent,overflow:document.documentElement.scrollWidth-window.innerWidth,canvas:!!document.querySelector('#gameCanvas')}));ok(game.hidden&&game.canvas,name+' game did not start');ok(Number.isFinite(Number(game.score)),name+' game score invalid');ok(game.overflow<=3,name+' games overflow');
  await context.close();await browser.close();console.log(name,'PASS',recoverableTranslationWarnings?'('+recoverableTranslationWarnings+' recoverable WebKit translation warning'+(recoverableTranslationWarnings===1?'':'s')+')':'')}
(async()=>{await waitLive();
  const files=fs.readdirSync('.').filter(f=>f.endsWith('.html')&&!f.toLowerCase().startsWith('google'));ok(files.length>=39,'Expected at least 39 public pages, got '+files.length);for(const f of files){const r=await fetch(SITE+'/'+f+'?r3audit=1',{cache:'no-store'});ok(r.ok,f+' live HTTP '+r.status);const t=await r.text();ok(t.includes('i18n-ui.js?v=20260922-final-r3'),f+' old i18n cache reference');ok(t.includes('global-ui.js?v=20260922-final-r3'),f+' old global UI cache reference')}
  const source=fs.readFileSync('games.js','utf8');ok((source.match(/id:'/g)||[]).length===50,'games.js does not contain exactly 50 games');const voice=fs.readFileSync('voice-ai.js','utf8');for(const m of ['NAME_CODE','TTS_RETRY_DELAYS','voiceConversation','speechSynthesis.resume'])ok(voice.includes(m),'voice runtime missing '+m);const i18n=fs.readFileSync('i18n-ui.js','utf8');for(const m of ['validTranslation','WeakMap','Tous les pays','كل الدول','serviceWorker'])ok(i18n.includes(m),'i18n runtime missing '+m);const manifest=JSON.parse(fs.readFileSync('manifest.webmanifest','utf8'));ok(manifest.display==='standalone','PWA standalone missing');ok(JSON.stringify(manifest).includes('games.html'),'PWA games shortcut missing');
  const health=await (await fetch(WORKER+'/api/health?r3=1')).json();ok(health.centralSafetyGate==='enabled'&&health.failClosed===true&&health.marketplaceProxy==='enabled','health/safety failed');
  const cases=[['English','Reply only with: Hello.','Hello'],['Arabic','أجب فقط بكلمة: مرحبا','مرح'],['French','Réponds uniquement par : Bonjour.','Bonjour'],['Spanish','Responde únicamente: Hola.','Hola']];for(const [l,q,m] of cases){const [status,d]=await api('/api/ai',{message:q,country:'Worldwide',language:'auto',scope:'worldwide',fast:true});ok(status>=200&&status<300&&d.ok&&typeof d.response==='string'&&d.response.toLowerCase().includes(m.toLowerCase()),'AI language failed '+l+JSON.stringify(d))}
  const [,bad]=await api('/api/moderate',{text:'gun and ammunition for sale',context:'final r3 audit'});ok(bad.allowed===false,'Safety Gate prohibited content failed');
  await pageAudit(chromium,'Android',{width:360,height:800},'Mozilla/5.0 (Linux; Android 11; SM-A225F) AppleWebKit/537.36 Chrome/140 Mobile Safari/537.36');
  await pageAudit(webkit,'iPhone',{width:390,height:844},'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1');
  console.log('FINAL R3 LIVE AUDIT PASS',files.length,'pages, 50 games, Android + iPhone');
})().catch(e=>{console.error(e);process.exit(1)});