import{chromium}from'playwright';import assert from'node:assert/strict';
const b=await chromium.launch({headless:true});
const p=await b.newPage({viewport:{width:390,height:844},locale:'en-US',userAgent:'Mozilla/5.0 (Linux; Android 11; SM-A225F) AppleWebKit/537.36 Chrome/140 Mobile Safari/537.36'});
const errs=[];p.on('pageerror',e=>errs.push(String(e)));
await p.goto('https://seekveraglobal.com/?r121b='+Date.now(),{waitUntil:'domcontentloaded',timeout:60000});
await p.waitForFunction(()=>window.SEEKVERA_VOICE_AI&&window.SEEKVERA_R31?.submitAI&&window.SEEKVERA_R24_CONTROLLER,null,{timeout:25000});
const hybrid=await p.evaluate(()=>window.SEEKVERA_VOICE_AI.chooseHybridTranscript('Halið á að leita að vinnu',.97,{text:'دوريني على شغل',language:'ar',engine:'server-whisper-auto'}));
assert.match(hybrid.text,/[\u0600-\u06ff]/u);assert.equal(hybrid.language,'ar');
const n=await p.locator('#aiMessages .ai-msg.bot:not(.thinking)').count(),t=Date.now();
await p.fill('#aiChatInput','دوريني على شغل');await p.locator('#aiChatForm').evaluate(f=>f.requestSubmit());
await p.waitForFunction(x=>document.querySelectorAll('#aiMessages .ai-msg.bot:not(.thinking)').length>x,n,{timeout:4000});
const reply=await p.locator('#aiMessages .ai-msg.bot:not(.thinking)').last().innerText();assert.match(reply,/[\u0600-\u06ff]/u);
await p.waitForURL(/jobs\.html/,{timeout:4000});const ms=Date.now()-t;assert(ms<4000,{ms,reply,url:p.url()});
assert.equal(errs.length,0,errs.join('\n'));console.log('ANDROID_JOB_PASS',JSON.stringify({ms,reply,url:p.url(),hybrid}));
await p.goto('https://seekveraglobal.com/?r121bc='+Date.now(),{waitUntil:'domcontentloaded',timeout:60000});
await p.waitForFunction(()=>window.SEEKVERA_R24_CONTROLLER&&window.SEEKVERA_LOCALE_R15&&document.querySelector('#country'),null,{timeout:25000});
const c=await p.evaluate(()=>window.SEEKVERA_R24_CONTROLLER.detectControls('حوليني على تركيا'));assert.equal(c.country,'TR');
await p.evaluate(c=>window.SEEKVERA_R24_CONTROLLER.applyControls(c),c);
await p.waitForFunction(()=>document.querySelector('#country')?.value==='TR',{timeout:5000});await p.waitForTimeout(1200);
const cs=await p.evaluate(()=>({country:document.querySelector('#country')?.value,lang:document.querySelector('#lang')?.value,htmlLang:document.documentElement.lang,currency:document.querySelector('#currency')?.value}));
assert.equal(cs.country,'TR');assert.equal(cs.currency,'TRY');assert.equal(cs.lang,'tr');assert.equal(cs.htmlLang,'tr');
console.log('COUNTRY_ATOMIC_PASS',JSON.stringify(cs));await b.close();
