from pathlib import Path
p=Path('r24-ai-controller.js')
s=p.read_text(encoding='utf-8')
if 'pollinations-browser-private-backup' not in s:
    old="const nativeFetch=window.fetch.bind(window);\nwindow.fetch=async function(input,init){let controls={};let raw=init?.body;try{if(raw==null&&typeof Request!=='undefined'&&input instanceof Request)raw=await input.clone().text();const b=typeof raw==='string'?JSON.parse(raw):{};controls=detectControls(b?.message||b?.prompt||'')}catch{}const res=await nativeFetch(input,init);if(!sameApi(input))return res;let data=null;try{data=await res.clone().json()}catch{return res}const server={country:data?.countryAction?.code||'',language:data?.languageAction?.code||''};const merged={country:String(server.country||controls.country||'').toUpperCase(),language:String(server.language||controls.language||'').toLowerCase()};if(merged.country||merged.language)applyControls(merged);if(!merged.country&&!merged.language)return res;const payload={...data,...actionPayload(merged),controlVersion:VERSION};return new Response(JSON.stringify(payload),{status:res.status,headers:new Headers(res.headers)})};"
    new="""const nativeFetch=window.fetch.bind(window);
async function browserAiBackup(body={},base={}){const message=String(body?.message||body?.prompt||'').trim();if(!message||base?.blocked||base?.reviewRequired)return null;const history=Array.isArray(body?.history)?body.history.slice(-8).map(x=>String(x?.role||'user')+': '+String(x?.content||'')).join('\\n'):'';const prompt=['You are SEEKVERA AI, the helpful assistant inside a worldwide discovery and marketplace app.','Understand the latest user message in any language and reply naturally in that SAME language and script unless the user explicitly requests another language.','Be concise, practical and conversational. Help the user find the correct SEEKVERA section when relevant. Never invent live prices, availability, bookings, jobs, company replies or guarantees. Never request passwords, OTP, PIN or CVV.','Selected market: '+String(body?.country||'Worldwide')+'.','Conversation context: '+history.slice(-1800),'Latest user message: '+message.slice(0,1200)].join('\\n');const u='https://text.pollinations.ai/'+encodeURIComponent(prompt)+'?model=openai&private=true';const ctl=new AbortController(),to=setTimeout(()=>ctl.abort(),16000);try{const r=await nativeFetch(u,{method:'GET',headers:{accept:'text/plain'},signal:ctl.signal,cache:'no-store'});if(!r.ok)return null;const text=String(await r.text()).trim().slice(0,5000);if(!text)return null;return{...base,ok:true,response:text,model:'pollinations-browser-private-backup',degraded:false,providerAvailable:true,retryable:false,browserBackup:true}}catch{return null}finally{clearTimeout(to)}}
window.fetch=async function(input,init){let controls={},body={};let raw=init?.body;try{if(raw==null&&typeof Request!=='undefined'&&input instanceof Request)raw=await input.clone().text();body=typeof raw==='string'?JSON.parse(raw):{};controls=detectControls(body?.message||body?.prompt||'')}catch{}const res=await nativeFetch(input,init);if(!sameApi(input))return res;let data=null;try{data=await res.clone().json()}catch{return res}let usedBackup=false;if(!data?.blocked&&!data?.reviewRequired&&(res.status===503||data?.degraded===true||data?.model==='seekvera-local-router')){const backup=await browserAiBackup(body,data);if(backup){data=backup;usedBackup=true}}const server={country:data?.countryAction?.code||'',language:data?.languageAction?.code||''};const merged={country:String(server.country||controls.country||'').toUpperCase(),language:String(server.language||controls.language||'').toLowerCase()};if(merged.country||merged.language)applyControls(merged);if(!usedBackup&&!merged.country&&!merged.language)return res;const payload={...data,...actionPayload(merged),controlVersion:VERSION};const headers=new Headers(res.headers);headers.set('content-type','application/json; charset=utf-8');headers.set('cache-control','no-store');if(usedBackup)headers.set('x-seekvera-ai-mode','browser-private-backup');return new Response(JSON.stringify(payload),{status:usedBackup?200:res.status,headers})};"""
    if old not in s: raise SystemExit('R26 fetch wrapper anchor missing')
    s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')
s=p.read_text(encoding='utf-8')
assert 'pollinations-browser-private-backup' in s
assert "res.status===503||data?.degraded===true||data?.model==='seekvera-local-router'" in s
assert "if(!message||base?.blocked||base?.reviewRequired)return null" in s
print('R26 browser AI resilience patch PASS')
