from pathlib import Path


def replace_once(path, old, new, label):
    p=Path(path); s=p.read_text(encoding='utf-8')
    if new in s:
        print(label,'already applied'); return
    if old not in s:
        raise SystemExit(f'{label} anchor not found')
    p.write_text(s.replace(old,new,1),encoding='utf-8')
    print(label,'applied')

# 1) Home AI: make the correct app route available immediately, shorten the wait,
# and prevent visibly repeating the same generic answer.
p=Path('superapp.js'); s=p.read_text(encoding='utf-8')
anchor="function chatHistory(){const msgs=$('#aiMessages');if(!msgs)return[];return[...msgs.querySelectorAll('.ai-msg')].filter(x=>!x.classList.contains('thinking')).slice(-12).map(x=>({role:x.classList.contains('user')?'user':'assistant',content:clean(x.textContent,1800)})).filter(x=>x.content)}"
helper=anchor+"\nfunction directRouteLabel(cat){const ar=(document.documentElement.lang||lang()).toLowerCase().startsWith('ar');const m={jobs:ar?'افتح الوظائف الآن ←':'Open jobs now →',travel:ar?'افتح السفر والفنادق الآن ←':'Open travel & hotels now →',property:ar?'افتح العقارات الآن ←':'Open property now →',cars:ar?'افتح السيارات الآن ←':'Open cars now →',shopping:ar?'افتح التسوق الآن ←':'Open shopping now →',business:ar?'افتح الأعمال والموردين الآن ←':'Open business & suppliers now →',connectivity:ar?'افتح الإنترنت والاتصال الآن ←':'Open connectivity now →',health:ar?'افتح الصحة الآن ←':'Open health now →',restaurant:ar?'افتح المطاعم الآن ←':'Open restaurants now →'};return m[cat]||(ar?'افتح القسم المناسب الآن ←':'Open the right section now →')}\nfunction addDirectRoute(cat,q,after){const msgs=$('#aiMessages');if(!msgs)return null;msgs.querySelectorAll('.sv-ai-direct-route').forEach(x=>x.remove());const a=document.createElement('a');a.className='sv-ai-direct-route';a.href=routeFor(cat)+'?q='+encodeURIComponent(q)+'&country='+encodeURIComponent($('#country')?.value||localStorage.getItem('seekvera_country')||'WW');a.textContent=directRouteLabel(cat);a.style.cssText='display:block;margin:7px 12px 10px;padding:11px 13px;border-radius:12px;background:#0f9f6e;color:#fff;font-weight:900;text-decoration:none;text-align:center';if(after?.parentNode)after.insertAdjacentElement('afterend',a);else msgs.appendChild(a);msgs.scrollTop=msgs.scrollHeight;return a}\nfunction sameReply(a,b){const n=x=>String(x||'').toLowerCase().replace(/[^\\p{L}\\p{N}]+/gu,' ').trim();const x=n(a),y=n(b);return !!x&&!!y&&(x===y||(x.length>45&&y.includes(x.slice(0,45)))||(y.length>45&&x.includes(y.slice(0,45))))}\nfunction localJobGuide(){const ar=(document.documentElement.lang||lang()).toLowerCase().startsWith('ar');return ar?'أكيد. وصّلتك لقسم الوظائف مباشرة. قل لي البلد أو المدينة ونوع الشغل الذي تريده، وأنا أضيّق لك النتائج بدل ما أعيد نفس الكلام.':'Absolutely. I’ve put the Jobs section right below this reply. Tell me the country/city and the kind of job you want, and I’ll narrow it down instead of repeating the same answer.'}"
if 'function addDirectRoute(cat,q,after)' not in s:
    if anchor not in s: raise SystemExit('superapp chatHistory anchor missing')
    s=s.replace(anchor,helper,1)
old="async function askAI(q){q=clean(q,1800);if(!q)return;const history=chatHistory(),ans=$('#aiAnswer'),actions=$('#aiActions');if(actions)actions.innerHTML='';chatAdd('user',q);const pending=chatAdd('bot',tr('thinking'),'thinking');const cat=categoryFor(q),country=selectedCountryName();const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),22000);try{const r=await fetch(api('/api/ai'),{method:'POST',headers:{'content-type':'application/json'},signal:controller.signal,body:JSON.stringify({message:q,country,language:languageName(),scope:scope(),fast:true,history})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.response)throw new Error(d.error||'AI unavailable');if(d?.countryAction?.type==='set-country'){const cc=String(d.countryAction.code||'').toUpperCase(),ce=$('#country');if(ce&&[...ce.options].some(o=>o.value===cc)){ce.value=cc;ce.dispatchEvent(new Event('change',{bubbles:true}))}}if(pending){pending.textContent=d.response;pending.classList.remove('thinking')}if(ans)ans.textContent=d.response;if(actions)actions.innerHTML=actionLinks(d.category||cat,q);window.dispatchEvent(new CustomEvent('seekvera:ai-response',{detail:{text:d.response,language:d.language||lang()}}))}catch(e){const msg=e?.name==='AbortError'?'SEEKVERA AI is taking too long. Please try again.':'SEEKVERA AI is temporarily unavailable. Please try again.';if(pending){pending.textContent=msg;pending.classList.remove('thinking')}if(ans)ans.textContent=msg;if(actions)actions.innerHTML=actionLinks(cat,q)}finally{clearTimeout(timer)}}"
new="async function askAI(q){q=clean(q,1800);if(!q)return;const history=chatHistory(),ans=$('#aiAnswer'),actions=$('#aiActions');chatAdd('user',q);const pending=chatAdd('bot',tr('thinking'),'thinking');const cat=categoryFor(q),country=selectedCountryName();if(actions){actions.innerHTML=actionLinks(cat,q);actions.hidden=false}addDirectRoute(cat,q,pending);const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{const r=await fetch(api('/api/ai'),{method:'POST',headers:{'content-type':'application/json'},signal:controller.signal,body:JSON.stringify({message:q,country,language:languageName(),scope:scope(),fast:true,history})});const d=await r.json().catch(()=>({}));if(!r.ok||!d.response)throw new Error(d.error||'AI unavailable');if(d?.countryAction?.type==='set-country'){const cc=String(d.countryAction.code||'').toUpperCase(),ce=$('#country');if(ce&&[...ce.options].some(o=>o.value===cc)){ce.value=cc;ce.dispatchEvent(new Event('change',{bubbles:true}))}}let reply=String(d.response||'').trim();const previous=[...history].reverse().find(x=>x.role==='assistant')?.content||'';if(sameReply(reply,previous)&&((d.category||cat)==='jobs'||cat==='jobs'))reply=localJobGuide();if(pending){pending.textContent=reply;pending.classList.remove('thinking')}if(ans)ans.textContent=reply;const finalCat=d.category||cat;if(actions){actions.innerHTML=actionLinks(finalCat,q);actions.hidden=false}addDirectRoute(finalCat,q,pending);window.dispatchEvent(new CustomEvent('seekvera:ai-response',{detail:{text:reply,language:d.language||lang(),route:d.route||routeFor(finalCat),category:finalCat}}))}catch(e){let msg;if(cat==='jobs')msg=localJobGuide();else msg=e?.name==='AbortError'?'I’m still here — use the direct section button below while I narrow the result.':'Use the direct section button below and try one more detail.';if(pending){pending.textContent=msg;pending.classList.remove('thinking')}if(ans)ans.textContent=msg;if(actions){actions.innerHTML=actionLinks(cat,q);actions.hidden=false}addDirectRoute(cat,q,pending);window.dispatchEvent(new CustomEvent('seekvera:ai-response',{detail:{text:msg,language:lang(),route:routeFor(cat),category:cat}}))}finally{clearTimeout(timer)}}"
if new not in s:
    if old not in s: raise SystemExit('superapp askAI anchor missing')
    s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')
print('superapp fast routing + de-dupe applied')

# 2) Voice: remember that a request originated from the microphone until the AI reply arrives.
p=Path('voice-ai.js'); s=p.read_text(encoding='utf-8')
old="let recognition=null,lastAnswer='',lastLocale='',muted=localStorage.getItem('seekvera_voice_muted')==='1',activeButton=null,voiceConversation=false,speakToken=0,recording=false"
new="let recognition=null,lastAnswer='',lastLocale='',muted=localStorage.getItem('seekvera_voice_muted')==='1',activeButton=null,voiceConversation=false,voiceReplyDeadline=0,speakToken=0,recording=false"
if old in s:s=s.replace(old,new,1)
elif new not in s:raise SystemExit('voice state anchor missing')
old="function enableVoiceConversation(){voiceConversation=true;muted=false;localStorage.setItem('seekvera_voice_muted','0');updateSpeakerButtons();unlockTTS()}"
new="function enableVoiceConversation(){voiceConversation=true;voiceReplyDeadline=Date.now()+45000;muted=false;localStorage.setItem('seekvera_voice_muted','0');updateSpeakerButtons();unlockTTS()}"
if old in s:s=s.replace(old,new,1)
elif new not in s:raise SystemExit('voice enable anchor missing')
s=s.replace("if(i){i.value=String(d.text).trim();i.placeholder='Message SEEKVERA AI…';if(i.value)setTimeout(()=>i.form?.requestSubmit?.(),80)}","if(i){i.value=String(d.text).trim();i.placeholder='Message SEEKVERA AI…';if(i.value){voiceReplyDeadline=Date.now()+45000;setTimeout(()=>i.form?.requestSubmit?.(),45)}}",1)
s=s.replace("if(q&&!hadError)setTimeout(()=>i.form?.requestSubmit?.(),90);else if(!q)voiceConversation=false","if(q&&!hadError){voiceReplyDeadline=Date.now()+45000;setTimeout(()=>i.form?.requestSubmit?.(),45)}else if(!q)voiceConversation=false",1)
old="window.addEventListener('seekvera:ai-response',e=>speak(e.detail?.text,e.detail?.language,voiceConversation));"
new="window.addEventListener('seekvera:ai-response',e=>{const auto=voiceConversation||Date.now()<voiceReplyDeadline;if(auto)voiceReplyDeadline=0;speak(e.detail?.text,e.detail?.language,auto)});\nwindow.SEEKVERA_VOICE_AI={speak,start,markVoiceReply:()=>{voiceConversation=true;voiceReplyDeadline=Date.now()+45000;muted=false;localStorage.setItem('seekvera_voice_muted','0');updateSpeakerButtons();unlockTTS()},isVoiceReplyPending:()=>voiceConversation||Date.now()<voiceReplyDeadline};"
if old in s:s=s.replace(old,new,1)
elif 'window.SEEKVERA_VOICE_AI=' not in s:raise SystemExit('voice response anchor missing')
p.write_text(s,encoding='utf-8')
print('voice reply persistence applied')

# 3) Server AI: reduce latency budgets and explicitly prohibit repetitive replies.
p=Path('worker-r31.js'); s=p.read_text(encoding='utf-8')
s=s.replace("const second=(async()=>{await sleep(900);return runModel(env,LIGHT,messages,220)})();const timeout=(async()=>{await sleep(4800);throw Error('ai latency budget')})();try{return await Promise.race([Promise.any([first,second]),timeout])}catch{try{return await Promise.race([runModel(env,STRONG,messages,220),(async()=>{await sleep(1800);throw Error('fallback latency budget')})()])}","const second=(async()=>{await sleep(220);return runModel(env,LIGHT,messages,220)})();const timeout=(async()=>{await sleep(2200);throw Error('ai latency budget')})();try{return await Promise.race([Promise.any([first,second]),timeout])}catch{try{return await Promise.race([runModel(env,STRONG,messages,220),(async()=>{await sleep(850);throw Error('fallback latency budget')})()])}",1)
s=s.replace("AbortSignal.timeout(7500)","AbortSignal.timeout(2200)",1)
old="Understand follow-ups and imperfect wording. Ask at most one essential question. Never invent live price, inventory, availability, booking, job or company reply."
new="Understand follow-ups and imperfect wording. Never repeat or paraphrase the previous assistant reply. For a clear category request, tell the user the direct section button is available and move the conversation forward. For jobs, ask at most one missing detail such as location or job type. Ask at most one essential question. Never invent live price, inventory, availability, booking, job or company reply."
if old in s:s=s.replace(old,new,1)
elif new not in s:raise SystemExit('worker prompt anchor missing')
# Make the no-provider job fallback useful instead of the same generic sentence.
old="function fallbackGuide(language,cat){const routeName={travel:'travel',property:'property',cars:'cars',jobs:'jobs',shopping:'shopping',business:'business sourcing',health:'health',restaurants:'restaurants',connectivity:'connectivity',media:'media',general:'marketplace'}[cat]||'marketplace';if(language==='Arabic')return`أقدر أساعدك مباشرة. سأبدأ من قسم ${routeName==='marketplace'?'السوق':routeName}، وأحتاج فقط أهم تفصيل ناقص مثل المدينة أو الميزانية أو التاريخ حتى أضيّق لك الخيارات بدون اختلاق أسعار أو توافر.`;return`I can help directly. I’ll start with the ${routeName} section; give me the one key missing detail such as city, budget or date and I’ll narrow the options without inventing live prices or availability.`}"
new="function fallbackGuide(language,cat){if(cat==='jobs'){if(language==='Arabic')return'أكيد. افتح قسم الوظائف من الزر المباشر تحت الرد، وقل لي البلد أو المدينة ونوع الشغل الذي تريده حتى أضيّق لك النتائج.';return'Absolutely. Open the Jobs section from the direct button below, then tell me the country/city and job type so I can narrow the results.'}const routeName={travel:'travel',property:'property',cars:'cars',shopping:'shopping',business:'business sourcing',health:'health',restaurants:'restaurants',connectivity:'connectivity',media:'media',general:'marketplace'}[cat]||'marketplace';if(language==='Arabic')return`تمام. زر القسم المناسب موجود مباشرة تحت الرد. أعطني أهم تفصيل ناقص فقط حتى أنتقل للخطوة التالية بدل تكرار الكلام.`;return`Done. The direct section button is right below the reply. Give me only the one missing detail and I’ll move to the next step instead of repeating the same guidance.`}"
if old in s:s=s.replace(old,new,1)
elif new not in s:raise SystemExit('worker fallback anchor missing')
p.write_text(s,encoding='utf-8')
print('worker latency + conversation prompt applied')
