from pathlib import Path

# This runs after r61_country_chat_server_voice.py, so replace its server-player functions.
p=Path('voice-ai.js');s=p.read_text(encoding='utf-8')
start=s.find('async function serverSpeak(');end=s.find('\nfunction nativeSpeak',start)
if start<0 or end<0:raise SystemExit('R61 serverSpeak boundary missing')
server=r'''async function serverSpeak(text,loc,token,emitEnd=true){const spoken=cleanSpeech(text).slice(0,190);if(!spoken||token!==speakToken||muted)return false;try{prepareServerAudio();const ctl=new AbortController(),to=setTimeout(()=>ctl.abort(),10000),r=await fetch(apiBase()+'/api/tts',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text:spoken,language:String(loc||'auto')}),signal:ctl.signal,cache:'no-store'}).finally(()=>clearTimeout(to));if(!r.ok)return false;const buf=await r.arrayBuffer();if(!buf.byteLength||token!==speakToken)return false;if(prepareServerAudio()&&serverAudioCtx){try{const audio=await serverAudioCtx.decodeAudioData(buf.slice(0));if(token!==speakToken)return false;return await new Promise(resolve=>{serverAudioSource=serverAudioCtx.createBufferSource();serverAudioSource.buffer=audio;serverAudioSource.connect(serverAudioCtx.destination);serverAudioSource.onended=()=>{serverAudioSource=null;if(token===speakToken&&emitEnd){voiceConversation=false;window.dispatchEvent(new CustomEvent('seekvera:tts-end',{detail:{language:loc,engine:'server'}}))}resolve(true)};window.dispatchEvent(new CustomEvent('seekvera:tts-start',{detail:{language:loc,engine:'server'}}));serverAudioSource.start(0)})}catch(_){}}
const blob=new Blob([buf],{type:r.headers.get('content-type')||'audio/mpeg'});serverAudioUrl=URL.createObjectURL(blob);serverAudioEl=new Audio(serverAudioUrl);serverAudioEl.preload='auto';return await new Promise(async resolve=>{let began=false;serverAudioEl.onplaying=()=>{began=true;window.dispatchEvent(new CustomEvent('seekvera:tts-start',{detail:{language:loc,engine:'server-audio'}}))};serverAudioEl.onended=()=>{if(token===speakToken&&emitEnd){voiceConversation=false;window.dispatchEvent(new CustomEvent('seekvera:tts-end',{detail:{language:loc,engine:'server-audio'}}))}stopServerAudio();resolve(true)};serverAudioEl.onerror=()=>{stopServerAudio();resolve(false)};try{await serverAudioEl.play()}catch(_){resolve(false)}})}catch(_){return false}}'''
s=s[:start]+server+s[end:]
start=s.find('function speak(text,l,force=false){');end=s.find('\nfunction setMic',start)
if start<0 or end<0:raise SystemExit('R61 speak boundary missing')
speak=r'''function speak(text,l,force=false){lastAnswer=typeof text==='string'?text:'';lastLocale=localeForText(lastAnswer,l);const chunks=splitSpeech(lastAnswer);if(force){muted=false;localStorage.setItem('seekvera_voice_muted','0');localStorage.setItem('seekvera_voice_mode','1');updateSpeakerButtons()}if(muted||!chunks.length){if(force)voiceConversation=false;return}const token=++speakToken,android=/Android/i.test(navigator.userAgent);if(android){(async()=>{let any=false;for(let i=0;i<chunks.length;i++){if(token!==speakToken||muted)return;const ok=await serverSpeak(chunks[i],lastLocale,token,false);if(!ok){if(!any&&token===speakToken&&!muted)nativeSpeak(chunks,token);return}any=true}if(any&&token===speakToken){voiceConversation=false;window.dispatchEvent(new CustomEvent('seekvera:tts-end',{detail:{language:lastLocale,engine:'server'}}))}})();return}if(!nativeSpeak(chunks,token))serverSpeak(lastAnswer,lastLocale,token,true)}'''
s=s[:start]+speak+s[end:]
p.write_text(s,encoding='utf-8')

# Replace the R61 serverTTS with a three-tier service:
# Cloudflare hosted -> Inworld multilingual -> no-key MP3 fallback.
p=Path('worker-r31.js');s=p.read_text(encoding='utf-8')
start=s.find('async function serverTTS(');end=s.find('\nasync function inject',start)
if start<0 or end<0:raise SystemExit('R61 worker serverTTS boundary missing')
new=r'''const GOOGLE_TTS_UNSUPPORTED=new Set(['fa','yo','ig','sl','mk','ka','hy','az','kk','uz','ky','tg','tk','lo','mn','zu','be','dz','ti','fo','kl','rw','sm','to','so','ps','dv','mt','mg','ga','mi','fy','lb','rm','ku','xh','st','tn']);
const GOOGLE_TTS_FALLBACK={fa:'ar',yo:'ha',ig:'en',sl:'hr',mk:'bg',ka:'ru',hy:'ru',az:'tr',kk:'ru',uz:'tr',ky:'ru',tg:'ru',tk:'tr',lo:'th',mn:'ru',zu:'af',be:'ru',dz:'hi',ti:'am',fo:'da',kl:'da',rw:'sw',sm:'en',to:'en',so:'sw',ps:'ur',dv:'hi',mt:'it',mg:'fr',ga:'en',mi:'en',fy:'nl',lb:'de',rm:'de',ku:'tr',xh:'af',st:'af',tn:'af'};
async function serverTTS(req,env){if(req.method!=='POST')return json(req,{ok:false,error:'POST required'},405);let b={};try{b=await req.json()}catch{}const text=clean(b.text,190),lang=inputLangCode(b.language||b.lang||'en');if(!text)return json(req,{ok:false,error:'text required'},400);const audioResp=async(r,engine,target)=>{if(!(r instanceof Response)||!r.ok)return null;const h=new Headers(r.headers);h.set('content-type',h.get('content-type')||'audio/mpeg');h.set('cache-control','no-store');const o=req.headers.get('origin')||'';if(ALLOWED.has(o))h.set('access-control-allow-origin',o);h.set('vary','Origin');h.set('x-seekvera-tts',engine);h.set('x-seekvera-tts-language',target||lang);return new Response(r.body,{status:200,headers:h})};if(env.AI){const melo=new Set(['en','es','fr','zh','ja','ko']);if(melo.has(lang)){try{const r=await env.AI.run('@cf/myshell-ai/melotts',{prompt:text,lang},{returnRawResponse:true}),a=await audioResp(r,'cloudflare-melo',lang);if(a)return a}catch{}}try{const x=await env.AI.run('inworld/tts-2',{output_format:'mp3',temperature:.8,text,timestamp_type:'none',voice_id:'Olivia',apply_text_normalization:true}),url=x?.result?.audio||x?.audio;if(url&&/^https:\/\//i.test(url)){const r=await fetch(url),a=await audioResp(r,'inworld',lang);if(a)return a}}catch{}}
const target=GOOGLE_TTS_FALLBACK[lang]||lang;try{const u='https://translate.google.com/translate_tts?ie=UTF-8&client=tw-ob&tl='+encodeURIComponent(target)+'&q='+encodeURIComponent(text),r=await fetch(u,{headers:{'user-agent':'Mozilla/5.0','accept':'audio/mpeg,*/*'}}),a=await audioResp(r,'multilingual-mp3-fallback',target);if(a)return a}catch{}return json(req,{ok:false,error:'voice generation unavailable',language:lang},503)}'''
s=s[:start]+new+s[end:]
p.write_text(s,encoding='utf-8')
print('R61C resilient multilingual audio fallback patched')
