from pathlib import Path
import re

VER='20260926-r76-complete-global-final'

# Browser AI must survive Cloudflare Worker quota/rate-limit responses. Keep safety client-side,
# try a privacy-mode browser model, then use a same-language deterministic emergency reply.
p=Path('r24-ai-controller.js')
s=p.read_text(encoding='utf-8')
start=s.index('const nativeFetch=window.fetch.bind(window);')
end=s.index('function bindSpeaker(){',start)
block=r'''const nativeFetch=window.fetch.bind(window);
function clientBlocked(message){const s=String(message||'').toLowerCase();return /\b(gun|firearm|rifle|pistol|shotgun|ammunition|grenade|explosive|bomb|cocaine|heroin|meth|fentanyl|mdma|lsd|password|cvv|cvc|otp|seed phrase|private key)\b|سلاح|مسدس|بندقية|ذخيرة|قنبلة|متفجر|كوكايين|هيروين|مخدرات|كلمة المرور|رمز التحقق|الرقم السري|مفتاح خاص|عاري|إباحي|porn|nude|naked/iu.test(s)}
function messageLang(message){const t=String(message||''),s=t.toLowerCase();if(/[\u0600-\u06ff]/u.test(t))return'ar';if(/[\u3040-\u30ff]/u.test(t))return'ja';if(/[\u4e00-\u9fff]/u.test(t))return'zh';if(/[\uac00-\ud7af]/u.test(t))return'ko';if(/[\u0900-\u097f]/u.test(t))return'hi';if(/[\u0400-\u052f]/u.test(t))return'ru';if(/[ğüşöçıİ]/u.test(t)||/\b(merhaba|istiyorum|arıyorum|ülke|dil)\b/iu.test(s))return'tr';if(/[àâçéèêëîïôûùüÿœæ]/iu.test(t)||/\b(bonjour|cherche|besoin|voudrais|emploi)\b/iu.test(s))return'fr';if(/[äöüß]/iu.test(t)||/\b(suche|möchte|brauche|stelle|arbeit)\b/iu.test(s))return'de';if(/[ñáéíóúü¿¡]/iu.test(t)||/\b(busco|quiero|necesito|trabajo)\b/iu.test(s))return'es';return'en'}
function languageMatches(text,lang){text=String(text||'');if(lang==='ar')return/[\u0600-\u06ff]/u.test(text);if(lang==='zh')return/[\u4e00-\u9fff]/u.test(text);if(lang==='ja')return/[\u3040-\u30ff]/u.test(text);if(lang==='ko')return/[\uac00-\ud7af]/u.test(text);if(lang==='hi')return/[\u0900-\u097f]/u.test(text);if(lang==='ru')return/[\u0400-\u052f]/u.test(text);return true}
function emergencyReply(message){const l=messageLang(message),r={ar:'فهمت طلبك. رح ساعدك من داخل SEEKVERA وأفتح لك القسم المناسب لتكمل مباشرة.',en:'I understand. I’ll keep helping inside SEEKVERA and take you to the right section to continue.',fr:'J’ai compris. Je continue à vous aider dans SEEKVERA et je vous dirige vers la bonne section.',tr:'Anladım. SEEKVERA içinde yardımcı olmaya devam edip sizi doğru bölüme yönlendireceğim.',de:'Verstanden. Ich helfe in SEEKVERA weiter und führe Sie zum passenden Bereich.',es:'Entendido. Seguiré ayudándote en SEEKVERA y te llevaré a la sección adecuada.',ru:'Понял. Я продолжу помогать в SEEKVERA и переведу вас в нужный раздел.',zh:'明白了。我会继续在 SEEKVERA 中帮助你，并带你进入正确的栏目。',ja:'わかりました。SEEKVERA内で引き続きサポートし、適切なセクションへ案内します。',hi:'समझ गया। मैं SEEKVERA में आपकी मदद जारी रखूँगा और सही सेक्शन पर ले जाऊँगा।',ko:'알겠습니다. SEEKVERA에서 계속 도와드리고 알맞은 섹션으로 안내하겠습니다.'};return{ok:true,response:r[l]||r.en,language:l,category:'general',route:'marketplace.html',countryAction:null,languageAction:null,model:'seekvera-r76-local-emergency',degraded:true,providerAvailable:false,retryable:false,browserBackup:true}}
async function browserAiBackup(body={},base={}){const message=String(body?.message||body?.prompt||'').trim();if(!message||base?.blocked||base?.reviewRequired)return null;if(clientBlocked(message))return{ok:true,blocked:true,reviewRequired:true,response:messageLang(message)==='ar'?'ما فيني أساعد بشراء أو بيع أو ترويج أشياء محظورة أو غير قانونية.':'SEEKVERA cannot help buy, sell, source or promote prohibited or illegal items or services.',language:messageLang(message),category:'general',route:'marketplace.html',countryAction:null,languageAction:null,model:'seekvera-r76-browser-safety',browserBackup:true};const history=Array.isArray(body?.history)?body.history.slice(-8).map(x=>String(x?.role||'user')+': '+String(x?.content||'')).join('\n'):'';const lang=messageLang(message);const prompt=['You are SEEKVERA AI, the helpful assistant inside a worldwide discovery and marketplace app.','Understand the latest user message in any language and reply naturally in that SAME language and script unless the user explicitly requests another language.','Be concise, practical and conversational. Help the user find the correct SEEKVERA section when relevant. Never invent live prices, availability, bookings, jobs, company replies or guarantees. Never request passwords, OTP, PIN or CVV.','Selected market: '+String(body?.country||'Worldwide')+'.','Conversation context: '+history.slice(-1800),'Latest user message: '+message.slice(0,1200)].join('\n');const u='https://text.pollinations.ai/'+encodeURIComponent(prompt)+'?model=openai&private=true';const ctl=new AbortController(),to=setTimeout(()=>ctl.abort(),6000);try{const r=await nativeFetch(u,{method:'GET',headers:{accept:'text/plain'},signal:ctl.signal,cache:'no-store'});if(r.ok){const text=String(await r.text()).trim().slice(0,5000);if(text&&languageMatches(text,lang))return{...base,ok:true,response:text,language:lang,model:'pollinations-browser-private-backup',degraded:true,providerAvailable:true,retryable:false,browserBackup:true}}}catch{}finally{clearTimeout(to)}return emergencyReply(message)}
window.fetch=async function(input,init){if(!sameApi(input))return nativeFetch(input,init);let controls={},body={};let raw=init?.body;try{if(raw==null&&typeof Request!=='undefined'&&input instanceof Request)raw=await input.clone().text();body=typeof raw==='string'?JSON.parse(raw):{};controls=detectControls(body?.message||body?.prompt||'')}catch{}let res=null,data=null,networkError=false;try{res=await nativeFetch(input,init)}catch{networkError=true}if(res)try{data=await res.clone().json()}catch{}let usedBackup=false;const blocked=!!(data?.blocked||data?.reviewRequired);const needBackup=!blocked&&(networkError||!res||res.status===429||res.status>=500||!data||!String(data?.response||'').trim());if(needBackup){const backup=await browserAiBackup(body,data||{});if(backup){data=backup;usedBackup=true}}if(!data){if(res)return res;throw Error('SEEKVERA AI unavailable')}const server={country:data?.countryAction?.code||'',language:data?.languageAction?.code||''};const languageOnly=!!controls.language&&!controls.country;const countryOnly=!!controls.country&&!controls.language;const merged={country:String(languageOnly?'':(controls.country||server.country||'')).toUpperCase(),language:String(countryOnly?(server.language||''):(controls.language||server.language||'')).toLowerCase()};if(merged.country||merged.language)applyControls(merged);if(!usedBackup&&!merged.country&&!merged.language&&res)return res;const payload={...data,...actionPayload(merged),controlVersion:VERSION};const headers=new Headers(res?.headers||{});headers.set('content-type','application/json; charset=utf-8');headers.set('cache-control','no-store');if(usedBackup)headers.set('x-seekvera-ai-mode','browser-resilient-backup');return new Response(JSON.stringify(payload),{status:usedBackup?200:(res?.status||200),headers})};
'''
s=s[:start]+block+s[end:]
p.write_text(s,encoding='utf-8')

# Make local app-control acknowledgement natural and same-language before the actual switch.
p=Path('r31-ui-polish.js');s=p.read_text(encoding='utf-8')
s=re.sub(r"function controlReply\(c,q\)\{.*?\}\nfunction pendingVoiceOnNextPage",'''function controlReply(c,q){const t=String(q||'');if(/[\\u0600-\\u06ff]/u.test(t))return'تمام، فهمت. رح أغيّر إعداد التطبيق الآن مثل ما طلبت.';const l=lang();const r={en:'Got it. I’ll change the app setting now as requested.',fr:'Compris. Je change maintenant le réglage de l’application comme demandé.',tr:'Tamam. Uygulama ayarını şimdi istediğiniz gibi değiştiriyorum.',de:'Verstanden. Ich ändere die App-Einstellung jetzt wie gewünscht.',es:'Entendido. Ahora cambio la configuración de la app como pediste.',ru:'Понял. Сейчас изменю настройку приложения, как вы попросили.',zh:'明白了。我现在按你的要求更改应用设置。',hi:'समझ गया। अब मैं ऐप की सेटिंग आपके अनुरोध के अनुसार बदल रहा हूँ।'};return r[l]||r.en}\nfunction pendingVoiceOnNextPage''',s,count=1,flags=re.S)
p.write_text(s,encoding='utf-8')

# Future release stamping must also remove visible stale R74/R75 labels.
p=Path('tools/r76_apply_release.py');s=p.read_text(encoding='utf-8')
anchor="    if 'data-release=' in x:x=re.sub(r'data-release=\"[^\"]+\"','data-release=\"'+VER+'\"',x,count=1)\n"
if "R76</small>" not in s:
    repl=anchor+"    x=re.sub(r'(<small>2026-09-26\\s*·\\s*)R\\d+(</small>)',r'\\1R76\\2',x)\n    x=re.sub(r'<!--\\s*20260926-r\\d+[^>]*-->', '<!-- '+VER+' -->', x, count=1)\n"
    if anchor not in s: raise SystemExit('apply release HTML anchor missing')
    s=s.replace(anchor,repl,1)
p.write_text(s,encoding='utf-8')

print('R76 resilience patch applied')
